module_name: mb12xx
parameters:
- group: Sensors
  definitions:
    SENS_EN_MB12XX:
      description:
        short: Maxbotix Sonar (mb12xx)
      type: boolean
      default: 0
      reboot_required: true
    SENS_MB12_0_ROT:
      description:
        short: MaxBotix MB12XX Sensor 0 Rotation
        long: This parameter defines the rotation of the sensor relative to the platform.
      type: enum
      values:
        0: No rotation
        1: "Yaw 45\xB0"
        2: "Yaw 90\xB0"
        3: "Yaw 135\xB0"
        4: "Yaw 180\xB0"
        5: "Yaw 225\xB0"
        6: "Yaw 270\xB0"
        7: "Yaw 315\xB0"
      default: 0
      reboot_required: true
      min: 0
      max: 7
    SENS_MB12_1_ROT:
      description:
        short: MaxBotix MB12XX Sensor 1 Rotation
        long: This parameter defines the rotation of the sensor relative to the platform.
      type: enum
      values:
        0: No rotation
        1: "Yaw 45\xB0"
        2: "Yaw 90\xB0"
        3: "Yaw 135\xB0"
        4: "Yaw 180\xB0"
        5: "Yaw 225\xB0"
        6: "Yaw 270\xB0"
        7: "Yaw 315\xB0"
      default: 0
      reboot_required: true
      min: 0
      max: 7
    SENS_MB12_2_ROT:
      description:
        short: MaxBotix MB12XX Sensor 2 Rotation
        long: This parameter defines the rotation of the sensor relative to the platform.
      type: enum
      values:
        0: No rotation
        1: "Yaw 45\xB0"
        2: "Yaw 90\xB0"
        3: "Yaw 135\xB0"
        4: "Yaw 180\xB0"
        5: "Yaw 225\xB0"
        6: "Yaw 270\xB0"
        7: "Yaw 315\xB0"
      default: 0
      reboot_required: true
      min: 0
      max: 7
    SENS_MB12_3_ROT:
      description:
        short: MaxBotix MB12XX Sensor 3 Rotation
        long: This parameter defines the rotation of the sensor relative to the platform.
      type: enum
      values:
        0: No rotation
        1: "Yaw 45\xB0"
        2: "Yaw 90\xB0"
        3: "Yaw 135\xB0"
        4: "Yaw 180\xB0"
        5: "Yaw 225\xB0"
        6: "Yaw 270\xB0"
        7: "Yaw 315\xB0"
      default: 0
      reboot_required: true
      min: 0
      max: 7
    SENS_MB12_4_ROT:
      description:
        short: MaxBotix MB12XX Sensor 4 Rotation
        long: This parameter defines the rotation of the sensor relative to the platform.
      type: enum
      values:
        0: No rotation
        1: "Yaw 45\xB0"
        2: "Yaw 90\xB0"
        3: "Yaw 135\xB0"
        4: "Yaw 180\xB0"
        5: "Yaw 225\xB0"
        6: "Yaw 270\xB0"
        7: "Yaw 315\xB0"
      default: 0
      reboot_required: true
      min: 0
      max: 7
    SENS_MB12_5_ROT:
      description:
        short: MaxBotix MB12XX Sensor 5 Rotation
        long: This parameter defines the rotation of the sensor relative to the platform.
      type: enum
      values:
        0: No rotation
        1: "Yaw 45\xB0"
        2: "Yaw 90\xB0"
        3: "Yaw 135\xB0"
        4: "Yaw 180\xB0"
        5: "Yaw 225\xB0"
        6: "Yaw 270\xB0"
        7: "Yaw 315\xB0"
      default: 0
      reboot_required: true
      min: 0
      max: 7
    SENS_MB12_6_ROT:
      description:
        short: MaxBotix MB12XX Sensor 6 Rotation
        long: This parameter defines the rotation of the sensor relative to the platform.
      type: enum
      values:
        0: No rotation
        1: "Yaw 45\xB0"
        2: "Yaw 90\xB0"
        3: "Yaw 135\xB0"
        4: "Yaw 180\xB0"
        5: "Yaw 225\xB0"
        6: "Yaw 270\xB0"
        7: "Yaw 315\xB0"
      default: 0
      reboot_required: true
      min: 0
      max: 7
    SENS_MB12_7_ROT:
      description:
        short: MaxBotix MB12XX Sensor 7 Rotation
        long: This parameter defines the rotation of the sensor relative to the platform.
      type: enum
      values:
        0: No rotation
        1: "Yaw 45\xB0"
        2: "Yaw 90\xB0"
        3: "Yaw 135\xB0"
        4: "Yaw 180\xB0"
        5: "Yaw 225\xB0"
        6: "Yaw 270\xB0"
        7: "Yaw 315\xB0"
      default: 0
      reboot_required: true
      min: 0
      max: 7
    SENS_MB12_8_ROT:
      description:
        short: MaxBotix MB12XX Sensor 8 Rotation
        long: This parameter defines the rotation of the sensor relative to the platform.
      type: enum
      values:
        0: No rotation
        1: "Yaw 45\xB0"
        2: "Yaw 90\xB0"
        3: "Yaw 135\xB0"
        4: "Yaw 180\xB0"
        5: "Yaw 225\xB0"
        6: "Yaw 270\xB0"
        7: "Yaw 315\xB0"
      default: 0
      reboot_required: true
      min: 0
      max: 7
    SENS_MB12_9_ROT:
      description:
        short: MaxBotix MB12XX Sensor 9 Rotation
        long: This parameter defines the rotation of the sensor relative to the platform.
      type: enum
      values:
        0: No rotation
        1: "Yaw 45\xB0"
        2: "Yaw 90\xB0"
        3: "Yaw 135\xB0"
        4: "Yaw 180\xB0"
        5: "Yaw 225\xB0"
        6: "Yaw 270\xB0"
        7: "Yaw 315\xB0"
      default: 0
      reboot_required: true
      min: 0
      max: 7
    SENS_MB12_10_ROT:
      description:
        short: MaxBotix MB12XX Sensor 10 Rotation
        long: This parameter defines the rotation of the sensor relative to the platform.
      type: enum
      values:
        0: No rotation
        1: "Yaw 45\xB0"
        2: "Yaw 90\xB0"
        3: "Yaw 135\xB0"
        4: "Yaw 180\xB0"
        5: "Yaw 225\xB0"
        6: "Yaw 270\xB0"
        7: "Yaw 315\xB0"
      default: 0
      reboot_required: true
      min: 0
      max: 7
    SENS_MB12_11_ROT:
      description:
        short: MaxBotix MB12XX Sensor 12 Rotation
        long: This parameter defines the rotation of the sensor relative to the platform.
      type: enum
      values:
        0: No rotation
        1: "Yaw 45\xB0"
        2: "Yaw 90\xB0"
        3: "Yaw 135\xB0"
        4: "Yaw 180\xB0"
        5: "Yaw 225\xB0"
        6: "Yaw 270\xB0"
        7: "Yaw 315\xB0"
      default: 0
      reboot_required: true
      min: 0
      max: 7
