#!/usr/bin/bash
# PX4 commands need the 'px4-' prefix in bash.
# (px4-alias.sh is expected to be in the PATH)
source px4-alias.sh

uorb start
param set SDLOG_DIRS_MAX 7

ekf2 start -r
logger start -f -t -b 1000 -p vehicle_attitude
sleep 0.2
replay start

