list(APPEND module_directories
	./src/platforms/posix/px4_layer
	./src/platforms/posix/work_queue
	./src/platforms/posix/drivers/adcsim
	./src/platforms/posix/drivers/gpssim
	./src/platforms/posix/drivers/tonealrmsim
	./src/platforms/posix/drivers/accelsim
	./src/platforms/posix/drivers/airspeedsim
	./src/platforms/posix/drivers/barosim
	./src/platforms/posix/drivers/gyrosim
	./src/systemcmds/param
	./src/systemcmds/mixer
	./src/systemcmds/topic_listener
	./src/systemcmds/ver
	./src/systemcmds/esc_calib
	./src/systemcmds/reboot
	./src/modules/sensors
	./src/modules/mavlink
	./src/modules/attitude_estimator_ekf
	./src/modules/attitude_estimator_q
	./src/modules/ekf_att_pos_estimator
	./src/modules/position_estimator_inav
	./src/modules/navigator
	./src/modules/mc_pos_control
	./src/modules/mc_att_control
	./src/modules/mc_pos_control_multiplatform
	./src/modules/mc_att_control_multiplatform
	./src/modules/land_detector
	./src/modules/fw_att_control
	./src/modules/fw_pos_control_l1
	./src/modules/dataman
	./src/modules/sdlog2
	./src/modules/simulator
	./src/modules/commander
	./src/modules/controllib
	./src/lib/mathlib
	./src/lib/ecl
	./src/lib/external_lgpl
	./src/lib/geo
	./src/lib/geo_lookup
	./src/lib/launchdetection
	)

