#!/bin/sh
#
# @name IF750A SITL
# InspiredFlight 750 Auterion edition. Gazebo Only.
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

if [ $AUTOCNF = yes ]
then
	# EKF2: Multi GPS blending (as the model has 2 GPS's)
	param set EKF2_GPS_MASK 7 # Uses speed, hpos and vpos accuracy
	param set TRIG_INTERFACE 3
	param set TRIG_MODE 4
	param set MNT_MODE_IN 4
	param set MNT_MODE_OUT 2
	param set MNT_DO_STAB 2

fi

set MIXER quad_x
