#!/bin/sh
#
# @name VTOL + Tailsitter
#
# @type VTOL Coaxial Tailsitter
#

. ${R}etc/init.d/rc.vtol_defaults

param set-default SENS_EN_ARSPDSIM 0
param set-default FW_USE_AIRSPD 0
param set-default SYS_HAS_NUM_ASPD 0
param set-default MPC_THR_HOVER	0.7

param set-default MAV_TYPE 19
param set-default EKF2_FUSE_BETA 0

param set-default CA_AIRFRAME 16
param set-default CA_ROTOR_COUNT 2
param set-default CA_ROTOR0_KM -0.05
param set-default CA_ROTOR0_PY -0.0
param set-default CA_ROTOR1_KM 0.05
param set-default CA_ROTOR1_PY 0.0
param set-default CA_SV_CS_COUNT 2
param set-default CA_SV_CS0_TRQ_P -0.5
param set-default CA_SV_CS0_TRQ_Y 0.0
param set-default CA_SV_CS0_TYPE 3
param set-default CA_SV_CS1_TRQ_P 0.0
param set-default CA_SV_CS1_TRQ_Y 0.0
param set-default CA_SV_CS1_TRQ_R 0.5
param set-default CA_SV_CS1_TYPE 4

param set-default SENS_BOARD_ROT	24

param set-default VT_TYPE 0
param set-default VT_ELEV_MC_LOCK 0
param set-default VT_B_TRANS_DUR 5

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 201
param set-default PWM_MAIN_FUNC4 202


# Single-EKF (for replay)
param set-default EKF2_MULTI_IMU 0
param set-default SENS_IMU_MODE 1

param set-default FW_P_TC 0.6

param set-default FW_PR_FF 0.0
param set-default FW_PSP_OFF 2
param set-default FW_RR_FF 0.1
param set-default FW_RR_I 0.2
param set-default FW_RR_P 0.5
param set-default FW_THR_TRIM 0.35
param set-default FW_THR_MAX 0.8
param set-default FW_THR_MIN 0.05
param set-default FW_T_CLMB_MAX 6
param set-default FW_T_HRATE_FF 0.5
param set-default FW_T_SINK_MAX 3
param set-default FW_T_SINK_MIN 1.6

param set-default MC_AIRMODE 1
param set-default MC_ROLL_P 3
param set-default MC_PITCH_P 3

param set-default VT_ARSP_TRANS 10
param set-default VT_B_TRANS_DUR 5
param set-default VT_FW_DIFTHR_EN 1
param set-default VT_FW_DIFTHR_S_Y 1
param set-default VT_F_TRANS_DUR 1.5
param set-default VT_TYPE 0

param set-default WV_EN 0

