#!/bin/sh
#
# @name PX4Vision SITL
# Holybro px4vision. Gazebo Only.
#
# @type Quadrotor
#

. ${R}etc/init.d/airframes/4016_holybro_px4vision

# PX4 default motor ordering:
#  3     1
#     ^
#  2     4
param set-default SYS_CTRL_ALLOC 1
param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

# front right (CCW)
param set-default CA_ROTOR0_PX 0.707107
param set-default CA_ROTOR0_PY 0.707107
param set-default CA_ROTOR0_KM 0.05

# rear left (CCW)
param set-default CA_ROTOR1_PX -0.707107
param set-default CA_ROTOR1_PY -0.707107
param set-default CA_ROTOR1_KM 0.05

# front left (CW)
param set-default CA_ROTOR2_PX 0.707107
param set-default CA_ROTOR2_PY -0.707107
param set-default CA_ROTOR2_KM -0.05

# rear right (CW)
param set-default CA_ROTOR3_PX -0.707107
param set-default CA_ROTOR3_PY 0.707107
param set-default CA_ROTOR3_KM -0.05

set MIXER skip
set MIXER_AUX none
