#!/bin/sh
#
# @name QuadrotorX SITL for SIH, navput ranging-beacon setup
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=sihsim}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=quadx}

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 1
param set-default SENS_EN_MAGSIM 1

# Square quadrotor X PX4 numbering
param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 1
param set-default CA_ROTOR0_PY 1
param set-default CA_ROTOR1_PX -1
param set-default CA_ROTOR1_PY -1
param set-default CA_ROTOR2_PX 1
param set-default CA_ROTOR2_PY -1
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -1
param set-default CA_ROTOR3_PY 1
param set-default CA_ROTOR3_KM -0.05

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104

param set-default SENS_GPS0_DELAY 0
param set-default SENS_GPS1_DELAY 0

param set SIH_VEHICLE_TYPE 0

param set-default ZENOH_ENABLE 1

param set-default EKF2_RNGBC_CTRL 1
param set-default EKF2_AGP0_ID 123
param set-default EKF2_AGP0_CTRL 1

param set-default SIH_RNGBC_EN 1
param set-default SIH_RNGBC_INTV 134
param set-default SIH_RNGBC_NOISE 50.0

param set-default SENS_EN_AGPSIM 1
param set-default SIM_AGP_NOISE 30
param set-default SIM_AGP_INTV 500

navputer start
