#!/bin/sh
#
# @name QuadrotorX SITL for SIH with optical flow
#
# @type Simulation
# @class Quadrotor
#

PX4_SIM_MODEL=${PX4_SIM_MODEL:=quadx_flow}

. ${R}etc/init.d-posix/airframes/10040_sihsim_quadx

param set-default SIH_OF_EN 1
param set-default SIH_OF_H_MAX 30
param set-default SIH_DISTSNSR_EN 1
param set-default SIH_DISTSNSR_MAX 30

param set-default SENS_EN_GPSSIM 1
param bitclear EKF2_SENS_EN 3 # disable gps fusion
param set-default EKF2_RNG_CTRL 2
param set-default EKF2_HGT_REF 0
