#!/bin/sh
# @name Boat (Ackermann style)
# @type Boat
# @class Boat

. ${R}etc/init.d/rc.boat_defaults

set VEHICLE_TYPE boat
param set-default CA_AIRFRAME 5         # Rover (Ackermann)
param set-default CA_R_REV 1            # Motor is assumed to be reversible
param set-default EKF2_MAG_TYPE 1       # Make sure magnetometer is fused even when not flying
param set-default NAV_ACC_RAD 0.5       # Waypoint acceptance radius
param set-default EKF2_GBIAS_INIT 0.01
param set-default EKF2_ANGERR_INIT 0.01


PX4_SIMULATOR=${PX4_SIMULATOR:=sihsim}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=boat}

param set-default SIH_VEHICLE_TYPE 4 	# sih as boat

#param set-default SIH_MASS 3.0
#param set-default SIH_IXX 0.00402
#param set-default SIH_IYY 0.0144
#param set-default SIH_IZZ 0.0177
#param set-default SIH_IXZ 0.00046
#param set-default SIH_KDV 0.2

param set-default PWM_MAIN_FUNC1 201 # Steering
param set-default PWM_MAIN_FUNC2 101 # Throttle

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 1
param set-default SENS_EN_MAGSIM 1
#param set-default SENS_EN_ARSPDSIM 1

param set-default NAV_ACC_RAD 0.5

# Ackermann Parameters
param set-default RA_WHEEL_BASE 0.321
param set-default RA_ACC_RAD_GAIN 2
param set-default RA_ACC_RAD_MAX 3
param set-default RA_MAX_STR_ANG 0.5236
param set-default RA_STR_RATE_LIM 360

# Rover Control Parameters
param set-default RO_ACCEL_LIM 3
param set-default RO_DECEL_LIM 6
param set-default RO_JERK_LIM 15
param set-default RO_MAX_THR_SPEED 3.1

# Rover Rate Control Parameters
param set-default RO_YAW_RATE_I 0.1
param set-default RO_YAW_RATE_P 1
param set-default RO_YAW_RATE_LIM 180

# Rover Attitude Control Parameters
param set-default RO_YAW_P 3

# Rover Position Control Parameters
param set-default RO_SPEED_LIM 3
param set-default RO_SPEED_I 0.1
param set-default RO_SPEED_P 1

# Pure Pursuit parameters
param set-default PP_LOOKAHD_GAIN 1
param set-default PP_LOOKAHD_MAX 10
param set-default PP_LOOKAHD_MIN 1

# Wheels
param set-default SIM_GZ_WH_FUNC1 101
param set-default SIM_GZ_WH_MIN1 0
param set-default SIM_GZ_WH_MAX1 200
param set-default SIM_GZ_WH_DIS1 100

# Steering
param set-default SIM_GZ_SV_MAXA1 30
param set-default SIM_GZ_SV_MINA1 -30
param set-default CA_SV_CS_COUNT 1
param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_REV 1
