#!/bin/sh
#
# @name Plane SITL for SIH
#
# @type Plane
#
# @maintainer Romain Chiappinelli <romain.chiap@gmail.com>

. ${R}etc/init.d/rc.fw_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=sihsim}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=airplane}

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 1
param set-default SENS_EN_MAGSIM 1
param set-default SENS_EN_ARSPDSIM 1

param set-default SIH_MASS 0.3
param set-default SIH_IXX 0.00402
param set-default SIH_IYY 0.0144
param set-default SIH_IZZ 0.0177
param set-default SIH_IXZ 0.00046
param set-default SIH_KDV 0.2

# pusher propeller model with advance ratio, model from UIUC APC 8x6"
param set-default SIH_F_CT0 0.131
param set-default SIH_F_CT1 0.004
param set-default SIH_F_CT2 -0.146
param set-default SIH_F_CP0 0.0777
param set-default SIH_F_CP1 0.0498
param set-default SIH_F_CP2 -0.11
param set-default SIH_F_DIA_INCH 8
param set-default SIH_F_RPM_MAX 13000

param set-default SIH_VEHICLE_TYPE 1 # sih as fixed wing
param set-default RWTO_TKOFF 1 # enable takeoff from runway (as opposed to launched)

# 13000 RPM gives ~11 N of thrust at trim airspeed, which is a 30 deg climb at
# trim and 20 m/s in level flight. Raise the climb rate so TECS
# can command that climb (15 m/s * sin(30 deg) = 7.5 m/s)
param set-default FW_T_CLMB_MAX 8

param set-default CA_ROTOR_COUNT 1
param set-default CA_ROTOR0_PX 0.3

# SIH for now hardcodes this configuration which we need to match in the airframe files.
param set-default CA_SV_CS_COUNT 3
param set-default CA_SV_CS0_TRQ_R 1
param set-default CA_SV_CS0_TYPE 15 # single channel aileron
param set-default CA_SV_CS1_TRQ_P 1
param set-default CA_SV_CS1_TYPE 3 # elevator
param set-default CA_SV_CS2_TRQ_Y 1
param set-default CA_SV_CS2_TYPE 4 # rudder

param set-default PWM_MAIN_FUNC1 201
param set-default PWM_MAIN_FUNC2 202
param set-default PWM_MAIN_FUNC3 203
param set-default PWM_MAIN_FUNC4 101

param set-default SENS_GPS0_DELAY 0
param set-default SENS_GPS1_DELAY 0

# Rate controllers
param set-default FW_RR_P 0.05
param set-default FW_RR_I 2
param set-default FW_RR_D 0
param set-default FW_RR_FF 0
param set-default FW_RR_IMAX 1

param set-default FW_PR_P 0.08
param set-default FW_PR_I 2.5
param set-default FW_PR_D 0
param set-default FW_PR_FF 0
param set-default FW_PR_IMAX 1

param set-default FW_YR_P 0.05
param set-default FW_YR_I 3
param set-default FW_YR_D 0
param set-default FW_YR_FF 0
param set-default FW_YR_IMAX 1
