#!/bin/sh
#
# @name 3DR Iris Quadrotor SITL (Vision)
#
# @type Quadrotor Wide
#

. ${R}etc/init.d-posix/airframes/10016_iris

# EKF2: Vision position and heading
param set-default EKF2_AID_MASK 24
param set-default EKF2_EV_DELAY 5

# LPE: Vision + baro
param set-default LPE_FUSION 132

# AEQ: External heading set to use vision input
param set-default ATT_EXT_HDG_M 1

