#!/bin/sh
#
# @name Solo
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

param set-default SYS_CTRL_ALLOC 1

param set-default CA_AIRFRAME 0

param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 0.145
param set-default CA_ROTOR0_PY 0.145
param set-default CA_ROTOR0_KM 0.05
param set-default CA_ROTOR1_PX -0.145
param set-default CA_ROTOR1_PY -0.145
param set-default CA_ROTOR1_KM 0.05
param set-default CA_ROTOR2_PX 0.145
param set-default CA_ROTOR2_PY -0.145
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -0.145
param set-default CA_ROTOR3_PY 0.145
param set-default CA_ROTOR3_KM -0.05

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104

param set-default MC_PITCHRATE_P 0.1
param set-default MC_ROLLRATE_P 0.05

set MIXER skip
set MIXER_AUX none
