#!/bin/sh
#
# @name 3DR Iris Quadrotor SITL (Obstacle Avoidance)
#
# @type Quadrotor Wide
#

. ${R}etc/init.d-posix/airframes/10016_iris

if [ $AUTOCNF = yes ]
then
	param set COM_OBS_AVOID 1
	param set MPC_XY_CRUISE 5.0
fi
