#!/bin/sh
#
# @name UUV
#

. ${R}etc/init.d/rc.uuv_defaults

#Set data link loss failsafe mode (0: disabled)
param set-default NAV_DLL_ACT 0

# disable circuit breaker for airspeed sensor
param set-default CBRK_AIRSPD_CHK 162128

#param set CBRK_GPSFAIL 240024

set MAV_TYPE 12
param set MAV_TYPE ${MAV_TYPE}

set MIXER_FILE etc/mixers-sitl/uuv_x_sitl.main.mix
set MIXER custom
