#!/bin/sh
#
# @name Hippocampus UUV
#

. ${R}etc/init.d/rc.uuv_defaults

# disable circuit breaker for airspeed sensor
param set-default CBRK_AIRSPD_CHK 162128

set MIXER_FILE etc/mixers-sitl/uuv_x_sitl.main.mix
set MIXER custom
