#!/bin/sh
#
# @name Plane SITL
#

. ${R}etc/init.d/rc.fw_defaults

param set-default EKF2_MAG_ACCLIM 0
param set-default EKF2_MAG_YAWLIM 0

param set-default FW_LND_AIRSPD_SC 1
param set-default FW_LND_ANG 8
param set-default FW_THR_LND_MAX 0

param set-default FW_L1_PERIOD 12

param set-default FW_MAN_P_MAX 30

param set-default FW_PR_P 0.9
param set-default FW_PR_FF 0.2
param set-default FW_PSP_OFF 2
param set-default FW_P_LIM_MAX 32
param set-default FW_P_LIM_MIN -15

param set-default FW_RR_FF 0.1
param set-default FW_RR_P 0.3

param set-default FW_THR_MAX 0.6
param set-default FW_THR_MIN 0.05
param set-default FW_THR_CRUISE 0.25

param set-default FW_T_CLMB_MAX 8
param set-default FW_T_SINK_MAX 2.7
param set-default FW_T_SINK_MIN 2.2

param set-default FW_W_EN 1

param set-default MIS_LTRMIN_ALT 30
param set-default MIS_TAKEOFF_ALT 30

param set-default NAV_ACC_RAD 15
param set-default NAV_DLL_ACT 2

param set-default RWTO_TKOFF 1

#param set-default SYS_CTRL_ALLOC 1
param set-default CA_AIRFRAME 1

param set-default CA_ROTOR_COUNT 1
param set-default CA_ROTOR0_PX 0.3

param set-default CA_SV_CS_COUNT 6
param set-default CA_SV_CS0_TRQ_Y 1.0000
param set-default CA_SV_CS0_TYPE 2
param set-default CA_SV_CS1_TYPE 7
param set-default CA_SV_CS2_TRQ_P -1.0000
param set-default CA_SV_CS2_TRQ_R 1.0000
param set-default CA_SV_CS2_TYPE 9
param set-default CA_SV_CS3_TRQ_P 1.0000
param set-default CA_SV_CS3_TRQ_R 1.0000
param set-default CA_SV_CS3_TYPE 10
param set-default CA_SV_CS4_TRQ_P 1.0000
param set-default CA_SV_CS5_TYPE 8

param set-default PWM_MAIN_FUNC3 201
param set-default PWM_MAIN_FUNC4 202
param set-default PWM_MAIN_FUNC5 101
param set-default PWM_MAIN_FUNC6 203
param set-default PWM_MAIN_FUNC7 204
param set-default PWM_MAIN_FUNC8 205
param set-default PWM_MAIN_FUNC9 206
param set-default PWM_MAIN_REV 288


set MIXER_FILE etc/mixers-sitl/plane_sitl.main.mix
set MIXER custom
