#!/bin/sh
#
# @name Plane SITL
#

. ${R}etc/init.d/rc.fw_defaults

param set-default EKF2_ARSP_THR 8
param set-default EKF2_FUSE_BETA 1
param set-default EKF2_MAG_ACCLIM 0
param set-default EKF2_MAG_YAWLIM 0

param set-default FW_LND_AIRSPD_SC 1
param set-default FW_LND_ANG 8
param set-default FW_THR_LND_MAX 0

param set-default FW_L1_PERIOD 15

param set-default FW_P_TC 0.5
param set-default FW_PR_FF 0.40
param set-default FW_PR_I 0.05
param set-default FW_PR_P 0.05

param set-default FW_R_TC 0.7
param set-default FW_RR_FF 0.20
param set-default FW_RR_I 0.02
param set-default FW_RR_P 0.22

param set-default FW_L1_PERIOD 12

param set-default FW_W_EN 1

param set-default MIS_LTRMIN_ALT 30
param set-default MIS_TAKEOFF_ALT 30

param set-default NAV_ACC_RAD 15
param set-default NAV_DLL_ACT 2
param set-default NAV_LOITER_RAD 50

param set-default RWTO_TKOFF 1

set MIXER_FILE etc/mixers-sitl/plane_sitl.main.mix
set MIXER custom
