#!/bin/sh
#
# @name Standard VTOL
#
# @type Standard VTOL
#

. ${R}etc/init.d/rc.vtol_defaults

if [ $AUTOCNF = yes ]
then
	param set FW_L1_PERIOD 12
	param set FW_MAN_P_MAX 30
	param set FW_PR_FF 0.2
	param set FW_PR_I 0.4
	param set FW_PR_P 0.9
	param set FW_PSP_OFF 2
	param set FW_P_LIM_MAX 32
	param set FW_P_LIM_MIN -15
	param set FW_RR_FF 0.1
	param set FW_RR_P 0.3
	param set FW_THR_CRUISE 0.25
	param set FW_THR_MAX 0.6
	param set FW_THR_MIN 0.05
	param set FW_T_ALT_TC 2
	param set FW_T_CLMB_MAX 8
	param set FW_T_HRATE_FF 0.5
	param set FW_T_SINK_MAX 2.7
	param set FW_T_SINK_MIN 2.2
	param set FW_T_TAS_TC 2

	param set MC_ROLLRATE_P 0.3
	param set MC_YAW_P 1.6

	param set MIS_TAKEOFF_ALT 10

	param set MPC_ACC_HOR_MAX 2
	param set MPC_XY_P 0.8
	param set MPC_XY_VEL_P_ACC 3
	param set MPC_XY_VEL_I_ACC 4
	param set MPC_XY_VEL_D_ACC 0.1

	param set NAV_ACC_RAD 5
	param set NAV_LOITER_RAD 80

	param set VT_FWD_THRUST_EN 4
	param set VT_F_TRANS_THR 0.75
	param set VT_MOT_ID 1234
	param set VT_FW_MOT_OFFID 1234
	param set VT_B_TRANS_DUR 8
	param set VT_TYPE 2

	param set RC_MAP_AUX1 8
	param set RC_MAP_AUX2 9
	param set RC_MAP_AUX3 10
fi

set MAV_TYPE 22

set MIXER_FILE etc/mixers-sitl/standard_vtol_sitl.main.mix
set MIXER custom
