#!/bin/sh
#
# @name Plane SITL
#

. ${R}etc/init.d/rc.fw_defaults

param set-default SYS_CTRL_ALLOC 1

param set-default CA_METHOD 0


param set-default CA_ACT0_FUNC 103 # motor
param set-default CA_ACT1_FUNC 100 # ail left
param set-default CA_ACT2_FUNC 100 # ail right
param set-default CA_ACT3_FUNC 101 # elev
param set-default CA_ACT4_FUNC 102 # rudd
param set-default CA_ACT5_FUNC 121 # left flap
param set-default CA_ACT6_FUNC 121 # right flap


#aileron left
param set-default CA_ACT1_SC -1 # left ail


param set-default PWM_MAIN_FUNC1 0
param set-default PWM_MAIN_FUNC2 0
param set-default PWM_MAIN_FUNC3 204 # rudder
param set-default PWM_MAIN_FUNC4 205 # flap left
param set-default PWM_MAIN_FUNC5 101 # motor
param set-default PWM_MAIN_FUNC6 201 # aileron left
param set-default PWM_MAIN_FUNC7 202 # aileron right
param set-default PWM_MAIN_FUNC8 203 # elevator
param set-default PWM_MAIN_FUNC9 206 # flap right


param set-default FW_LND_AIRSPD_SC 1
param set-default FW_LND_ANG 8
param set-default FW_THR_LND_MAX 0

param set-default FW_PR_P 0.9
param set-default FW_PR_FF 0.2
param set-default FW_PSP_OFF 2
param set-default FW_P_LIM_MAX 32
param set-default FW_P_LIM_MIN -15

param set-default FW_RR_FF 0.1
param set-default FW_RR_P 0.3

param set-default FW_THR_MAX 0.6
param set-default FW_THR_MIN 0.05
param set-default FW_THR_CRUISE 0.25

param set-default FW_T_ALT_TC 2
param set-default FW_T_CLMB_MAX 8
param set-default FW_T_HRATE_FF 0.5
param set-default FW_T_SINK_MAX 2.7
param set-default FW_T_SINK_MIN 2.2
param set-default FW_T_TAS_TC 2

param set-default FW_W_EN 1

param set-default RWTO_TKOFF 1

set MIXER skip
