#!/bin/sh
#
# @name Tiltrotor VTOL
#
# @type Tiltrotor
#

. ${R}etc/init.d/rc.vtol_defaults

param set-default SYS_CTRL_ALLOC 1
param set-default CA_METHOD 0

param set-default CA_ACT0_FUNC 1 # motor
param set-default CA_ACT1_FUNC 1 # motor
param set-default CA_ACT2_FUNC 1 # motor
param set-default CA_ACT3_FUNC 1 # motor

param set-default CA_ACT4_FUNC 100 # ail left
param set-default CA_ACT5_FUNC 100 # ail right
param set-default CA_ACT6_FUNC 101 # elev

param set-default CA_ACT7_FUNC 120 # tilt
param set-default CA_ACT8_FUNC 120 # tilt
param set-default CA_ACT9_FUNC 120 # tilt
param set-default CA_ACT10_FUNC 120 # tilt

param set-default CA_ACT0_PX 0.177
param set-default CA_ACT0_PY 0.177
param set-default CA_ACT0_CT 6.5
param set-default CA_ACT0_KM 0.05

param set-default CA_ACT1_PX -0.177
param set-default CA_ACT1_PY -0.177
param set-default CA_ACT1_CT 6.5
param set-default CA_ACT1_KM 0.05

param set-default CA_ACT2_PX 0.177
param set-default CA_ACT2_PY -0.177
param set-default CA_ACT2_CT 6.5
param set-default CA_ACT2_KM -0.05

param set-default CA_ACT3_PX -0.177
param set-default CA_ACT3_PY 0.177
param set-default CA_ACT3_CT 6.5
param set-default CA_ACT3_KM -0.05

param set-default CA_ACT4_SC -1 # left ail

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
param set-default PWM_MAIN_FUNC5 204 # tilt 1
param set-default PWM_MAIN_FUNC6 205 # tilt 2
param set-default PWM_MAIN_FUNC7 206 # tilt 3
param set-default PWM_MAIN_FUNC8 207 # tilt 4
param set-default PWM_MAIN_FUNC9 201 # aileron left
param set-default PWM_MAIN_FUNC10 202 # aileron right
param set-default PWM_MAIN_FUNC11 203 # elevator



param set-default FW_L1_PERIOD 12
param set-default FW_MAN_P_MAX 30
param set-default FW_PR_FF 0.2
param set-default FW_PR_P 0.9
param set-default FW_PSP_OFF 2
param set-default FW_P_LIM_MAX 32
param set-default FW_P_LIM_MIN -15
param set-default FW_RR_FF 0.1
param set-default FW_RR_P 0.3
param set-default FW_THR_CRUISE 0.38
param set-default FW_THR_MAX 0.6
param set-default FW_THR_MIN 0.05
param set-default FW_T_ALT_TC 2
param set-default FW_T_CLMB_MAX 8
param set-default FW_T_HRATE_FF 0.5
param set-default FW_T_SINK_MAX 2.7
param set-default FW_T_SINK_MIN 2.2
param set-default FW_T_TAS_TC 2

param set-default MC_YAW_P 1.6

param set-default MIS_TAKEOFF_ALT 10

param set-default MPC_ACC_HOR_MAX 2
param set-default MPC_XY_P 0.8
param set-default MPC_XY_VEL_P_ACC 3
param set-default MPC_XY_VEL_I_ACC 4
param set-default MPC_XY_VEL_D_ACC 0.1

param set-default NAV_ACC_RAD 5
param set-default NAV_LOITER_RAD 80

param set-default VT_B_TRANS_DUR 8
param set-default VT_FWD_THRUST_EN 4
param set-default VT_MOT_ID 1234
param set-default VT_TILT_TRANS 0.6
param set-default VT_TYPE 1

set MAV_TYPE 21

set MIXER skip
