#!/bin/sh
#
# @name Boat
#

. ${R}etc/init.d/rc.boat_defaults

param set-default GND_L1_DIST 5
param set-default GND_L1_PERIOD 100
param set-default GND_SP_CTRL_MODE 1
param set-default GND_SPEED_THR_SC 1

param set-default GND_SPEED_D 0.001
param set-default GND_SPEED_I 8
param set-default GND_SPEED_IMAX 0.125
param set-default GND_SPEED_P 2

# Rate controller PID values
param set-default GND_RATE_P 1.0
param set-default GND_RATE_I 0.0
param set-default GND_RATE_D 0.0
param set-default GND_RATE_FF 1.0

# SITL Boat can achieve yaw rate of around 0.2 rad/s with full differential
param set-default GND_RATE_MAX 0.2

# SITL Boat has trim speed around 1 m/s
param set-default GND_SPEED_TRIM 1

param set-default GND_THR_CRUISE 0.85
param set-default GND_THR_MAX 1
param set-default GND_THR_MIN 0
param set-default GND_RATE_P 0.08
param set-default GND_RATE_D 0.02
param set-default GND_RATE_FF 0.0
param set-default GND_RATE_I 0.0
param set-default GND_RATE_MAX 0.5

param set-default MIS_LTRMIN_ALT 0.01
param set-default MIS_TAKEOFF_ALT 0.01
param set-default NAV_ACC_RAD 5
param set-default NAV_LOITER_RAD 2

param set-default CBRK_AIRSPD_CHK 162128

param set-default GND_MAX_ANG 0.6

param set-default CA_AIRFRAME 9

# Currently only the 'differential thrust' boat configuration is available in gazebo simulation
# Tools/sitl_gazebo/models/boat/boat.sdf.jinja

# Set airframe as Differential Rover
param set-default CA_AIRFRAME 6

param set-default CA_ROTOR_COUNT 2

param set-default CA_ROTOR0_AX 1
param set-default CA_ROTOR0_AZ 0
param set-default CA_ROTOR0_KM 0
param set-default CA_ROTOR0_PX -2
param set-default CA_ROTOR0_PY -1

param set-default CA_ROTOR0_AX 1
param set-default CA_ROTOR0_AZ 0
param set-default CA_ROTOR0_KM 0
param set-default CA_ROTOR0_PX -2
param set-default CA_ROTOR0_PY 1

# Left Thruster at MAIN1
param set-default PWM_MAIN_FUNC1 101

# Right Thruster MAIN2
param set-default PWM_MAIN_FUNC2 102

