#!/bin/sh
#
# @name Voliro Variable Tilt MuJoCo SITL
#
# @type Hexarotor x
# @class Copter
#
# @maintainer Holiday
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=mujoco}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=voliro_variable_tilt}

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 1
param set-default SENS_EN_MAGSIM 1

param set SIH_VEHICLE_TYPE 4
param set-default MAV_TYPE 13

# MuJoCo thrust_1...thrust_6 order expressed in PX4 FRD. Rotor positions
# are normalized by the 0.315 m arm radius; KM is 0.015 / 0.315 with the
# reaction-torque signs converted from FLU to FRD.
param set-default CA_ROTOR_COUNT 6
param set-default CA_ROTOR0_PX 1
param set-default CA_ROTOR0_PY 0
param set-default CA_ROTOR0_KM -0.0476190476
param set-default CA_ROTOR1_PX 0.5
param set-default CA_ROTOR1_PY -0.866025404
param set-default CA_ROTOR1_KM 0.0476190476
param set-default CA_ROTOR2_PX -0.5
param set-default CA_ROTOR2_PY -0.866025404
param set-default CA_ROTOR2_KM -0.0476190476
param set-default CA_ROTOR3_PX -1
param set-default CA_ROTOR3_PY 0
param set-default CA_ROTOR3_KM 0.0476190476
param set-default CA_ROTOR4_PX -0.5
param set-default CA_ROTOR4_PY 0.866025404
param set-default CA_ROTOR4_KM -0.0476190476
param set-default CA_ROTOR5_PX 0.5
param set-default CA_ROTOR5_PY 0.866025404
param set-default CA_ROTOR5_KM 0.0476190476

# Simulator/HIL channel contract: six motors followed by six independent
# radial-axis tilt servos. The custom allocator is intentionally not enabled.
param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
param set-default PWM_MAIN_FUNC5 105
param set-default PWM_MAIN_FUNC6 106
param set-default PWM_MAIN_FUNC7 201
param set-default PWM_MAIN_FUNC8 202
param set-default PWM_MAIN_FUNC9 203
param set-default PWM_MAIN_FUNC10 204
param set-default PWM_MAIN_FUNC11 205
param set-default PWM_MAIN_FUNC12 206

param set-default SENS_GPS0_DELAY 0
param set-default SENS_GPS1_DELAY 0
param set-default THR_MDL_FAC 1
