#!/bin/sh
#
# @name Gazebo x500 mono cam
#
# @type Quadrotor
#

PX4_SIM_MODEL=${PX4_SIM_MODEL:=x500_mono_cam_down}

. ${R}etc/init.d-posix/airframes/4001_gz_x500

param set-default EKF2_OF_CTRL 1
param set-default EKF2_RNG_A_VMAX 3

echo "disabling Sim GPS sats"
param set-default SIM_GPS_USED 0
