#!/bin/sh
#
# @name Gazebo x500 lidar down
#
# @type Quadrotor
#

PX4_SIM_MODEL=${PX4_SIM_MODEL:=x500_lidar_down}

. ${R}etc/init.d-posix/airframes/4001_gz_x500

param set-default EKF2_RNG_POS_Z -0.177
param set-default EKF2_MIN_RNG 0
