#!/bin/sh
#
# @name BlueROV2 (Heavy Configuration)
#
# @type Vectored 6 DOF UUV
# @class Underwater Robot
#
# @output Motor1 motor 1 CCW, bow starboard horizontal, , propeller CCW
# @output Motor2 motor 2 CCW, bow port horizontal, propeller CCW
# @output Motor3 motor 3 CCW, stern starboard horizontal, propeller CW
# @output Motor4 motor 4 CCW, stern port horizontal, propeller CW
# @output Motor5 motor 5 CCW, bow starboard vertical, propeller CCW
# @output Motor6 motor 6 CCW, bow port vertical, propeller CW
# @output Motor7 motor 7 CCW, stern starboard vertical, propeller CW
# @output Motor8 motor 8 CCW, stern port vertical, propeller CCW
#
# @maintainer Thies Lennart Alff <thies.lennart.alff@tuhh.de>
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.uuv_defaults


PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=ocean}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=uuv_bluerov2_heavy}

param set-default SIM_GZ_EN 1

//param set-default MAV_1_CONFIG 102

//param set-default BAT1_A_PER_V 37.8798
param set-default BAT1_CAPACITY 18000
//param set-default BAT1_V_DIV 11
param set-default BAT1_N_CELLS 4
//param set-default BAT_V_OFFS_CURR 0.33

param set-default CA_AIRFRAME 7

param set-default CA_ROTOR_COUNT 8
param set-default CA_R_REV 255
param set-default CA_ROTOR0_AX 1
param set-default CA_ROTOR0_AY -1
param set-default CA_ROTOR0_AZ 0
param set-default CA_ROTOR0_KM 0
param set-default CA_ROTOR0_PX 0.5
param set-default CA_ROTOR0_PY 0.3
param set-default CA_ROTOR0_PZ 0.2
param set-default CA_ROTOR1_AX 1
param set-default CA_ROTOR1_AY 1
param set-default CA_ROTOR1_AZ 0
param set-default CA_ROTOR1_KM 0
param set-default CA_ROTOR1_PX 0.5
param set-default CA_ROTOR1_PY -0.3
param set-default CA_ROTOR1_PZ 0.2
param set-default CA_ROTOR2_AX 1
param set-default CA_ROTOR2_AY 1
param set-default CA_ROTOR2_AZ 0
param set-default CA_ROTOR2_KM 0
param set-default CA_ROTOR2_PX -0.5
param set-default CA_ROTOR2_PY 0.3
param set-default CA_ROTOR2_PZ 0.2
param set-default CA_ROTOR3_AX 1
param set-default CA_ROTOR3_AY -1
param set-default CA_ROTOR3_AZ 0
param set-default CA_ROTOR3_KM 0
param set-default CA_ROTOR3_PX -0.5
param set-default CA_ROTOR3_PY -0.3
param set-default CA_ROTOR3_PZ 0.2
param set-default CA_ROTOR4_AZ -1
param set-default CA_ROTOR4_KM 0
param set-default CA_ROTOR4_PX 0.5
param set-default CA_ROTOR4_PY 0.5
param set-default CA_ROTOR5_AZ 1
param set-default CA_ROTOR5_KM 0
param set-default CA_ROTOR5_PX 0.5
param set-default CA_ROTOR5_PY -0.5
param set-default CA_ROTOR6_AZ 1
param set-default CA_ROTOR6_KM 0
param set-default CA_ROTOR6_PX -0.5
param set-default CA_ROTOR6_PY 0.5
param set-default CA_ROTOR7_AZ -1
param set-default CA_ROTOR7_KM 0
param set-default CA_ROTOR7_PX -0.5
param set-default CA_ROTOR7_PY -0.5

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
param set-default PWM_MAIN_FUNC5 105
param set-default PWM_MAIN_FUNC6 106
param set-default PWM_MAIN_FUNC7 107
param set-default PWM_MAIN_FUNC8 108





param set-default SIM_GZ_TH_FUNC1 101
param set-default SIM_GZ_TH_FUNC2 102
param set-default SIM_GZ_TH_FUNC3 103
param set-default SIM_GZ_TH_FUNC4 104
param set-default SIM_GZ_TH_FUNC5 105
param set-default SIM_GZ_TH_FUNC6 106
param set-default SIM_GZ_TH_FUNC7 107
param set-default SIM_GZ_TH_FUNC8 108

param set-default SIM_GZ_TH_MIN1 0
param set-default SIM_GZ_TH_MIN2 0
param set-default SIM_GZ_TH_MIN3 0
param set-default SIM_GZ_TH_MIN4 0
param set-default SIM_GZ_TH_MIN5 0
param set-default SIM_GZ_TH_MIN6 0
param set-default SIM_GZ_TH_MIN7 0
param set-default SIM_GZ_TH_MIN8 0


param set-default SIM_GZ_TH_DIS1 500
param set-default SIM_GZ_TH_DIS2 500
param set-default SIM_GZ_TH_DIS3 500
param set-default SIM_GZ_TH_DIS4 500
param set-default SIM_GZ_TH_DIS5 500
param set-default SIM_GZ_TH_DIS6 500
param set-default SIM_GZ_TH_DIS7 500
param set-default SIM_GZ_TH_DIS8 500


param set-default SIM_GZ_TH_MAX1 1000
param set-default SIM_GZ_TH_MAX2 1000
param set-default SIM_GZ_TH_MAX3 1000
param set-default SIM_GZ_TH_MAX4 1000
param set-default SIM_GZ_TH_MAX5 1000
param set-default SIM_GZ_TH_MAX6 1000
param set-default SIM_GZ_TH_MAX7 1000
param set-default SIM_GZ_TH_MAX8 1000

param set-default SIM_GZ_TH_REV 255
