#!/bin/sh
#
# @name SSRC SCOUT MINI UGV
#
# @url https://global.agilex.ai/products/scout-mini
#
# @type Rover
# @class Rover
#

. ${R}etc/init.d/rc.rover_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=scout_mini}

param set-default SIM_GZ_EN 1
param set-default SIM_GZ_RUN_GZSIM 0
param set-default SIM_GZ_SHOME 1

param set-default CA_AIRFRAME 6

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 1
param set-default SENS_EN_MAGSIM 1

param set IMU_GYRO_CUTOFF 60
param set IMU_DGYRO_CUTOFF 30

param set-default SYS_HAS_BARO 0

param set-default BAT1_N_CELLS 4

param set-default MIS_TAKEOFF_ALT 0.01

param set-default NAV_ACC_RAD 0.5     # reached when within 0.5m of waypoint

# Enable Airspeed check circuit breaker because Rovers will have no airspeed sensor
param set-default CBRK_AIRSPD_CHK 162128

# EKF2
param set-default EKF2_GBIAS_INIT 0.01
param set-default EKF2_ANGERR_INIT 0.01
param set-default EKF2_MAG_TYPE 1
param set-default EKF2_REQ_SACC 1.0
param set-default EKF2_REQ_VDRIFT 0.4
param set-default EKF2_REQ_HDRIFT 0.2


#################################
# Rover Position Control Module #
#################################

param set-default GND_SP_CTRL_MODE 1
param set-default GND_L1_DIST 5
param set-default GND_L1_PERIOD 3
param set-default GND_THR_CRUISE 1
param set-default GND_THR_MAX 1

# Because this is differential drive, it can make a turn with radius 0.
# This corresponds to a turn angle of pi radians.
# If a special case is made for differential-drive, this will need to change.
param set-default GND_MAX_ANG 3.142
param set-default GND_WHEEL_BASE 0.45

# TODO: Set to -1.0, to allow reversing. This will require many changes in the codebase
# to support negative throttle.
param set-default GND_THR_MIN 0
param set-default GND_SPEED_P 0.4
param set-default GND_SPEED_I 1
param set-default GND_SPEED_D 0.001
param set-default GND_SPEED_MAX 3.0
param set-default GND_SPEED_TRIM 3.0
param set-default GND_SPEED_THR_SC 1.0
param set-default GND_VEL_CTRL 1
param set-default GND_ANG_VEL_CTRL 1
param set-default GND_ACC_LIMIT 10
param set-default GND_DEC_LIMIT 50
