#!/bin/sh
#
# PX4 SITL Configuration Script for Cessna 172 Skyhawk in X-Plane
#
# This script configures PX4 SITL for a Cessna 172 Skyhawk, a standard fixed-wing plane.
# It's tailored for integration with X-Plane, a custom simulator, facilitating real-world scale simulation.
#
# Usage: Run with 'make px4_sitl xplane_cessna172'.
#
# @name: Cessna 172 Skyhawk
# Compatible Simulator: X-Plane
# @type Standard Plane
# @maintainer alireza787b <p30planets@gmail.com>
# Date: Nov 2023
# @url https://github.com/alireza787b/px4xplane/
#
# ---- Start of Configuration ----

# Load default configuration for fixed-wing aircraft
. ${R}etc/init.d/rc.fw_defaults

# ---- Airframe Configuration Parameters ----
# These parameters define the physical configuration of the Cessna 172 Skyhawk airframe
param set-default CA_AIRFRAME 1
param set-default CA_ROTOR_COUNT 1

# ---- Control Surface Configuration ----
# Configuration of control surfaces for flight control and maneuvering
param set-default CA_SV_CS_COUNT 4
param set-default CA_SV_CS0_TYPE 1
param set-default CA_SV_CS0_TRQ_R -0.5
param set-default CA_SV_CS1_TYPE 2
param set-default CA_SV_CS1_TRQ_R 0.5
param set-default CA_SV_CS2_TYPE 3
param set-default CA_SV_CS2_TRQ_P 1.0
param set-default CA_SV_CS3_TYPE 4
param set-default CA_SV_CS3_TRQ_Y 1.0

# ---- Simulator Sensor Configuration ----
# Enabling simulated sensors for integration with X-Plane
param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 1
param set-default SENS_EN_MAGSIM 1
param set-default SENS_EN_ARSPDSIM 1

# ---- PWM Output Configuration ----
# Assignments for PWM main outputs
param set-default PWM_MAIN_FUNC1 201
param set-default PWM_MAIN_FUNC2 202
param set-default PWM_MAIN_FUNC3 203
param set-default PWM_MAIN_FUNC4 101
param set-default PWM_MAIN_FUNC5 204
param set-default PWM_MAIN_FUNC6 204

# ---- Fixed-wing Specific Parameters ----
# Parameters specific to fixed-wing flight dynamics
param set-default FW_AIRSPD_MAX 75.0000
param set-default FW_AIRSPD_MIN 30.0000
param set-default FW_AIRSPD_STALL 25.0000
param set-default FW_AIRSPD_TRIM 45.0000
param set-default ASPD_FALLBACK_GW 1
param set-default FW_RR_FF 4.8000
param set-default FW_R_LIM 30.0000
param set-default LNDFW_VEL_XY_MAX 15.0000
param set-default FW_LND_FLALT  5.0000
param set-default RTL_LOITER_RAD 1000.0000
param set-default FW_LND_FL_PMAX 35.0000

# ---- PWM Reversals ----
# Configuration for reversing the PWM signal
param set-default PWM_MAIN_REV 7

# ---- Logging Configuration ----
# Settings related to flight data logging
param set-default SDLOG_MODE 0

# ---- Circuit Breakers ----
# Disabling various system checks (use with caution)
param set-default CBRK_USB_CHK 197848      # Disable USB check
param set-default CBRK_SUPPLY_CHK 894281   # Disable real battery check
param set-default CBRK_IO_SAFETY 22027     # Disable safety switch check
param set-default CBRK_AIRSPD_CHK 1612128  # Disable airspeed sensor check

# ---- End of Configuration ----
#new

param set-default FW_TKO_AIRSPD 32.0000
param set-default FW_TKO_PITCH_MIN 20.0000
param set-default FW_T_CLMB_MAX 6.0000
param set-default FW_WING_HEIGHT 2.5000
param set-default FW_WING_SPAN 11.0000
param set-default MIS_DIST_1WP 5000.0000
param set-default MIS_TAKEOFF_ALT 100.0000
param set-default MIS_TKO_LAND_REQ 0
param set-default NAV_LOITER_RAD 1000.0000
param set-default RTL_MIN_DIST 50.0000
param set-default WEIGHT_BASE 1000.0000
param set-default WEIGHT_GROSS 1000.0000
param set-default CA_ROTOR0_PX 1.2000


param set-default CA_R0_SLEW 2.0000
param set-default EKF2_ABL_ACCLIM 35.0000
param set-default EKF2_MAG_DELAY 1.0000
param set-default FW_LND_ABORT 0
param set-default FW_PN_R_SLEW_MAX 50.0000
param set-default FW_PR_FF 3.4000
param set-default FW_PR_I 0.0450
param set-default FW_PR_P 0.3650
param set-default FW_P_LIM_MAX 20.0000
param set-default FW_P_LIM_MIN -15.0000
param set-default MPC_JERK_AUTO 1.0000
param set-default MPC_JERK_MAX 3.0000
param set-default FW_P_TC 0.4500
param set-default FW_RR_P 0.4700
param set-default FW_R_RMAX 10.0000
param set-default FW_R_TC 0.6000
param set-default FW_T_ALT_TC 10.0000
param set-default FW_T_I_GAIN_THR 0.0200
param set-default FW_T_RLL2THR 5.0000
param set-default FW_T_STE_R_TC 2.5000
param set-default FW_T_THR_DAMP 0.0000
param set-default LNDFW_AIRSPD_MAX 30.0000
param set-default MIS_YAW_ERR 15.0000
param set-default NAV_ACC_RAD 300.0000
param set-default NAV_FW_ALT_RAD 50.0000
param set-default NAV_MIN_LTR_ALT -1.0000

param set-default EKF2_MAG_TYPE 0
param set-default FW_LND_AIRSPD 36.0000
param set-default FW_PR_D 0.3550
param set-default FW_RR_D 0.0850
param set-default FW_RR_I 0.1300
param set-default SYS_HAS_MAG 1
