#!/bin/sh
#
# @name TB2 Fixed Wing Aircraft
# @type Plane A-Tail
# @class Plane
#
# @output Motor1 throttle
# @output Servo1 aileron right
# @output Servo2 aileron left
# @output Servo3 v-tail right
# @output Servo4 v-tail left
# @output Servo5 wheel
# @output Servo6 flaps right
# @output Servo7 flaps left
#
# @maintainer Alireza Ghaderi <p30planets@gmail.com>
#

. ${R}etc/init.d/rc.fw_defaults

# --- Aircraft Configuration ---
param set-default CA_AIRFRAME 1
param set-default CA_ROTOR_COUNT 1
param set-default CA_SV_CS_COUNT 7

# --- Control Surface Configuration ---
param set-default CA_SV_CS0_TYPE 1     # Left aileron
param set-default CA_SV_CS0_TRQ_R -0.5
param set-default CA_SV_CS1_TYPE 2     # Right aileron
param set-default CA_SV_CS1_TRQ_R 0.5
param set-default CA_SV_CS2_TYPE 13    # Left V-tail
param set-default CA_SV_CS2_TRQ_P 0.5
param set-default CA_SV_CS2_TRQ_Y -0.5
param set-default CA_SV_CS3_TYPE 14    # Right V-tail
param set-default CA_SV_CS3_TRQ_P 0.5
param set-default CA_SV_CS3_TRQ_Y 0.5
param set-default CA_SV_CS4_TYPE 16    # Wheel
param set-default CA_SV_CS4_TRQ_Y 0
param set-default CA_SV_CS5_TYPE 9     # Left flap
param set-default CA_SV_CS6_TYPE 10    # Right flap

# --- PWM Configuration and Reversals ---
param set-default PWM_MAIN_FUNC1 201
param set-default PWM_MAIN_FUNC2 202
param set-default PWM_MAIN_FUNC3 203
param set-default PWM_MAIN_FUNC4 204
param set-default PWM_MAIN_FUNC5 101
param set-default PWM_MAIN_FUNC6 205
param set-default PWM_MAIN_FUNC7 206
param set-default PWM_MAIN_FUNC8 207
param set-default PWM_MAIN_REV 15      # PWM signal reversal configuration

# --- Flight Performance Parameters ---
param set-default FW_MAN_P_MAX 55
param set-default FW_MAN_R_MAX 55
param set-default FW_R_LIM 30
param set-default FW_WR_FF 0.2
param set-default FW_WR_I 0.2
param set-default FW_WR_IMAX 0.8
param set-default FW_WR_P 1
param set-default FW_W_RMAX 0

# --- Sensor Simulation ---
param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 1
param set-default SENS_EN_MAGSIM 1
param set-default SENS_EN_ARSPDSIM 1

# --- Airspeed and Flight Mode Settings ---
param set-default FW_AIRSPD_MAX 80
param set-default FW_AIRSPD_MIN 30
param set-default FW_AIRSPD_STALL 25
param set-default FW_AIRSPD_TRIM 45
param set-default ASPD_FALLBACK_GW 1

# --- Landing and RTL Parameters ---
param set-default FW_LND_FLALT 5
param set-default RTL_LOITER_RAD 1000
param set-default FW_LND_FL_PMAX 35
param set-default FW_TKO_AIRSPD 32
param set-default FW_TKO_PITCH_MIN 20
param set-default FW_T_CLMB_MAX 6
param set-default FW_WING_HEIGHT 2.5
param set-default FW_WING_SPAN 11
param set-default MIS_DIST_1WP 5000
param set-default MIS_TAKEOFF_ALT 100
param set-default MIS_TKO_LAND_REQ 0
param set-default RTL_MIN_DIST 50

# --- Safety and Breakers ---
param set-default CBRK_USB_CHK 197848       # Disable USB check
param set-default CBRK_SUPPLY_CHK 894281    # Disable real battery check
param set-default CBRK_IO_SAFETY 22027      # Disable safety switch check

# --- Miscellaneous Settings ---
param set-default SDLOG_MODE 0
param set-default SYS_HAS_MAG 1
param set-default NAV_LOITER_RAD 1000
param set-default EKF2_MAG_TYPE 0

# --- End of Configuration ---
