#!/bin/sh
#
# @name Gazebo x500
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=PLACE_mockup}

param set-default SIM_GZ_EN 1

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 0
param set-default SENS_EN_MAGSIM 1

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 6

param set-default CA_ROTOR0_PX 0
param set-default CA_ROTOR0_PY -0.8
param set-default CA_ROTOR0_KM  -0.05

param set-default CA_ROTOR1_PX 0.692
param set-default CA_ROTOR1_PY -0.4
param set-default CA_ROTOR1_KM  0.05

param set-default CA_ROTOR2_PX 0.692
param set-default CA_ROTOR2_PY 0.4
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX 0
param set-default CA_ROTOR3_PY 0.8
param set-default CA_ROTOR3_KM 0.05

param set-default CA_ROTOR4_PX -0.692
param set-default CA_ROTOR4_PY 0.4
param set-default CA_ROTOR4_KM -0.05

param set-default CA_ROTOR5_PX -0.692
param set-default CA_ROTOR5_PY -0.4
param set-default CA_ROTOR5_KM 0.05

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_FUNC5 105
param set-default SIM_GZ_EC_FUNC6 106


param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150
param set-default SIM_GZ_EC_MIN5 150
param set-default SIM_GZ_EC_MIN6 150

param set-default SIM_GZ_EC_MAX1 3500
param set-default SIM_GZ_EC_MAX2 3500
param set-default SIM_GZ_EC_MAX3 3500
param set-default SIM_GZ_EC_MAX4 3500
param set-default SIM_GZ_EC_MAX5 3500
param set-default SIM_GZ_EC_MAX6 3500

param set-default MPC_THR_HOVER 0.60
