#!/bin/sh
#
# @name Typhoon H480 SITL
#
# @type Hexarotor x
#

. ${R}etc/init.d/rc.mc_defaults

if [ $AUTOCNF = yes ]
then
	param set MC_PITCHRATE_P 0.0800
	param set MC_PITCHRATE_I 0.0400
	param set MC_PITCHRATE_D 0.0010
	param set MC_PITCH_P 9.0
	param set MC_ROLLRATE_P 0.0800
	param set MC_ROLLRATE_I 0.0400
	param set MC_ROLLRATE_D 0.0010
	param set MC_ROLL_P 9.0
	param set MPC_XY_VEL_I_ACC 4
	param set MPC_XY_VEL_P_ACC 3

	param set RTL_DESCEND_ALT 10

	param set TRIG_INTERFACE 3
	param set TRIG_MODE 4
	param set MNT_MODE_IN 4
	param set MNT_MODE_OUT 2
	param set MAV_PROTO_VER 2
fi

set MAV_TYPE 13

set MIXER hexa_x
