#!/bin/sh
#
# @name Gazebo OmniQuad
#
# @type Quadrotor
#
# @maintainer Andrea Berra andrea.berra@outlook.com
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=OmniQuad}

param set-default SIM_GZ_EN 1

param set-default CA_AIRFRAME 16
param set-default MPC_ACT_MODE 1
set MAV_TYPE 2

param set-default CA_ROTOR_COUNT 4
param set-default CA_SV_TL_COUNT 4

param set-default CA_ROTOR0_PX 0.166170094
param set-default CA_ROTOR0_PY 0.166170094
param set-default CA_ROTOR0_KM 0.05

param set-default CA_ROTOR1_PX -0.166170094
param set-default CA_ROTOR1_PY -0.166170094
param set-default CA_ROTOR1_KM 0.05

param set-default CA_ROTOR2_PX 0.166170094
param set-default CA_ROTOR2_PY -0.166170094
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX -0.166170094
param set-default CA_ROTOR3_PY 0.166170094
param set-default CA_ROTOR3_KM -0.05

param set-default CA_ROTOR0_TILT 1
param set-default CA_ROTOR1_TILT 2
param set-default CA_ROTOR2_TILT 3
param set-default CA_ROTOR3_TILT 4

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 0
param set-default SIM_GZ_EC_MIN2 0
param set-default SIM_GZ_EC_MIN3 0
param set-default SIM_GZ_EC_MIN4 0

param set-default SIM_GZ_EC_MAX1 1100
param set-default SIM_GZ_EC_MAX2 1100
param set-default SIM_GZ_EC_MAX3 1100
param set-default SIM_GZ_EC_MAX4 1100

param set-default SIM_GZ_SV_MIN1 0
param set-default SIM_GZ_SV_MIN2 0
param set-default SIM_GZ_SV_MIN3 0
param set-default SIM_GZ_SV_MIN4 0

param set-default SIM_GZ_SV_MAX1 1000
param set-default SIM_GZ_SV_MAX2 1000
param set-default SIM_GZ_SV_MAX3 1000
param set-default SIM_GZ_SV_MAX4 1000

param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_FUNC2 202
param set-default SIM_GZ_SV_FUNC3 203
param set-default SIM_GZ_SV_FUNC4 204

param set-default CA_SV_TL0_MAXA 45
param set-default CA_SV_TL0_MINA -45
param set-default CA_SV_TL1_MAXA 45
param set-default CA_SV_TL1_MINA -45
param set-default CA_SV_TL2_MAXA 45
param set-default CA_SV_TL2_MINA -45
param set-default CA_SV_TL3_MAXA 45
param set-default CA_SV_TL3_MINA -45

param set-default MC_ROLL_P 4.22
param set-default MC_PITCH_P 4.01
param set-default MC_YAW_P 4.84

param set-default MC_ROLLRATE_P 0.226
param set-default MC_ROLLRATE_I 0.299
param set-default MC_ROLLRATE_D 0.0064

param set-default MC_PITCHRATE_P 0.238
param set-default MC_PITCHRATE_I 0.331
param set-default MC_PITCHRATE_D 0.0084

param set-default MC_YAWRATE_P 0.20
param set-default MC_YAWRATE_I 0.19
param set-default MC_YAWRATE_D 0.01
