module_name: hardfault_stream
parameters:
- group: System
  definitions:
    SYS_HF_MAV:
      description:
        short: Enable FMU SD card hardfault streaming
        long: Streams SD card hardfaults over MAVLink; useful when FMU resets in-flight and the SD card may not survive a crash.
      type: boolean
      default: 1
