module_name: hardfault_stream
parameters:
- group: System
  definitions:
    SYS_HF_MAV:
      description:
        short: Enable FMU SD card hardfault streaming
        long: |-
          When this is enabled all the hardfaults on the SD card are streamed
          over MAVLink. This is useful for cases where the FMU does reset in-flight due
          to a hardfault and the SD card may not survive a crash.
      type: boolean
      default: 1
