module_name: mag_bias_estimator
parameters:
- group: Magnetometer Bias Estimator
  definitions:
    MBE_ENABLE:
      description:
        short: Enable online mag bias calibration
        long: Continuous magnetometer calibration before takeoff using gyro data.
      type: boolean
      default: 1
      reboot_required: true
    MBE_LEARN_GAIN:
      description:
        short: Mag bias estimator learning gain
        long: Increase for more responsiveness; decrease for more noise robustness.
      type: float
      default: 18.0
      min: 0.1
      max: 100
      increment: 0.1
      decimal: 1
