float64 tar_lat			# target position 
float64 tar_lon			# target position 
float64 tar_alt			# target position
float32 tar_vy			# target vel in y
float32 tar_vx			# target vel in x
float32 tar_vz			# target vel in z
float32 vx			# North velocity in NED earth-fixed frame, (metres/sec)
float32 vy			# East velocity in NED earth-fixed frame, (metres/sec)
float32 vz			# Down velocity in NED earth-fixed frame, (metres/sec)
float64 lat			# Latitude, (degrees)
float64 lon			# Longitude, (degrees)
float32 alt			# Altitude AMSL, (meters)
