
uint64 timestamp		   		# time since system start (microseconds)

float32[3] acc_measured	  		 	# actual acceleration in world frame

float32[3] acc_expected		   		# expected acceleration in world frame

float32[3] drag_acc	 			# drag acceleration

float32[3] drag_acc_filtered 			# drag acceleration filtered

float32[3] drag_acc_filtered_body		# drag acceleration filtered in body frame

float32[3] drag_acceleration_moment_body	# drag acceleration moment in body frame

