uint64 timestamp		# Timestamp in microseconds since boot
float32[6] vel_pos_innov  # velocity and position innovations
float32[3] mag_innov 	# earth magnetic field innovations
float32 heading_innov 	# heading innovation
float32[6] vel_pos_innov_var 	# velocity and position innovation variances
float32[3] mag_innov_var	# earth magnetic field innovation variance
float32 heading_innov_var 	# heading innovation variance
