uint8 accel_id	# Sensor ID of currently used accelerometer sensor
uint8 gyro_id	# Sensor ID of currently used gyroscope sensor
uint8 mag_id	# Sensor ID of currently used magnetometer sensor
float32 rate_vibration	# Value between 0 and 1 indicating vibration. A value of 0 means no vibration, a value of 1 indicates unbearable vibration levels.
float32 accel_vibration	# Value between 0 and 1 indicating vibration. A value of 0 means no vibration, a value of 1 indicates unbearable vibration levels.
float32 mag_vibration	# Value between 0 and 1 indicating vibration. A value of 0 means no vibration, a value of 1 indicates unbearable vibration levels.
