# Relative position of precision land beacon in navigation frame

float32 x				# X/forward relative position of beacon, (metres)
float32 y				# Y/right relative position of beacon, (metres)
float32 x_unfilt		# DEBUG X/forward relative position of beacon, (metres)
float32 y_unfilt		# DEBUG Y/right relative position of beacon, (metres)
float32 vx				# X/forward relative velocity  of beacon, (metres/second)
float32 vy				# Y/right relative velocity of beacon, (metres/second)
float32 covx			# X/forward variance
float32 covy			# Y/right variance