
uint64 timestamp			# time since system start(microseconds)
uint8 rssi				# [dB] received signal strength indicator
uint8 snr				# [dB] signal to noise ratio
uint8 mcs_index				# multipoint coding scheme index
uint8 number_spatial_streams		# number of spatial streams
uint8 queue_size			# queue size, number of packets in tx queue
uint8 air_time				# percentage of the time the radio is transmitting
