bool inertial_valid			# Validity

float32 inertial_bvx		# Estimated Body vx
float32 inertial_bvy		# Estimated Body vy
float32 inertial_bvz		# Estimated Body vz

float32 inertial_ivx		# Estimated inertial vx
float32 inertial_ivy		# Estimated inertial vy
float32 inertial_ivz		# Estimated inertial vz

float32 wind_ivx			# Wind vx
float32 wind_ivy			# Wind vy
float32 wind_ivz			# Wind vz

float32 u			# Latent scaling
