// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <matrix/math.hpp>

namespace sym
{

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: getTransitionMatrix
 *
 * Args:
 *     dt: Scalar
 *
 * Outputs:
 *     transition_matrix: Matrix55
 */
template <typename Scalar>
void Gettransitionmatrix(const Scalar dt,
			 matrix::Matrix<Scalar, 5, 5> *const transition_matrix = nullptr)
{
	// Total ops: 3

	// Input arrays

	// Intermediate terms (0)

	// Output terms (1)
	if (transition_matrix != nullptr) {
		matrix::Matrix<Scalar, 5, 5> &_transition_matrix = (*transition_matrix);

		_transition_matrix.setZero();

		_transition_matrix(0, 0) = 1;
		_transition_matrix(0, 1) = -dt;
		_transition_matrix(1, 1) = 1;
		_transition_matrix(2, 2) = 1;
		_transition_matrix(0, 3) = Scalar(0.5) * std::pow(dt, Scalar(2));
		_transition_matrix(3, 3) = 1;
		_transition_matrix(4, 3) = dt;
		_transition_matrix(0, 4) = dt;
		_transition_matrix(4, 4) = 1;
	}
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
