module_name: vl53l0x
parameters:
- group: Sensors
  definitions:
    SENS_EN_VL53L0X:
      description:
        short: VL53L0X Distance Sensor
      type: boolean
      default: 0
      reboot_required: true
