#include <systemlib/param/param.h>
PARAM_DEFINE_FLOAT(FW_STAB_P_LP_FCUT,10.0f);
PARAM_DEFINE_FLOAT(FW_STAB_Q_LP_FCUT,10.0f);
PARAM_DEFINE_FLOAT(FW_STAB_R_LP_FCUT,10.0f);
PARAM_DEFINE_FLOAT(FW_STAB_R_HP_FCUT,1.0f);
PARAM_DEFINE_FLOAT(FW_STAB_P2AIL_P,1.0f);
PARAM_DEFINE_FLOAT(FW_STAB_Q2ELV_P,1.0f);
PARAM_DEFINE_FLOAT(FW_STAB_R2RDR_P,1.0f);

