#include <systemlib/param/param.h>

PARAM_DEFINE_FLOAT(FW_HEAD_PSI_2PHI_P, 1.0f);
PARAM_DEFINE_FLOAT(FW_HEAD_P_2PHI_P, 1.0f);
PARAM_DEFINE_FLOAT(FW_HEAD_PHI_2AIL_P, 1.0f);
PARAM_DEFINE_FLOAT(FW_HEAD_PHI_LIM_MIN, -1.0f);
PARAM_DEFINE_FLOAT(FW_HEAD_PHI_LIM_MAX, 1.0f);

PARAM_DEFINE_FLOAT(FW_STAB_P_LP_FCUT,10.0f);
PARAM_DEFINE_FLOAT(FW_STAB_Q_LP_FCUT,10.0f);
PARAM_DEFINE_FLOAT(FW_STAB_R_LP_FCUT,10.0f);
PARAM_DEFINE_FLOAT(FW_STAB_R_HP_FCUT,1.0f);
PARAM_DEFINE_FLOAT(FW_STAB_P_2AIL_P,1.0f);
PARAM_DEFINE_FLOAT(FW_STAB_Q_2ELV_P,1.0f);
PARAM_DEFINE_FLOAT(FW_STAB_R_2RDR_P,1.0f);

PARAM_DEFINE_FLOAT(FW_ALTB_H_2THR_P,1.0f);
PARAM_DEFINE_FLOAT(FW_ALTB_H_2THR_I,0.0f);
PARAM_DEFINE_FLOAT(FW_ALTB_H_2THR_I_MIN,0.0f);
PARAM_DEFINE_FLOAT(FW_ALTB_H_2THR_I_MAX,0.0f);
PARAM_DEFINE_FLOAT(FW_ALTB_H_2THR_D,0.0f);
PARAM_DEFINE_FLOAT(FW_ALTB_H_2THR_D_FCUT,0.0f);

PARAM_DEFINE_FLOAT(FW_VELB_V_2THETA_P,1.0f);
PARAM_DEFINE_FLOAT(FW_VELB_V_2THETA_I,0.0f);
PARAM_DEFINE_FLOAT(FW_VELB_V_2THETA_I_MIN,0.0f);
PARAM_DEFINE_FLOAT(FW_VELB_V_2THETA_I_MAX,0.0f);
PARAM_DEFINE_FLOAT(FW_VELB_V_2THETA_D,0.0f);
PARAM_DEFINE_FLOAT(FW_VELB_V_2THETA_D_FCUT,0.0f);
PARAM_DEFINE_FLOAT(FW_VELB_THETA_2Q_P,1.0f);
PARAM_DEFINE_FLOAT(FW_VELB_THETA_2Q_I,0.0f);
PARAM_DEFINE_FLOAT(FW_VELB_THETA_2Q_I_MIN,0.0f);
PARAM_DEFINE_FLOAT(FW_VELB_THETA_2Q_I_MAX,0.0f);
PARAM_DEFINE_FLOAT(FW_VELB_THETA_2Q_D,0.0f);
PARAM_DEFINE_FLOAT(FW_VELB_THETA_2Q_D_FCUT,0.0f);
