function H_MAGD = calcH_MAGD(magE,magN)
%CALCH_MAGD
%    H_MAGD = CALCH_MAGD(MAGE,MAGN)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    29-May-2017 00:16:13

t2 = magE.^2;
t3 = magN.^2;
t4 = t2+t3;
t5 = 1.0./t4;
H_MAGD = [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-magE.*t5,magN.*t5,0.0,0.0,0.0,0.0,0.0,0.0];
