#!/bin/sh
# PX4 commands need the 'px4-' prefix in bash.
# (px4-alias.sh is expected to be in the PATH)
. px4-alias.sh

param load
param set CBRK_SUPPLY_CHK 894281

dataman start

battery_simulator start
simulator start
tone_alarm start
pwm_out_sim start

ver all

mavlink start -x -u 14556 -r 2000000 -p
mavlink boot_complete

mavlink_tests

shutdown
