#!/usr/bin/bash
# PX4 commands need the 'px4-' prefix in bash.
# (px4-alias.sh is expected to be in the PATH)
source px4-alias.sh

uorb start

param load
param set SYS_RESTART_TYPE 0

dataman start

tone_alarm start

ver all

sleep 1

tests all

shutdown
