#include <systemlib/param/param.h>

PARAM_DEFINE_FLOAT(AE2_SD_GYRO, 1e-6f);
PARAM_DEFINE_FLOAT(AE2_SD_DBIAS, 1e-6f);
PARAM_DEFINE_FLOAT(AE2_SD_MAG, 1.0f);
PARAM_DEFINE_FLOAT(AE2_SD_ACCEL, 1.0f);
PARAM_DEFINE_FLOAT(AE2_ALPHA_LP, 250.0f);
PARAM_DEFINE_FLOAT(AE2_ACCEL_LP, 250.0f);
