module_name: gz_bridge
parameters:
- group: Simulation
  definitions:
    SIM_GZ_EN_LIDAR:
      description:
        short: Enable laser/lidar sensors in Gazebo bridge
      type: enum
      values:
        0: Disabled
        1: Enabled
      default: 1
      reboot_required: true
    SIM_GZ_EN_FLOW:
      description:
        short: Enable optical flow sensor in Gazebo bridge
      type: enum
      values:
        0: Disabled
        1: Enabled
      default: 1
      reboot_required: true
    SIM_GZ_EN_ASPD:
      description:
        short: Enable airspeed sensor in Gazebo bridge
      type: enum
      values:
        0: Disabled
        1: Enabled
      default: 1
      reboot_required: true
    SIM_GZ_EN_BARO:
      description:
        short: Enable barometer/air pressure sensor in Gazebo bridge
      type: enum
      values:
        0: Disabled
        1: Enabled
      default: 1
      reboot_required: true
    SIM_GZ_EN_ODOM:
      description:
        short: Enable odometry in Gazebo bridge
      type: enum
      values:
        0: Disabled
        1: Enabled
      default: 1
      reboot_required: true
    SIM_GZ_EN_GPS:
      description:
        short: Enable GPS/NavSat sensor(s) in Gazebo bridge
      type: enum
      values:
        0: Disabled
        1: Simulate 1 GPS sensor
        2: Simulate 2 GPS sensors
      default: 1
      reboot_required: true
    SIM_GZ_EN_IMU:
      description:
        short: Enable IMU sensor(s) in Gazebo bridge
      type: enum
      values:
        0: Disabled
        1: Simulate 1 IMU sensor
        2: Simulate 2 IMU sensors
        3: Simulate 3 IMU sensors
      default: 1
      reboot_required: true
    SIM_GZ_EN_MAG:
      description:
        short: Enable magnetometer sensor(s) in Gazebo bridge
      type: enum
      values:
        0: Disabled
        1: Simulate 1 magnometer sensor
        2: Simulate 2 magnometer sensors
      default: 1
      reboot_required: true
- group: UAVCAN
  definitions:
    SIM_GZ_EN:
      description:
        short: Simulator Gazebo bridge enable
      type: boolean
      default: 0
      reboot_required: true
