module_name: spl06
parameters:
- group: Sensors
  definitions:
    SENS_EN_SPL06:
      description:
        short: Goertek SPL06 Barometer (external I2C)
      type: boolean
      default: 0
      reboot_required: true
