module_name: Orbit
parameters:
- group: Flight Task Orbit
  definitions:
    MC_ORBIT_RAD_MAX:
      description:
        short: Maximum radius of orbit
      type: float
      default: 1000.0
      unit: m
      min: 1.0
      max: 10000.0
      increment: 0.5
      decimal: 1
    MC_ORBIT_YAW_MOD:
      description:
        short: Yaw behaviour during orbit flight
      type: enum
      values:
        0: Front to Circle Center
        1: Hold Initial Heading
        2: Uncontrolled
        3: Hold Front Tangent to Circle
        4: Manually (yaw stick) Controlled
      default: 0
