#!/usr/bin/env python3
"""Code generator: reads PX4's generated <Msg>.json (rosidl type_description
format) and writes <Msg>.py with a dataclass + fast deserialize() -- one
precompiled struct.Struct, no per-message JSON parsing, no idlc/cyclonedds.

Usage:
    python3 gen_msg.py <build_dir> SensorCombined EstimatorAidSource1d
    python3 gen_msg.py <build_dir> --all

<build_dir> is a PX4 build directory, e.g. build/px4_sitl_navput -- the
generated <Msg>.json files are expected at
<build_dir>/uORB/idl/px4_msgs/msg/<Msg>.json
"""
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT_DIR = HERE / "msgs"

# rosidl_runtime_c/type_description/field_type__struct.h
_SCALARS = {
    2: ("b", 1),   # INT8
    3: ("B", 1),   # UINT8
    4: ("h", 2),   # INT16
    5: ("H", 2),   # UINT16
    6: ("i", 4),   # INT32
    7: ("I", 4),   # UINT32
    8: ("q", 8),   # INT64
    9: ("Q", 8),   # UINT64
    10: ("f", 4),  # FLOAT
    11: ("d", 8),  # DOUBLE
    13: ("B", 1),  # CHAR
    14: ("H", 2),  # WCHAR
    15: ("?", 1),  # BOOLEAN
    16: ("B", 1),  # BYTE
}
_ARRAY_OFFSET = 48  # FIELD_TYPE_X_ARRAY == FIELD_TYPE_X + 48


def build_layout(msg_name, json_dir):
    with open(json_dir / f"{msg_name}.json") as f:
        desc = json.load(f)
    type_desc = desc["type_description_msg"]["type_description"]
    type_hash = desc["type_hashes"][0]["hash_string"]

    fmt_parts = ["<"]
    offset = 0
    slices = []  # (name, python_slice_expr)
    flat_index = 0

    for field in type_desc["fields"]:
        type_id = field["type"]["type_id"]
        capacity = field["type"]["capacity"]
        count = capacity if capacity else 1
        base_id = type_id - _ARRAY_OFFSET if type_id >= _ARRAY_OFFSET else type_id
        if base_id not in _SCALARS:
            raise NotImplementedError(
                f"{msg_name}.{field['name']}: unsupported type_id {type_id}"
            )
        fmt_char, size = _SCALARS[base_id]

        pad = (-offset) % size
        if pad:
            fmt_parts.append("x" * pad)
            offset += pad

        fmt_parts.append(fmt_char * count)
        offset += size * count

        if count == 1:
            slices.append((field["name"], f"v[{flat_index}]"))
            flat_index += 1
        else:
            slices.append((field["name"], f"v[{flat_index}:{flat_index + count}]"))
            flat_index += count

    return "".join(fmt_parts), slices, type_hash


def generate(msg_name, json_dir):
    fmt, slices, type_hash = build_layout(msg_name, json_dir)
    field_names = [name for name, _ in slices]

    lines = []
    lines.append(f'"""Generated by gen_msg.py from {msg_name}.json -- do not edit."""')
    lines.append("import struct")
    lines.append("from dataclasses import dataclass")
    lines.append("")
    lines.append(f'TYPE_HASH = "{type_hash}"')
    lines.append(f'_STRUCT = struct.Struct("{fmt}")')
    lines.append("")
    lines.append("@dataclass")
    lines.append(f"class {msg_name}:")
    for name in field_names:
        lines.append(f"    {name}: object")
    lines.append("")
    lines.append("    @classmethod")
    lines.append("    def deserialize(cls, payload):")
    lines.append("        v = _STRUCT.unpack_from(payload, 4)  # skip CDR encapsulation header")
    lines.append("        return cls(")
    for name, expr in slices:
        lines.append(f"            {name}={expr},")
    lines.append("        )")
    lines.append("")

    OUT_DIR.mkdir(exist_ok=True)
    out_path = OUT_DIR / f"{msg_name}.py"
    out_path.write_text("\n".join(lines))
    print(f"wrote {out_path}")


def main():
    if len(sys.argv) < 3:
        print(__doc__)
        sys.exit(1)

    json_dir = Path(sys.argv[1]) / "uORB" / "idl" / "px4_msgs" / "msg"

    if sys.argv[2] == "--all":
        names = [p.stem for p in json_dir.glob("*.json")]
    else:
        names = sys.argv[2:]

    for name in names:
        try:
            generate(name, json_dir)
        except NotImplementedError as e:
            print(f"skip {name}: {e}")


if __name__ == "__main__":
    main()
