#pragma once

#include "protocol.h"

#define OPT_TBOOT_MS            2000
#define OPT_NODE_STATUS_RATE_MS 800
#define OPT_NODE_INFO_RATE_MS   200
#define OPT_BL_NUMBER_TIMERS 6

#define OPT_WAIT_FOR_GETNODEINFO 0
#define OPT_WAIT_FOR_GETNODEINFO_JUMPER_GPIO        1
#define OPT_WAIT_FOR_GETNODEINFO_JUMPER_GPIO_INVERT 1

#define OPT_CPU_FREQ_HZ 72000000u

#define OPT_ENABLE_WD
#define OPT_MIN_APP_PROGRESS 0u
#define OPT_RESTART_TIMEOUT_MS 20000u

#define OPT_APPLICATION_IMAGE_OFFSET 8192u
#define OPT_APPLICATION_IMAGE_LENGTH 49152u

#define FLASH_BASE STM32_FLASH_BASE
#define FLASH_NUMBER_PAGES STM32_FLASH_NPAGES
#define FLASH_PAGE_SIZE STM32_FLASH_PAGESIZE
#define FLASH_SIZE (FLASH_NUMBER_PAGES*FLASH_PAGE_SIZE)

#define UAVCAN_SERVICE_RETRIES 3u
#define UAVCAN_SERVICE_TIMEOUT_MS 1000
#define UAVCAN_NODESTATUS_INTERVAL_MS 500

#define APPLICATION_LOAD_ADDRESS (FLASH_BASE + OPT_APPLICATION_IMAGE_OFFSET)
#define APPLICATION_SIZE (FLASH_SIZE-OPT_APPLICATION_IMAGE_OFFSET)
#define APPLICATION_LAST_32BIT_ADDRRESS ((uint32_t *)((APPLICATION_LOAD_ADDRESS+APPLICATION_SIZE)-sizeof(uint32_t)))
#define APPLICATION_LAST_64BIT_ADDRRESS ((uint64_t *)((APPLICATION_LOAD_ADDRESS+APPLICATION_SIZE)-sizeof(uint64_t)))

