name: 🐛 Bug report
description: Create a report to help us improve
title: "[Bug] "
labels: ["bug-report"]
body:
  - type: markdown
    attributes:
      value: |
        **Tips for a great bug report:**
        - Describe what went wrong and what you expected
        - Include a flight log link from [logs.px4.io](http://logs.px4.io/) if possible
        - Mention your PX4 version, flight controller, and vehicle type if relevant

  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear description of the bug and what you expected to happen.
      placeholder: |
        What happened and what did you expect instead?

        Steps to reproduce (if applicable):
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Flight Log / Additional Information
      description: |
        **Flight log** (highly recommended for flight-related issues):
        - Upload to [PX4 Flight Review](http://logs.px4.io/) and paste the link

        **Additional details** (if relevant):
        - PX4 version (output of `ver all` in MAVLink Shell)
        - Flight controller model
        - Vehicle type (multicopter, fixed-wing, VTOL, etc.)
        - Screenshots or media
      placeholder: |
        Flight log link:

        Version:

        Hardware:
    validations:
      required: false
