blank_issues_enabled: false
contact_links:
  - name: Support Question
    url: https://docs.px4.io/main/en/contribute/support.html#forums-and-chat
    about: For questions about using PX4 or related components, please use the discuss forum and discord server
