#include <systemlib/param/param.h>
PARAM_DEFINE_FLOAT(TEST_MIN,-1.0f);
PARAM_DEFINE_FLOAT(TEST_MAX,1.0f);
PARAM_DEFINE_FLOAT(TEST_HP,10.0f);
PARAM_DEFINE_FLOAT(TEST_LP,10.0f);

PARAM_DEFINE_FLOAT(TEST_P,0.2f);

PARAM_DEFINE_FLOAT(TEST_I,0.1f);
PARAM_DEFINE_FLOAT(TEST_I_MIN,-1.0f);
PARAM_DEFINE_FLOAT(TEST_I_MAX,1.0f);

PARAM_DEFINE_FLOAT(TEST_D,0.01f);
PARAM_DEFINE_FLOAT(TEST_D_LP,10.0f);
