#!/bin/sh
#
# @name Astro Blue F7010 Motors
#
# @type Quadrotor x
# @class Copter
#

echo "[AIRFRAME]-> Loading Astro Max Blue F7010 Motors Airframe"

. ${R}etc/init.d/rc.mc_defaults
. ${R}etc/init.d/airframes/astro_base
. ${R}etc/init.d/airframes/astro_max
. ${R}etc/init.d/airframes/astro_blue
