#!/bin/sh
#
# @name Generic AAVVT v-tail plane airframe with Quad VTOL.
#
# @type Standard VTOL
# @class VTOL
#
# @maintainer Sander Smeets <sander@droneslab.com>
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
# @board holybro_kakutef7 exclude
#

. ${R}etc/init.d/rc.vtol_defaults


param set-default MC_ROLL_P 7
param set-default MC_ROLLRATE_I 0.002
param set-default MC_PITCH_P 7
param set-default MC_PITCHRATE_P 0.12
param set-default MC_PITCHRATE_I 0.002
param set-default MC_YAWRATE_P 0.22
param set-default MC_YAWRATE_I 0.02
param set-default MC_YAWRATE_MAX 40

param set-default MPC_YAWRAUTO_MAX 40

param set-default PWM_AUX_DIS5 950

param set-default VT_F_TRANS_THR 0.75
param set-default VT_MOT_ID 1234
param set-default VT_FW_MOT_OFFID 1234
param set-default VT_IDLE_PWM_MC 1080
param set-default VT_TYPE 2

set MIXER quad_x
set MIXER_AUX vtol_AAVVT

set PWM_OUT 1234
