#!/bin/sh
#
# @name Caipiroshka Duo Tailsitter
#
# @type VTOL Duo Tailsitter
# @class VTOL
#
# @output MAIN1 motor right
# @output MAIN2 motor left
# @output MAIN5 elevon right
# @output MAIN6 elevon left
#
# @maintainer Roman Bapst <roman@px4.io>
#

sh /etc/init.d/rc.vtol_defaults

if [ $AUTOCNF = yes ]
then
	param set MC_ROLL_P 7.00
	param set MC_ROLLRATE_P 0.13
	param set MC_ROLLRATE_I 0.1
	param set MC_ROLLRATE_D 0.0
	param set MC_ROLLRATE_FF 0
	param set MC_PITCH_P 7.5
	param set MC_PITCHRATE_P 0.06
	param set MC_PITCHRATE_I 0.05
	param set MC_PITCHRATE_D 0.0005
	param set MC_PITCHRATE_FF 0
	param set MC_YAW_P 3.8
	param set MC_YAWRATE_P -0.1
	param set MC_YAWRATE_I 0.02
	param set MC_YAWRATE_D 0.00
	param set MC_YAWRATE_FF 0

	param set VT_IDLE_PWM_MC  1080
	param set VT_ELEV_MC_LOCK 0
	param set VT_MOT_COUNT 2
	param set VT_TYPE 0
fi

set MAV_TYPE 19

set MIXER caipirinha_vtol

set PWM_OUT 1234
