#!/bin/sh
#
# @name Quadrotor + Tailsitter
#
# @type VTOL Quad Tailsitter
# @class VTOL
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 4
# @output MAIN4 motor 5
# @output MAIN5 elevon left
# @output MAIN6 elevon right
# @output MAIN7 canard surface
# @output MAIN8 rudder
#
# @maintainer Roman Bapst <roman@px4.io>
#
# @board px4_fmu-v2 exclude
# @board intel_aerofc-v1 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.vtol_defaults

if [ $AUTOCNF = yes ]
then
	param set PWM_MAIN_MAX 2000
	param set PWM_MAIN_RATE 400

	param set VT_IDLE_PWM_MC  1080
	param set VT_TYPE 0
	param set VT_ELEV_MC_LOCK 1
fi

set MAV_TYPE 20

set MIXER quad_+_vtol

set PWM_OUT 1234
