#!/bin/sh
#
# @name Quadrotor X Tailsitter
#
# @type VTOL Quad Tailsitter
# @class VTOL
#
# @maintainer Roman Bapst <roman@px4.io>
#

sh /etc/init.d/rc.vtol_defaults

if [ $AUTOCNF = yes ]
then
	param set PWM_MAX 2000
	param set PWM_RATE 400

	param set VT_MOT_COUNT 4
	param set VT_IDLE_PWM_MC  1080
	param set VT_TYPE 0
	param set VT_ELEV_MC_LOCK 1

	# Indicate that FW roll direction was fixed in mixer, to be removed in v1.10
	param set V19_VT_ROLLDIR 0
fi

set MAV_TYPE 20

set MIXER quad_x_vtol

set PWM_OUT 1234