#!/bin/sh
#
# @name Caipiroshka Duo Tailsitter
#
# @type VTOL Duo Tailsitter
# @class VTOL
#
# @output MAIN1 motor right
# @output MAIN2 motor left
# @output MAIN5 elevon right
# @output MAIN6 elevon left
#
# @maintainer Roman Bapst <roman@px4.io>
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.vtol_defaults

set MAV_TYPE 19

param set-default MC_ROLL_P 6
param set-default MC_ROLLRATE_P 0.12
param set-default MC_ROLLRATE_I 0.002
param set-default MC_ROLLRATE_D 0.003
param set-default MC_ROLLRATE_FF 0

param set-default MC_PITCH_P 4.5
param set-default MC_PITCHRATE_P 0.3
param set-default MC_PITCHRATE_I 0.002
param set-default MC_PITCHRATE_D 0.003
param set-default MC_PITCHRATE_FF 0

param set-default MC_YAW_P 3.8
param set-default MC_YAWRATE_P 0.22
param set-default MC_YAWRATE_I 0.02
param set-default MC_YAWRATE_D 0
param set-default MC_YAWRATE_FF 0

param set-default VT_IDLE_PWM_MC  1080
param set-default VT_ELEV_MC_LOCK 0
param set-default VT_MOT_ID 12
param set-default VT_TYPE 0


# MAIN
set MIXER vtol_tailsitter_duo
param set-default PWM_MAIN_MIN1 1100
param set-default PWM_MAIN_MIN2 1100

param set-default PWM_MAIN_MAX1 1900
param set-default PWM_MAIN_MAX2 1900

param set-default PWM_MAIN_RATE1 400
param set-default PWM_MAIN_RATE2 400

param set-default PWM_MAIN_DIS1 900
param set-default PWM_MAIN_DIS2 900
param set-default PWM_MAIN_DIS3 1500 # right (starboard) elevon
param set-default PWM_MAIN_DIS4 1500 # left (port) elevon.
