#!/bin/sh
#
# @name Generic quad delta VTOL
#
# @type Standard VTOL
# @class VTOL
#
# @maintainer Simon Wilks <simon@uaventure.com>
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
# @output AUX1 Right elevon
# @output AUX2 Left elevon
# @output AUX3 Motor
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
# @board holybro_kakutef7 exclude
#

. ${R}etc/init.d/rc.vtol_defaults


param set-default MC_ROLLRATE_I 0.01
param set-default MC_PITCHRATE_I 0.01
param set-default MC_YAW_P 3.5

param set-default MC_YAWRATE_MAX 50

param set-default MPC_XY_P 0.8
param set-default MPC_XY_VEL_P_ACC 2
param set-default MPC_ACC_HOR_MAX 2
param set-default MPC_YAWRAUTO_MAX 20

param set-default PWM_AUX_DIS3 950

param set-default VT_MOT_ID 1234
param set-default VT_FW_MOT_OFFID 1234
param set-default VT_F_TRANS_THR 0.75
param set-default VT_IDLE_PWM_MC 1080
param set-default VT_TYPE 2

set MIXER quad_x
set MIXER_AUX vtol_delta

set PWM_OUT 1234
