#!/bin/sh
#
# @name Quadrotor X Tailsitter
#
# @type VTOL Quad Tailsitter
# @class VTOL
#
# @maintainer Roman Bapst <roman@px4.io>
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.mc_quad_defaults
. ${R}etc/init.d/rc.vtol_defaults

set MAV_TYPE 20

param set-default VT_MOT_ID 1234
param set-default VT_IDLE_PWM_MC 1080
param set-default VT_TYPE 0
param set-default VT_ELEV_MC_LOCK 1

# MAIN
set MIXER quad_x_vtol
# outputs 1-4 set by rc.mc_quad_defaults
param set-default PWM_MAIN_DIS5 1500 # left elevon
param set-default PWM_MAIN_DIS6 1500 # right elevon
