#!/bin/sh
#
# @name Quadrotor X Tailsitter
#
# @type VTOL Quad Tailsitter
# @class VTOL
#
# @maintainer Roman Bapst <roman@px4.io>
#
# @board px4_fmu-v2 exclude
# @board intel_aerofc-v1 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.vtol_defaults

if [ $AUTOCNF = yes ]
then
	param set PWM_MAIN_MAX 2000
	param set PWM_MAIN_RATE 400

	param set VT_MOT_ID 1234
	param set VT_IDLE_PWM_MC  1080
	param set VT_TYPE 0
	param set VT_ELEV_MC_LOCK 1
fi

set MAV_TYPE 20

set MIXER quad_x_vtol

set PWM_OUT 1234
