#!/bin/sh
#
# @name QuadRanger
#
# @type Standard VTOL
# @class VTOL
#
# @maintainer Sander Smeets <sander@droneslab.com>
#

. ${R}etc/init.d/rc.vtol_defaults


param set-default FW_THR_CRUISE 65
param set-default FW_RR_FF 0.6

param set-default MIS_YAW_TMT 10

param set-default MC_ROLL_P 7
param set-default MC_ROLLRATE_I 0.1
param set-default MC_ROLLRATE_D 0.004
param set-default MC_PITCH_P 7
param set-default MC_PITCHRATE_I 0.1
param set-default MC_PITCHRATE_D 0.004
param set-default MC_YAW_P 3.5
param set-default MC_YAWRATE_P 0.6
param set-default MC_YAWRATE_I 0.04
param set-default MC_YAWRATE_MAX 40

param set-default MPC_ACC_HOR_MAX 2
param set-default MPC_Z_VEL_MAX_DN 1.5
param set-default MPC_LAND_SPEED 0.8
param set-default MPC_YAWRAUTO_MAX 40

param set-default PWM_AUX_REV1 1
param set-default PWM_AUX_REV2 1

param set-default VT_ARSP_TRANS 15
param set-default VT_ARSP_BLEND 8
param set-default VT_F_TRANS_THR 0.75
param set-default VT_TYPE 2
