#!/bin/sh
#
# @name Generic quad delta VTOL
#
# @type Standard VTOL
# @class VTOL
#
# @maintainer Simon Wilks <simon@uaventure.com>
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
# @output AUX1 Right elevon
# @output AUX2 Left elevon
# @output AUX3 Motor
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.mc_quad_defaults
. ${R}etc/init.d/rc.vtol_defaults

set MAV_TYPE 22

param set-default MC_ROLL_P 6.5
param set-default MC_ROLLRATE_P 0.15
param set-default MC_ROLLRATE_I 0.01
param set-default MC_ROLLRATE_D 0.003
param set-default MC_ROLLRATE_FF 0
param set-default MC_PITCH_P 6.5
param set-default MC_PITCHRATE_P 0.15
param set-default MC_PITCHRATE_I 0.01
param set-default MC_PITCHRATE_D 0.003
param set-default MC_PITCHRATE_FF 0
param set-default MC_YAW_P 3.5
param set-default MC_YAWRATE_P 0.2
param set-default MC_YAWRATE_I 0.1
param set-default MC_YAWRATE_D 0
param set-default MC_YAWRATE_FF 0
param set-default MC_YAWRATE_MAX 50

param set-default MPC_XY_P 0.8
param set-default MPC_XY_VEL_P_ACC 2
param set-default MPC_ACC_HOR_MAX 2
param set-default MPC_YAWRAUTO_MAX 20

param set-default VT_MOT_ID 1234
param set-default VT_FW_MOT_OFFID 1234
param set-default VT_F_TRANS_THR 0.75
param set-default VT_IDLE_PWM_MC 1080
param set-default VT_TYPE 2

# MAIN set by rc.mc_quad_defaults

# AUX
set MIXER_AUX vtol_delta
param set-default PWM_AUX_DIS1 1500
param set-default PWM_AUX_DIS2 1500
param set-default PWM_AUX_DIS3 900 # throttle
param set-default PWM_AUX_DIS4 900 # throttle reverse
