#!/bin/sh
#
# @name BabyShark VTOL
#
# @type Standard VTOL
# @class VTOL
#
# @maintainer Silvan Fuhrer <silvan@auterion.com>
#
# @output MAIN1 Ailerons
# @output MAIN2 A-tail left
# @output MAIN3 Pusher motor
# @output MAIN4 A-tail right
# @output MAIN5 motor 1
# @output MAIN6 motor 2
# @output MAIN7 motor 3
# @output MAIN8 motor 4
#
# @board px4_fmu-v2 exclude
# @board intel_aerofc-v1 exclude
# @board bitcraze_crazyflie exclude
#

sh /etc/init.d/rc.vtol_defaults


param import-airframe /etc/init.d

set MAV_TYPE 22

set MIXER babyshark
set MIXER_AUX pass

set PWM_OUT 5678
