#!/bin/sh
#
# @name CruiseAder Claire
#
# @type VTOL Tiltrotor
# @class VTOL
#
# @maintainer Samay Siga <samay_s@icloud.com>
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.vtol_defaults


param set-default PWM_AUX_DISARM 1000
param set-default PWM_AUX_MAX 2000
param set-default PWM_AUX_MIN 1000
param set-default PWM_AUX_RATE 50

param set-default PWM_MAIN_MAX 2000
param set-default PWM_MAIN_RATE 400

param set-default PWM_MAIN_MIN1 1080
param set-default PWM_MAIN_MIN2 1080
param set-default PWM_MAIN_MIN3 1080
param set-default PWM_MAIN_MIN4 1080


param set-default VT_MOT_ID 1234
param set-default VT_FW_MOT_OFFID 13
param set-default VT_IDLE_PWM_FW 1000
param set-default VT_TILT_FW 0.9
param set-default VT_TILT_MC 0.08
param set-default VT_TILT_TRANS 0.5
param set-default VT_ELEV_MC_LOCK 0
param set-default VT_TYPE 1
set MAV_TYPE 21

set MIXER claire
set MIXER_AUX claire

set PWM_OUT 1234
