#!/bin/sh
#
# @name Vertical Technologies DeltaQuad
#
# @type Standard VTOL
# @class VTOL
#
# @maintainer Sander Smeets <sander@droneslab.com>
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
# @output MAIN5 Right elevon
# @output MAIN6 Left elevon
# @output MAIN7 Pusher motor
# @output MAIN8 Pusher reverse channel
#

sh /etc/init.d/rc.vtol_defaults

param import-as-default /etc/init.d/13013.params

set MAV_TYPE 22

set MIXER deltaquad
set MIXER_AUX pass

set PWM_OUT 1234
set PWM_AUX_OUT 12345
