#!/bin/sh
#
# @name CruiseAder Claire
#
# @type VTOL Tiltrotor
# @class VTOL
#
# @maintainer Samay Siga <samay_s@icloud.com>
#
# @board px4_fmu-v2 exclude
#

sh /etc/init.d/rc.vtol_defaults

if [ $AUTOCNF = yes ]
then
	param set PWM_AUX_DISARMED 1000
	param set PWM_AUX_MAX 2000
	param set PWM_AUX_MIN 1000
	param set PWM_AUX_RATE 50

	param set PWM_MAX 2000
	param set PWM_RATE 400

	param set VT_MOT_COUNT 4
	param set VT_FW_MOT_OFFID 13
	param set VT_IDLE_PWM_MC 1080
	param set VT_TILT_FW 0.9
	param set VT_TILT_MC 0.08
	param set VT_TILT_TRANS 0.5
	param set VT_ELEV_MC_LOCK 0
	param set VT_TYPE 1

	# Indicate that FW roll direction was fixed in mixer, to be removed in v1.10
	param set V19_VT_ROLLDIR 0
fi

set MAV_TYPE 21

set MIXER claire
set MIXER_AUX claire

set PWM_OUT 1234
