#!/bin/sh
#
# @name Generic Octoplane VTOL
#
# @type VTOL Octoplane
# @class VTOL
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
# @output MAIN5 motor 5
# @output MAIN6 motor 6
# @output MAIN7 motor 7
# @output MAIN8 motor 8
# @output AUX1 Aileron 1
# @output AUX2 Aileron 2
# @output AUX3 Elevator
# @output AUX4 Rudder
# @output AUX5 Throttle
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.mc_octo_defaults
. ${R}etc/init.d/rc.vtol_defaults

set MAV_TYPE 22

param set-default VT_TYPE 2
param set-default VT_MOT_ID 12345678
param set-default VT_FW_MOT_OFFID 12345678

# MAIN set by rc.mc_octo_defaults

# AUX
set MIXER_AUX vtol_AAERT
param set-default PWM_AUX_DIS1 1500
param set-default PWM_AUX_DIS2 1500
param set-default PWM_AUX_DIS3 1500
param set-default PWM_AUX_DIS4 1500
param set-default PWM_AUX_DIS5 900 # throttle
