#!/bin/sh
#
# @name Tri EDF Tailsitter
#
# @type VTOL Tailsitter
# @class VTOL
#
# @maintainer Manas Rajendran <rmanas@tamu.edu>
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
# @board holybro_kakutef7 exclude
#

. ${R}etc/init.d/rc.vtol_defaults

param set-default EKF2_FUSE_BETA 0 # side slip fusion is currently not supported for tailsitters

param set-default CA_AIRFRAME 4 # airframe file is set to vtol
param set-default CA_ROTOR_COUNT 3
param set-default CA_SV_CS_COUNT 6

# Rotor Configuration

# param set-default CA_ROTOR#_AX = Axis direction X thrust component - 0
# param set-default CA_ROTOR#_AY = Axis direction Y thrust component - 0
# param set-default CA_ROTOR#_AZ = Axis direction Z thrust component - -1 (pointing downwards along fuselage axis)
# param set-default CA_ROTOR#_CT = motor thrust to input coefficient - 6.5 is the default working value so no change is needed
# param set-default CA_ROTOR#_KM = Torque coefficient (yaw moment). Negative = CW rotation, Positive = CCW rotation. The value is the ratio of torque to thrust.
# param set-default CA_ROTOR#_PX = motor position X relative to GC
# param set-default CA_ROTOR#_PY = motor position Y relative to GC
# param set-default CA_ROTOR#_PZ = motor position Z relative to GC

# Rotor 0

param set-default CA_ROTOR0_AX 0
param set-default CA_ROTOR0_AY 0
param set-default CA_ROTOR0_AZ -1
param set-default CA_ROTOR0_CT 6.5
param set-default CA_ROTOR0_KM -0.05
param set-default CA_ROTOR0_PX 0.08
param set-default CA_ROTOR0_PY 0.13
param set-default CA_ROTOR0_PZ #TODO

# Rotor 1

param set-default CA_ROTOR1_AX 0
param set-default CA_ROTOR1_AY 0
param set-default CA_ROTOR1_AZ -1
param set-default CA_ROTOR1_CT 6.5
param set-default CA_ROTOR1_KM 0.05
param set-default CA_ROTOR1_PX 0.08
param set-default CA_ROTOR1_PY -0.13
param set-default CA_ROTOR1_PZ #TODO

# Rotor 2

param set-default CA_ROTOR2_AX 0
param set-default CA_ROTOR2_AY 0
param set-default CA_ROTOR2_AZ -1
param set-default CA_ROTOR2_CT 6.5
param set-default CA_ROTOR2_KM 0.05
param set-default CA_ROTOR2_PX -0.15
param set-default CA_ROTOR2_PY 0
param set-default CA_ROTOR2_PZ #TODO

# Control Surface Configuration

# param set-default CA_SV_CS#_TYPE = Control surface type
#   0 = None (disabled)
#   1 = Left Aileron
#   2 = Right Aileron
#   3 = Elevator
#   4 = Rudder
#   5 = Left Elevon
#   6 = Right Elevon
#   7 = Left V-Tail
#   8 = Right V-Tail
#   (and more types available)

# param set-default CA_SV_CS#_TRQ_R = Roll torque scaling (-1 to 1)
#   Positive = deflection creates positive roll moment (right wing down)
#   Negative = deflection creates negative roll moment (left wing down)
#   0 = no roll authority

# param set-default CA_SV_CS#_TRQ_P = Pitch torque scaling (-1 to 1)
#   Positive = deflection creates positive pitch moment (nose up)
#   Negative = deflection creates negative pitch moment (nose down)
#   0 = no pitch authority

# param set-default CA_SV_CS#_TRQ_Y = Yaw torque scaling (-1 to 1)
#   Positive = deflection creates positive yaw moment (nose right)
#   Negative = deflection creates negative yaw moment (nose left)
#   0 = no yaw authority

# param set-default CA_SV_CS#_TRIM = Trim offset (-1 to 1)
#   Adjusts neutral position of the control surface
#   0 = no trim offset (centered)
#   Positive/negative = offset from center

# param set-default CA_SV_CS#_FLAP = Flap effectiveness (0 to 1)
#   0 = no flap function
#   1 = full flap deflection capability

# param set-default CA_SV_CS#_SPOIL = Spoiler effectiveness (0 to 1)
#   0 = no spoiler function
#   1 = full spoiler deflection capability

# param set-default CA_SV_CS#_SLEW = Slew rate limit (rad/s)
#   0 = unlimited (no rate limiting)
#   >0 = maximum rate of deflection change

# Optional Position Parameters (usually not required):
# param set-default CA_SV_CS#_PX = surface position X relative to CG (meters)
# param set-default CA_SV_CS#_PY = surface position Y relative to CG (meters)
# param set-default CA_SV_CS#_PZ = surface position Z relative to CG (meters)


param set-default CA_SV_CS2_TRIM 0.0


param set-default CA_SV_CS_COUNT 2
param set-default CA_SV_CS0_TRQ_P 0.5
param set-default CA_SV_CS0_TRQ_Y 0.5
param set-default CA_SV_CS0_TYPE 5
param set-default CA_SV_CS1_TRQ_P 0.5
param set-default CA_SV_CS1_TRQ_Y -0.5
param set-default CA_SV_CS1_TYPE 6

param set-default MAV_TYPE 19
param set-default VT_TYPE 0
param set-default VT_ELEV_MC_LOCK 0
param set-default VT_B_TRANS_DUR 5