#!/bin/sh
#
# @name Esky (Big) Lama v4
#
# @type Coaxial Helicopter
# @class Copter
#
# @output MAIN1 Left swashplate servomotor, pitch axis
# @output MAIN2 Right swashplate servomotor, roll axis
# @output MAIN3 Upper rotor (CCW)
# @output MAIN4 Lower rotor (CW)
#
# @maintainer Emmanuel Roussel
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.mc_defaults
set MIXER coax

param set-default MC_ROLLRATE_P 0.17
param set-default MC_ROLLRATE_I 0.05
param set-default MC_ROLLRATE_D 0.005
param set-default MC_PITCHRATE_P 0.17
param set-default MC_PITCHRATE_I 0.05
param set-default MC_PITCHRATE_D 0.005
param set-default MC_YAW_P 2
param set-default MC_YAWRATE_P 0.1

param set-default NAV_ACC_RAD 2

param set-default PWM_AUX_RATE 50
param set-default PWM_MAIN_DISARM 900
param set-default PWM_MAIN_RATE 400

param set-default RTL_RETURN_ALT 30
param set-default RTL_DESCEND_ALT 10
# This is the gimbal pass mixer
set MIXER_AUX pass

# use PWM parameters for throttle channel
set PWM_OUT 34
