#!/bin/sh
#
# @name TF:AutoG2
#
# @type Autogyro
# @class Autogyro
#
# @output MAIN1 rotor_head_L
# @output MAIN2 rotor_head_R
# @output MAIN3 elevator
# @output MAIN4 rudder
# @output MAIN5 rudder (second, optional)
# @output MAIN6 throttle
# @output MAIN7 wheel
#
# @output AUX1 prerotator (optional)
# @output AUX2 release_device (optional)
#
# @url https://github.com/ThunderFly-aerospace/Auto-G2/
# @maintainer ThunderFly s.r.o., Roman Dvorak <dvorak.roman@thunderfly.cz>
#

sh /etc/init.d/rc.fw_defaults

if [ $AUTOCNF = yes ]
then
	param set BAT_CAPACITY 2500.0
	param set BAT_N_CELLS 3

	param set FW_AIRSPD_MAX = 20
	param set FW_AIRSPD_MIN = 7
	param set FW_AIRSPD_TRIM = 13
	param set FW_THR_CRUISE  = 0.8
	param set FW_R_LIM = 40
fi

set MIXER TF-AutoG2
