#!/bin/sh
#
# @name ThunderFly balloon TF-B1
#
# @type Balloon
# @class Balloon
#
#
# @url https://github.com/ThunderFly-aerospace/TF-B1/
# @maintainer ThunderFly s.r.o.
#
# @board px4_fmu-v2 exclude
# @board intel_aerofc-v1 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.balloon_defaults

if [ $AUTOCNF = yes ]
then
	param set COM_PREARM_MODE 2  # always in prearm state
	param set CBRK_IO_SAFETY 22027
	param set SDLOG_PROFILE 17
	param set SDLOG_MODE 2
	param set MAV_0_MODE 1
	param set MAV_0_CONFIG 102
	param set GPS_UBX_DYNMODEL 8
	param set SER_TEL2_BAUD 9600

	param set SENS_BOARD_ROT 0
        param set MAV_TYPE 8  # MAV_TYPE_FREE_BALLOON

fi


set MIXER IO_pass
set MIXER_AUX pass
