#!/bin/sh
#
# @name X-UAV Mini Talon
#
# @type Plane V-Tail
# @class Plane
#
# @output MAIN1 aileron right
# @output MAIN2 aileron left
# @output MAIN3 v-tail right
# @output MAIN4 v-tail left
# @output MAIN5 throttle
# @output MAIN6 wheel
# @output MAIN7 flaps right
# @output MAIN8 flaps left
#
# @output AUX1 feed-through of RC AUX1 channel
# @output AUX2 feed-through of RC AUX2 channel
# @output AUX3 feed-through of RC AUX3 channel
#
# @maintainer Friedrich Beckmann <friedrich.beckmann@hs-augsburg.de>
#
# @board px4_fmu-v2 exclude
# @board intel_aerofc-v1 exclude
# @board bitcraze_crazyflie exclude
#

sh /etc/init.d/rc.fw_defaults

if [ $AUTOCNF = yes ]
then
	param set FW_AIRSPD_MIN 10
	param set FW_AIRSPD_TRIM 15
	param set FW_AIRSPD_MAX 20

	param set FW_MAN_P_MAX 55
	param set FW_MAN_R_MAX 55
	param set FW_R_LIM 55

	param set FW_WR_FF 0.2
	param set FW_WR_I 0.2
	param set FW_WR_IMAX 0.8
	param set FW_WR_P 1
	param set FW_W_RMAX 0

	# set disarmed value for the ESC
	param set PWM_DISARMED 1000
fi

# The Mini Talon does not have a wheel and
# no flaps. I leave them here because the mixer
# computes also wheel and flap controls.
set MIXER AAVVTWFF_vtail

# use PWM parameters for throttle channel
set PWM_OUT 5
