#!/bin/sh
#
# @name Generic Dodecarotor cox geometry
#
# @type Dodecarotor cox
# @class Copter
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
# @output MAIN5 motor 5
# @output MAIN6 motor 6
#
# @output AUX1 motor 7
# @output AUX2 motor 8
# @output AUX3 motor 9
# @output AUX4 motor 10
# @output AUX5 motor 11
# @output AUX6 motor 12
#
# @maintainer Ian McNanie <ianmcnanie@gmail.com>
# @maintainer William Peale <develop707@gmail.com>
#
# @board bitcraze_crazyflie exclude
# @board px4_fmu-v2 exclude
#

set VEHICLE_TYPE mc


param set-default NAV_ACC_RAD 2

param set-default PWM_AUX_RATE 400
param set-default PWM_AUX_DISARM 900
param set-default PWM_AUX_MIN 1075
param set-default PWM_AUX_MAX 1950

param set-default PWM_MAIN_MIN 1075
param set-default PWM_MAIN_MAX 1950
param set-default PWM_MAIN_RATE 400

param set-default RTL_DESCEND_ALT 10
param set-default RTL_RETURN_ALT 30
set MIXER dodeca_top_cox
set MIXER_AUX dodeca_bottom_cox

# Need to set all 8 channels
set PWM_OUT 12345678
set PWM_AUX_OUT 123456
