#!/bin/sh
#
# @name Generic Dodecarotor cox geometry
#
# @type Dodecarotor cox
# @class Copter
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
# @output MAIN5 motor 5
# @output MAIN6 motor 6
#
# @output AUX1 motor 7
# @output AUX2 motor 8
# @output AUX3 motor 9
# @output AUX4 motor 10
# @output AUX5 motor 11
# @output AUX6 motor 12
#
# @maintainer Ian McNanie <ianmcnanie@gmail.com>
# @maintainer William Peale <develop707@gmail.com>
#
# @board bitcraze_crazyflie exclude
#

set VEHICLE_TYPE mc

param set-default NAV_ACC_RAD 2

param set-default RTL_DESCEND_ALT 10
param set-default RTL_RETURN_ALT 30

# MAIN
param set-default PWM_MAIN_MIN1 1100
param set-default PWM_MAIN_MIN2 1100
param set-default PWM_MAIN_MIN3 1100
param set-default PWM_MAIN_MIN4 1100
param set-default PWM_MAIN_MIN5 1100
param set-default PWM_MAIN_MIN6 1100

param set-default PWM_MAIN_MAX1 1900
param set-default PWM_MAIN_MAX2 1900
param set-default PWM_MAIN_MAX3 1900
param set-default PWM_MAIN_MAX4 1900
param set-default PWM_MAIN_MAX5 1900
param set-default PWM_MAIN_MAX6 1900

param set-default PWM_MAIN_RATE1 400
param set-default PWM_MAIN_RATE2 400
param set-default PWM_MAIN_RATE3 400
param set-default PWM_MAIN_RATE4 400
param set-default PWM_MAIN_RATE5 400
param set-default PWM_MAIN_RATE6 400

param set-default PWM_MAIN_DIS1 900
param set-default PWM_MAIN_DIS2 900
param set-default PWM_MAIN_DIS3 900
param set-default PWM_MAIN_DIS4 900
param set-default PWM_MAIN_DIS5 900
param set-default PWM_MAIN_DIS6 900

# AUX
param set-default PWM_AUX_MIN1 1100
param set-default PWM_AUX_MIN2 1100
param set-default PWM_AUX_MIN3 1100
param set-default PWM_AUX_MIN4 1100
param set-default PWM_AUX_MIN5 1100
param set-default PWM_AUX_MIN6 1100

param set-default PWM_AUX_MAX1 1900
param set-default PWM_AUX_MAX2 1900
param set-default PWM_AUX_MAX3 1900
param set-default PWM_AUX_MAX4 1900
param set-default PWM_AUX_MAX5 1900
param set-default PWM_AUX_MAX6 1900

param set-default PWM_AUX_RATE1 400
param set-default PWM_AUX_RATE2 400
param set-default PWM_AUX_RATE3 400
param set-default PWM_AUX_RATE4 400
param set-default PWM_AUX_RATE5 400
param set-default PWM_AUX_RATE6 400

param set-default PWM_AUX_DIS1 900
param set-default PWM_AUX_DIS2 900
param set-default PWM_AUX_DIS3 900
param set-default PWM_AUX_DIS4 900
param set-default PWM_AUX_DIS5 900
param set-default PWM_AUX_DIS6 900

set MIXER dodeca_top_cox
set MIXER_AUX dodeca_bottom_cox
