#!/bin/sh
#
# @name Cloudship
# @type Airship
# @class Airship
#
# @output MAIN1 starboard thruster
# @output MAIN2 port thruster
# @output MAIN3 thrust tilt
# @output MAIN4 tail thruster
#

. ${R}etc/init.d/rc.airship_defaults

param set-default COM_PREARM_MODE 2
