#!/bin/sh
#
# @name Phantom FPV Flying Wing
#
# @url https://docs.px4.io/master/en/frames_plane/wing_wing_z84.html
#
# @type Flying Wing
# @class Plane
#
# @output MAIN1 left aileron
# @output MAIN2 right aileron
# @output MAIN4 throttle
#
# @maintainer Simon Wilks <simon@uaventure.com>
#

. ${R}etc/init.d/rc.fw_defaults

param set-default FW_AIRSPD_MIN 13
param set-default FW_AIRSPD_MAX 25
param set-default FW_R_TC 0.3
param set-default FW_P_TC 0.3
param set-default FW_L1_PERIOD 15
param set-default FW_PR_FF 0.2
param set-default FW_PR_IMAX 0.2
param set-default FW_PR_P 0.03
param set-default FW_P_LIM_MAX 50
param set-default FW_P_LIM_MIN -50
param set-default FW_RR_P 0.08
param set-default FW_R_LIM 50
param set-default FW_R_RMAX 50

# Bottom of bay and nominal zero-pitch attitude differ
# the payload bay is pitched up about 7 degrees
param set-default SENS_BOARD_Y_OFF 7

param set-default CA_AIRFRAME 1
param set-default CA_ROTOR_COUNT 1
param set-default CA_ROTOR0_PX 0.3
param set-default CA_SV_CS_COUNT 4
param set-default CA_SV_CS0_TRQ_R -0.5
param set-default CA_SV_CS1_TRQ_R 0.5
param set-default CA_SV_CS1_TYPE 2
param set-default CA_SV_CS2_TRQ_P 1.0
param set-default CA_SV_CS2_TYPE 3
param set-default CA_SV_CS3_TRQ_Y 1.0
param set-default CA_SV_CS3_TYPE 4
