#!/bin/sh
#
# @name Sparkle Tech Pigeon
#
# @url http://www.sparkletech.hk/
#
# @type Flying Wing
# @class Plane
#
# @output MAIN1 left aileron
# @output MAIN2 right aileron
# @output MAIN4 throttle
#
# @output AUX1 feed-through of RC AUX1 channel
# @output AUX2 feed-through of RC AUX2 channel
# @output AUX3 feed-through of RC AUX3 channel
#
# @maintainer Simon Wilks <simon@uaventure.com>
#
# @board bitcraze_crazyflie exclude
#

sh /etc/init.d/rc.fw_defaults

param import-as-default /etc/init.d/3036.params
set MIXER phantom

# Provide ESC a constant 1000 us pulse
set PWM_OUT 4
