#!/bin/sh
#
# @name Sparkle Tech Pigeon
#
# @url http://www.sparkletech.hk/
#
# @type Flying Wing
# @class Plane
#
# @output MAIN1 left aileron
# @output MAIN2 right aileron
# @output MAIN4 throttle
#
# @output AUX1 feed-through of RC AUX1 channel
# @output AUX2 feed-through of RC AUX2 channel
# @output AUX3 feed-through of RC AUX3 channel
#
# @maintainer Simon Wilks <simon@uaventure.com>
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.fw_defaults

param set-default FW_AIRSPD_MIN 15
param set-default FW_AIRSPD_TRIM 20
param set-default FW_AIRSPD_MAX 27
param set-default FW_ATT_TC 0.3
param set-default FW_L1_DAMPING 0.75
param set-default FW_L1_PERIOD 20
param set-default FW_PR_FF 0.35
param set-default FW_PR_IMAX 0.2
param set-default FW_PR_P 0.05
param set-default FW_P_LIM_MAX 45
param set-default FW_P_LIM_MIN -45
param set-default FW_P_ROLLFF 1
param set-default FW_P_TC 0.3
param set-default FW_RR_FF 0.3
param set-default FW_RR_IMAX 0.2
param set-default FW_RR_P 0.03
param set-default FW_R_LIM 40
param set-default FW_R_RMAX 50
param set-default FW_R_TC 0.3

param set-default PWM_MAIN_DISARM 1000

# Bottom of bay and nominal zero-pitch attitude differ
# the payload bay is pitched up about 7 degrees
param set-default SENS_BOARD_Y_OFF 11.9

set MIXER fw_generic_wing

# Provide ESC a constant 1000 us pulse
set PWM_OUT 4
