#!/bin/sh
#
# @name Modified Parrot Disco
#
# @url
#
# @type Flying Wing
# @class Plane
#
# @output MAIN1 left aileron
# @output MAIN2 right aileron
# @output MAIN4 throttle
#
# @output AUX1 feed-through of RC AUX1 channel
# @output AUX2 feed-through of RC AUX2 channel
# @output AUX3 feed-through of RC AUX3 channel
#
# @maintainer Jan Liphardt <JTLiphardt@gmail.com>
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.fw_defaults

####################################
# Airspeed
####################################
param set-default FW_AIRSPD_MIN  15 # = 29 knots
param set-default FW_AIRSPD_TRIM 20 # = 39 knots
param set-default FW_AIRSPD_MAX  27 # = 52 knots

####################################
# The Main L1 Controller
####################################
param set-default FW_L1_PERIOD 20 #units of meters

# Damping factor for L1 control (def = 0.75)
param set-default FW_L1_DAMPING 0.75

####################################
# Pitch
####################################

# Basic limits (def = +/- 45 deg)
param set-default FW_P_LIM_MAX  45
param set-default FW_P_LIM_MIN -45

# Time Constant (def = 0.4s)
param set-default FW_P_TC 0.4

# Pitch rate feed forward (def = 0.5 %/rad/sec)
param set-default FW_PR_FF 0.35

# Pitch rate integrator limit (def = 0.4)
param set-default FW_PR_IMAX 0.4

# Pitch rate proportional gain (def = 0.08 %/rad/sec)
param set-default FW_PR_P 0.08

####################################
# Roll
####################################

# Basic limits (def = 50 deg)
param set-default FW_R_LIM 40

# Roll rate upper limit (def = 70 deg/s)
param set-default FW_R_RMAX 50

# Roll Time Constant (def = 0.4 s)
param set-default FW_R_TC 0.4

# Roll rate feed forward (def = 0.5 %/rad/sec)
param set-default FW_RR_FF 0.5

# Roll rate proportional Gain (def = 0.05 %/rad/sec)
param set-default FW_RR_P 0.05

# Roll Integrator Anti-Windup
param set-default FW_RR_IMAX 0.2


set MIXER fw_generic_wing.main.mix

# Provide ESC a constant 1000 us pulse
param set-default PWM_MAIN_DIS4 1000
