#!/bin/sh
#
# @name Modified Parrot Disco
#
# @url
#
# @type Flying Wing
# @class Plane
#
# @output MAIN1 left aileron
# @output MAIN2 right aileron
# @output MAIN4 throttle
#
# @output AUX1 feed-through of RC AUX1 channel
# @output AUX2 feed-through of RC AUX2 channel
# @output AUX3 feed-through of RC AUX3 channel
#
# @maintainer Jan Liphardt <JTLiphardt@gmail.com>
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.fw_defaults

####################################
# Airspeed
####################################
param set-default FW_AIRSPD_MAX  27 # = 52 knots

####################################
# Pitch
####################################

# Pitch rate feed forward (def = 0.5 %/rad/sec)
param set-default FW_PR_FF 0.35

####################################
# Roll
####################################

# Basic limits (def = 50 deg)
param set-default FW_R_LIM 40

# Roll rate upper limit (def = 70 deg/s)
param set-default FW_R_RMAX 50

param set-default PWM_MAIN_DISARM 1000

set MIXER fw_generic_wing.main.mix

# Provide ESC a constant 1000 us pulse
set PWM_OUT 4
