#!/bin/sh
#
# @name Generic Quadcopter
#
# @type Quadrotor x
# @class Copter
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
#
# @maintainer Lorenz Meier <lorenz@px4.io>
#

. ${R}etc/init.d/rc.mc_defaults

# PX4 default motor ordering:
#  3     1
#     ^
#  2     4
param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

# front right (CCW)
param set-default CA_ROTOR0_PX 0.707107
param set-default CA_ROTOR0_PY 0.707107
param set-default CA_ROTOR0_KM 0.05

# rear left (CCW)
param set-default CA_ROTOR1_PX -0.707107
param set-default CA_ROTOR1_PY -0.707107
param set-default CA_ROTOR1_KM 0.05

# front left (CW)
param set-default CA_ROTOR2_PX 0.707107
param set-default CA_ROTOR2_PY -0.707107
param set-default CA_ROTOR2_KM -0.05

# rear right (CW)
param set-default CA_ROTOR3_PX -0.707107
param set-default CA_ROTOR3_PY 0.707107
param set-default CA_ROTOR3_KM -0.05
