#!/bin/sh
#
# @name FSR Scidominus
#
# @type Quadrotor
# @class Copter
#
# @maintainer Benedikt Schorr (schorr@fsr.tu-darmstadt.de)
#

. ${R}etc/init.d/rc.mc_defaults

param set-default IMU_GYRO_CUTOFF 30

# Regelparameter

param set-default MC_ROLLRATE_P 0.171
param set-default MC_PITCHRATE_P 0.164
param set-default MC_YAWRATE_P 0.15

param set-default MC_ROLLRATE_I 0.185
param set-default MC_PITCHRATE_I 0.175
param set-default MC_YAWRATE_I 0.17

param set-default MC_ROLLRATE_D 0.0015
param set-default MC_PITCHRATE_D 0.0012

# Motorzuordnung

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104

# Square quadrotor X PX4 numbering
param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 0.25
param set-default CA_ROTOR0_PY 0.25
param set-default CA_ROTOR1_PX -0.25
param set-default CA_ROTOR1_PY -0.25
param set-default CA_ROTOR2_PX 0.25
param set-default CA_ROTOR2_PY -0.25
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -0.25
param set-default CA_ROTOR3_PY 0.25
param set-default CA_ROTOR3_KM -0.05

# Battery parameters (eventuell ändern, wenn andere Batterie verwendet wird)

param set-default BAT_N_CELLS 6
param set-default BAT_V_EMPTY 3.7
param set-default BAT_V_CHARGED 4.2

# RC setup
param set-default COM_FLTMODE1 2
param set-default COM_FLTMODE2 6
param set-default COM_FLTMODE3 5
param set-default COM_FLTMODE4 8
param set-default COM_FLTMODE5 3
param set-default COM_FLTMODE6 7