#!/bin/sh
#
# @name TUDa FSR SciDominus
#
# @type Quadrotor x
# @class Copter
#
# @maintainer UAS Team FSR@TUDa <uas@fsr.tu-darmstadt.de>
#

. ${R}etc/init.d/rc.mc_defaults

param set-default IMU_GYRO_CUTOFF 30

# Control Params

param set-default MC_ROLLRATE_P 0.171
param set-default MC_PITCHRATE_P 0.164
param set-default MC_YAWRATE_P 0.15

param set-default MC_ROLLRATE_I 0.185
param set-default MC_PITCHRATE_I 0.175
param set-default MC_YAWRATE_I 0.17

param set-default MC_ROLLRATE_D 0.0015
param set-default MC_PITCHRATE_D 0.0012

# Control Allocation

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104

# Geometry

param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 0.25
param set-default CA_ROTOR0_PY 0.25
param set-default CA_ROTOR1_PX -0.25
param set-default CA_ROTOR1_PY -0.25
param set-default CA_ROTOR2_PX 0.25
param set-default CA_ROTOR2_PY -0.25
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -0.25
param set-default CA_ROTOR3_PY 0.25
param set-default CA_ROTOR3_KM -0.05

# Battery parameters (eventuell ändern, wenn andere Batterie verwendet wird)

param set-default BAT_N_CELLS 6
param set-default BAT_V_EMPTY 3.7
param set-default BAT_V_CHARGED 4.2

# RC setup
param set-default COM_FLTMODE1 2
param set-default COM_FLTMODE2 6
param set-default COM_FLTMODE3 5
param set-default COM_FLTMODE4 8
param set-default COM_FLTMODE5 3
param set-default COM_FLTMODE6 7

# Companion Comms
param set-default MAV_2_CONFIG 1000
param set-default MAV_2_BROADCAST 1
param set-default MAV_2_MODE 2
param set-default MAV_2_RADIO_CTL 0
param set-default MAV_2_RATE 100000 
param set-default MAV_2_REMOTE_PRT 14540
param set-default MAV_2_UDP_PRT 14540
param set-default ZENOH_ENABLE 0
