#!/bin/sh
#
# @name Lumenier QAV-R (raceblade) 5" arms
#
# @type Quadrotor x
# @class Copter
#
# @maintainer James Goppert <james.goppert@gmail.com>
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.mc_defaults

param set-default MC_ROLL_P 8
param set-default MC_ROLLRATE_P 0.08
param set-default MC_ROLLRATE_I 0.16
param set-default MC_PITCH_P 8
param set-default MC_PITCHRATE_P 0.1
param set-default MC_YAWRATE_P 0.15

param set-default MPC_THR_MIN 0.06
param set-default MPC_MANTHR_MIN 0.06

param set-default PWM_MAIN_MIN 1075
