#!/bin/sh
#
# @name Lumenier QAV250
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Lorenz Meier <lorenz@px4.io>
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

sh /etc/init.d/rc.mc_defaults

set MIXER quad_x
set PWM_OUT 1234

if [ $AUTOCNF = yes ]
then
	param set ATT_BIAS_MAX 0

	param set CBRK_IO_SAFETY 22027

	param set MC_TPA_BREAK_P 0.5
	param set MC_TPA_RATE_P 0.5

	param set MPC_MANTHR_MIN 0.06
	param set MC_ROLL_P 6
	param set MC_ROLLRATE_P 0.14
	param set MC_ROLLRATE_I 0.23
	param set MC_ROLLRATE_D 0.0025
	param set MC_PITCH_P 7
	param set MC_PITCHRATE_P 0.235
	param set MC_PITCHRATE_I 0.17
	param set MC_PITCHRATE_D 0.004
	param set MC_YAW_P 4
	param set MC_YAWRATE_P 0.3
	param set MC_YAWRATE_I 0.2
	param set MC_YAWRATE_D 0
	param set MPC_THR_MIN 0.06

	param set PWM_MIN 1075
fi
