#!/bin/sh
#
# @name Lumenier QAV250
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Lorenz Meier <lorenz@px4.io>
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.mc_quad_defaults

param set-default ATT_BIAS_MAX 0

param set-default CBRK_IO_SAFETY 22027

param set-default MPC_MANTHR_MIN 0.06
param set-default MC_ROLL_P 6
param set-default MC_ROLLRATE_P 0.14
param set-default MC_ROLLRATE_I 0.23
param set-default MC_ROLLRATE_D 0.0025
param set-default MC_PITCH_P 7
param set-default MC_PITCHRATE_P 0.235
param set-default MC_PITCHRATE_I 0.17
param set-default MC_PITCHRATE_D 0.004
param set-default MC_YAW_P 4
param set-default MC_YAWRATE_P 0.3
param set-default MC_YAWRATE_I 0.2
param set-default MC_YAWRATE_D 0
param set-default MPC_THR_MIN 0.06
