#!/bin/sh
#
# @name DJI Flame Wheel F330
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Lorenz Meier <lorenz@px4.io>
#

sh /etc/init.d/rc.mc_defaults

set MIXER quad_x
set PWM_OUT 1234

param import-as-default /etc/init.d/4010.params
