#!/bin/sh
#
# @name DJI Flame Wheel F450
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Lorenz Meier <lorenz@px4.io>
#

sh /etc/init.d/rc.mc_defaults

if [ $AUTOCNF = yes ]
then
	# DJI ESCs do not support calibration and need a higher min
	param set PWM_MIN 1230
fi

set MIXER quad_x
