#!/bin/sh
#
# @name F450-sized quadrotor with CAN
#
# @type Quadrotor x
# @class Copter
#
# @board px4_fmu-v2 exclude
#
# @maintainer Pavel Kirienko <pavel.kirienko@gmail.com>
#

sh /etc/init.d/rc.mc_defaults

set MIXER quad_x
set PWM_OUT 1234

param import-airframe /etc/init.d

set MIXER quad_x_can
set OUTPUT_MODE uavcan_esc
