#!/bin/sh
#
# @name S500
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Lorenz Meier <lorenz@px4.io>
#

sh /etc/init.d/rc.mc_defaults

set MIXER quad_x
set PWM_OUT 1234

if [ $AUTOCNF = yes ]
then
	param set MC_ROLL_P 6.5
	param set MC_ROLLRATE_P 0.18
	param set MC_ROLLRATE_I 0.15
	param set MC_ROLLRATE_D 0.003
	param set MC_PITCH_P 6.5
	param set MC_PITCHRATE_P 0.18
	param set MC_PITCHRATE_I 0.15
	param set MC_PITCHRATE_D 0.003
fi
