#!/bin/sh
#
# @name S500 Generic
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Lorenz Meier <lorenz@px4.io>
#

sh /etc/init.d/rc.mc_defaults

if [ $AUTOCNF = yes ]
then
	param set MC_ROLLRATE_P 0.18
	param set MC_PITCHRATE_P 0.18
	param set MC_ROLLRATE_I 0.15
	param set MC_PITCHRATE_I 0.15
	param set MC_ROLLRATE_D 0.003
	param set MC_PITCHRATE_D 0.003
fi

set MIXER quad_x
