#!/bin/sh
#
# @name Holybro X500 V2
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Farhang Naderi <farhang.nba@gmail.com>
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.mc_defaults

param set-default IMU_GYRO_CUTOFF 30

param set-default MC_ROLLRATE_P 0.14
param set-default MC_PITCHRATE_P 0.14
param set-default MC_ROLLRATE_I 0.3
param set-default MC_PITCHRATE_I 0.3
param set-default MC_ROLLRATE_D 0.004
param set-default MC_PITCHRATE_D 0.004

# Square quadrotor X PX4 numbering
param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 1
param set-default CA_ROTOR0_PY 1
param set-default CA_ROTOR1_PX -1
param set-default CA_ROTOR1_PY -1
param set-default CA_ROTOR2_PX 1
param set-default CA_ROTOR2_PY -1
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -1
param set-default CA_ROTOR3_PY 1
param set-default CA_ROTOR3_KM -0.05

# INDI rate control
param set-default METRIC_ROTOR_COUNT 4
param set-default METRIC_ROTOR0_PX 0.174
param set-default METRIC_ROTOR0_PY -0.174
param set-default METRIC_ROTOR0_CT 8.54858e-06
param set-default METRIC_ROTOR0_KM 0.016
param set-default METRIC_ROTOR0_IZZ 2.649858234714004e-05
param set-default METRIC_ROTOR1_PX -0.174
param set-default METRIC_ROTOR1_PY 0.174
param set-default METRIC_ROTOR1_CT 8.54858e-06
param set-default METRIC_ROTOR1_KM 0.016
param set-default METRIC_ROTOR1_IZZ 2.649858234714004e-05
param set-default METRIC_ROTOR2_PX 0.174
param set-default METRIC_ROTOR2_PY 0.174
param set-default METRIC_ROTOR2_CT 8.54858e-06
param set-default METRIC_ROTOR2_KM -0.016
param set-default METRIC_ROTOR2_IZZ 2.649858234714004e-05
param set-default METRIC_ROTOR3_PX -0.174
param set-default METRIC_ROTOR3_PY -0.174
param set-default METRIC_ROTOR3_CT 8.54858e-06
param set-default METRIC_ROTOR3_KM -0.016
param set-default METRIC_ROTOR3_IZZ 2.649858234714004e-05
