#!/bin/sh
#
# @name BetaFPV Beta75X 2S Brushless Whoop
#
# @type Quadrotor H
# @class Copter
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
#
# @maintainer Beat Kueng <beat-kueng@gmx.net>
#
# @board px4_fmu-v2 exclude
# @board px4_fmu-v3 exclude
# @board px4_fmu-v4 exclude
# @board px4_fmu-v4pro exclude
# @board px4_fmu-v5 exclude
# @board px4_fmu-v5x exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.mc_defaults

param set-default CBRK_SUPPLY_CHK 894281
param set-default CBRK_USB_CHK 197848

param set-default IMU_GYRO_CUTOFF 100
param set-default IMU_DGYRO_CUTOFF 60

param set-default MC_AIRMODE 2
param set-default MC_PITCHRATE_D 0.001
param set-default MC_PITCHRATE_I 0.5
param set-default MC_PITCHRATE_MAX 600
param set-default MC_PITCHRATE_P 0.075
param set-default MC_PITCH_P 6
param set-default MC_ROLLRATE_D 0.001
param set-default MC_ROLLRATE_I 0.4
param set-default MC_ROLLRATE_MAX 600
param set-default MC_ROLLRATE_P 0.075
param set-default MC_YAWRATE_I 0.3
param set-default MC_YAWRATE_MAX 400
param set-default MC_YAWRATE_P 0.12
param set-default MC_YAW_P 4

param set-default MPC_MANTHR_MIN 0
param set-default MPC_MAN_TILT_MAX 60

param set-default MOT_ORDERING 1
param set-default DSHOT_CONFIG 600

param set-default SYS_HAS_BARO 0
param set-default SYS_HAS_MAG 0

param set-default BAT1_N_CELLS 2
# The Whoop uses reversed props
set MIXER quad_h
