#!/bin/sh
#
# @name Spedix S250AQ
# @url https://docs.px4.io/en/framebuild_multicopter/spedix_s250_pixracer.html
#
# @type Quadrotor asymmetric
# @class Copter
#
# @output MAIN1 motor1 (front right: CCW)
# @output MAIN2 motor2 (back left: CCW)
# @output MAIN3 motor3 (front left: CW)
# @output MAIN4 motor4 (back right: CW)
#
# @output MAIN5 feed-through of RC AUX1 channel
# @output MAIN6 feed-through of RC AUX2 channel
#
# @maintainer Lorenz Meier <lorenz@px4.io>
#
# @board px4_fmu-v2 exclude
# @board intel_aerofc-v1 exclude
# @board bitcraze_crazyflie exclude
#

sh /etc/init.d/rc.mc_defaults

set MIXER quad_s250aq
set MAV_TYPE 2

set PWM_OUT 1234

param import-as-default /etc/init.d/4051.params
