#!/bin/sh
#
# @name Spedix S250AQ
# @url https://docs.px4.io/master/en/frames_multicopter/spedix_s250_pixracer.html
#
# @type Quadrotor asymmetric
# @class Copter
#
# @output MAIN1 motor1 (front right: CCW)
# @output MAIN2 motor2 (back left: CCW)
# @output MAIN3 motor3 (front left: CW)
# @output MAIN4 motor4 (back right: CW)
#
# @output MAIN5 feed-through of RC AUX1 channel
# @output MAIN6 feed-through of RC AUX2 channel
#
# @maintainer Lorenz Meier <lorenz@px4.io>
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.mc_defaults

set MIXER quad_s250aq
set MAV_TYPE 2

set PWM_OUT 1234


param set-default ATT_BIAS_MAX 0

param set-default CBRK_IO_SAFETY 22027

param set-default MC_ROLL_P 8
param set-default MC_ROLLRATE_P 0.19
param set-default MC_ROLLRATE_I 0.1
param set-default MC_ROLLRATE_D 0.0055
param set-default MC_PITCH_P 8
param set-default MC_PITCHRATE_P 0.19
param set-default MC_PITCHRATE_I 0.1
param set-default MC_PITCHRATE_D 0.0055
param set-default MC_YAW_P 4
param set-default MC_YAWRATE_P 0.2
param set-default MC_YAWRATE_I 0.1
param set-default MC_YAWRATE_D 0
param set-default MC_ROLLRATE_MAX 720
param set-default MC_PITCHRATE_MAX 720
param set-default MC_YAWRATE_MAX 400
param set-default MC_ACRO_R_MAX 360
param set-default MC_ACRO_P_MAX 360

param set-default MPC_THR_MIN 0.06
param set-default MPC_MANTHR_MIN 0.06

param set-default PWM_MAIN_MIN 1075
