#!/bin/sh
#
# @name Intel Aero Ready to Fly Drone
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Beat Kueng <beat@px4.io>
#
# @board px4_fmu-v2 exclude
# @board px4_fmu-v3 exclude
# @board px4_fmu-v4 exclude
# @board px4_fmu-v4pro exclude
# @board px4_fmu-v5 exclude
# @board px4_fmu-v5x exclude
# @board bitcraze_crazyflie exclude
#

sh /etc/init.d/rc.mc_defaults

#
# Load default params for this platform
#
param import-as-default /etc/init.d/4070.params

if param compare SYS_HITL 0
then
  tap_esc start -d /dev/ttyS0 -n 4
  usleep 300000

  set OUTPUT_MODE tap_esc
fi

set MIXER quad_x
set USE_IO no

