#!/bin/sh
#
# @name ZMR250 Racer
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Anton Matosov <anton.matosov@gmail.com>
#

. ${R}etc/init.d/rc.mc_defaults

param set-default MC_ROLL_P 2.2
param set-default MC_ROLLRATE_P 0.06
param set-default MC_ROLLRATE_D 0.0017

param set-default MC_PITCH_P 2.2
param set-default MC_PITCHRATE_P 0.06
param set-default MC_PITCHRATE_D 0.0017

param set-default MC_YAW_P 1
param set-default MC_YAWRATE_P 0.15
param set-default MC_YAWRATE_I 0.2

param set-default MC_ACRO_R_MAX 1000
param set-default MC_ACRO_P_MAX 1000
param set-default MC_ACRO_Y_MAX 1000
