#!/bin/sh
#
# @name NanoMind 110 Quad
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Henry Zhang <zhanghui629@gmail.com>
#
# @board px4_fmu-v2 exclude
# @board px4_fmu-v3 exclude
# @board px4_fmu-v4pro exclude
# @board px4_fmu-v5 exclude
# @board px4_fmu-v5x exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.mc_defaults

set MIXER quad_x

param set-default BAT_N_CELLS 1

param set-default MC_ROLL_P 8
param set-default MC_ROLLRATE_P 0.19
param set-default MC_ROLLRATE_I 0.1
param set-default MC_ROLLRATE_D 0.0055
param set-default MC_PITCH_P 8
param set-default MC_PITCHRATE_P 0.19
param set-default MC_PITCHRATE_I 0.1
param set-default MC_PITCHRATE_D 0.0055
param set-default MC_YAW_P 4
param set-default MC_YAWRATE_P 0.2
param set-default MC_YAWRATE_I 0.1
param set-default MC_YAWRATE_D 0

param set-default PWM_MAIN_DIS1 0
param set-default PWM_MAIN_DIS2 0
param set-default PWM_MAIN_DIS3 0
param set-default PWM_MAIN_DIS4 0

param set-default PWM_MAIN_MIN1 500
param set-default PWM_MAIN_MIN2 500
param set-default PWM_MAIN_MIN3 500
param set-default PWM_MAIN_MIN4 500

param set-default PWM_MAIN_MAX1 2200
param set-default PWM_MAIN_MAX2 2200
param set-default PWM_MAIN_MAX3 2200
param set-default PWM_MAIN_MAX4 2200
