#!/bin/sh
#
# @name NanoMind 110 Quad
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Henry Zhang <zhanghui629@gmail.com>
#
# @board px4_fmu-v2 exclude
# @board px4_fmu-v3 exclude
# @board px4_fmu-v4pro exclude
# @board px4_fmu-v5 exclude
# @board px4_fmu-v5x exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.mc_defaults

param set-default BAT1_N_CELLS 1

param set-default MC_ROLL_P 8
param set-default MC_ROLLRATE_P 0.19
param set-default MC_ROLLRATE_I 0.1
param set-default MC_ROLLRATE_D 0.0055
param set-default MC_PITCH_P 8
param set-default MC_PITCHRATE_P 0.19
param set-default MC_PITCHRATE_I 0.1
param set-default MC_PITCHRATE_D 0.0055
param set-default MC_YAW_P 4

param set-default PWM_MAIN_DISARM 0
param set-default PWM_MAIN_MIN 500
param set-default PWM_MAIN_MAX 2200
