#!/bin/sh
#
# @name SSRC Quad X on holybro x500 frame
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Jukka Laitinen <jukkax@ssrc.tii.ae>
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. /etc/init.d/rc.mc_defaults

set MIXER quad_x
set PWM_OUT 1234

if [ $AUTOCNF = yes ]
then
	# Default rates
	param set IMU_GYRO_CUTOFF 60
	param set IMU_DGYRO_CUTOFF 30
	param set MC_ROLLRATE_P 0.14
	param set MC_PITCHRATE_P 0.14
	param set MC_ROLLRATE_I 0.3
	param set MC_PITCHRATE_I 0.3
	param set MC_ROLLRATE_D 0.004
	param set MC_PITCHRATE_D 0.004

	# Battery parameters
	param set BAT_N_CELLS 4
	param set BAT_V_CHARGED 4.2
	param set BAT_V_EMPTY 3.6
	param set BAT_V_DIV 18.1

	# RTPS/MAV on TELEMETRY 1
	param set MAV_0_CONFIG 0
	param set RTPS_MAV_CONFIG 101
	param set SER_TEL1_BAUD 1000000

	# Enable LL40LS in i2c
	param set SENS_EN_LL40LS 2

	# LEDs on TELEMETRY 2
	param set SER_TEL2_BAUD 57600
	param set MAV_1_CONFIG 102
	param set MAV_1_MODE 7
	param set MAV_1_RATE 1000

	# Disable multi ekf for now
	param set EKF2_MULTI_IMU 0
	param set SENS_IMU_MODE 1
	param set EKF2_MULTI_MAG 0
	param set SENS_MAG_MODE 1

	# Set battery load drop value to match
	# the "default" battery used in this drone
	param set BAT_V_LOAD_DROP 0.1

	# Enable safety switch
	param set CBRK_IO_SAFETY 0
fi
