#!/bin/sh
#
# @name SSRC Quad X on holybro x500 frame
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Jukka Laitinen <jukkax@ssrc.tii.ae>
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. /etc/init.d/rc.mc_defaults

set MIXER quad_x
set PWM_OUT 1234

# Default rates
param set-default IMU_GYRO_CUTOFF 60
param set-default IMU_DGYRO_CUTOFF 30
param set-default MC_ROLLRATE_P 0.14
param set-default MC_PITCHRATE_P 0.14
param set-default MC_ROLLRATE_I 0.3
param set-default MC_PITCHRATE_I 0.3
param set-default MC_ROLLRATE_D 0.004
param set-default MC_PITCHRATE_D 0.004

# Increase velocity controller P gain
param set-default MPC_XY_VEL_P_ACC 2.4

# Battery parameters
param set-default BAT1_N_CELLS 4
param set-default BAT1_V_CHARGED 4.2
param set-default BAT1_V_EMPTY 3.6
param set-default BAT1_V_DIV 18.1

# Enable ethernet for PX4<->MC
param set-default RTPS_MAV_CONFIG 0

# Enable LL40LS in i2c
param set-default SENS_EN_LL40LS 2

# LEDs on TELEMETRY 1
param set-default SER_TEL1_BAUD 57600
param set-default MAV_1_CONFIG 101
param set-default MAV_1_MODE 7
param set-default MAV_1_RATE 1000

# Disable MAV_0 and MAV_2
param set-default MAV_0_CONFIG 0
param set-default MAV_2_CONFIG 0

# Enable safety switch
param set-default CBRK_IO_SAFETY 0

# Set default for disarm after land to 4s
param set-default COM_DISARM_LAND 4.0

# Enable satellite info by default
param set-default GPS_SAT_INFO 1

# Set sticks movement not to switch to RC, we use mode switch for this
param set-default COM_RC_OVERRIDE 0

# Set takeoff ramp to disabled for a more decisive takeoff action
param set-default MPC_TKO_RAMP_T 0
