#!/bin/sh
#
# @name Generic Quadcopter (450mm)
#
# @type Quadrotor x
# @class Copter
#

sh /etc/init.d/rc.mc_defaults

if [ $AUTOCNF = yes ]
then

	# This file is currently a placeholder to be populated with
	# appropritate values for this size airframe.

fi

set MIXER quad_x
