#!/bin/sh
#
# @name COEX Clover 4
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Oleg Kalachev <okalachev@gmail.com>
#
# @board px4_fmu-v2 exclude
# @board intel_aerofc-v1 exclude
# @board bitcraze_crazyflie exclude
#

sh /etc/init.d/rc.mc_defaults

set MIXER quad_x
set PWM_OUT 1234

param import-airframe /etc/init.d