#!/bin/sh
#
# @name COEX Clover 4
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Oleg Kalachev <okalachev@gmail.com>
#
# @board px4_fmu-v2 exclude
# @board intel_aerofc-v1 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.mc_defaults

set MIXER quad_x
set PWM_OUT 1234

if [ $AUTOCNF = yes ]
then
	param set MC_PITCHRATE_P 0.087
	param set MC_PITCHRATE_I 0.037
	param set MC_PITCHRATE_D 0.0044
	param set MC_PITCH_P 8.5
	param set MC_ROLLRATE_P 0.087
	param set MC_ROLLRATE_I 0.037
	param set MC_ROLLRATE_D 0.0044
	param set MC_ROLL_P 8.5
	param set MPC_XY_VEL_P_ACC 2.2
	param set MPC_XY_VEL_D_ACC 0.26
	param set MPC_XY_P 1.1
	param set MPC_Z_VEL_P_ACC 4.8
	param set MPC_Z_P 1.2
fi
