#!/bin/sh
#
# @name Crazyflie 2
#
# @type Quadrotor x
# @class Copter
#
# @maintainer Dennis Shtatov <densht@gmail.com>
#
# @board px4_fmu-v2 exclude
# @board px4_fmu-v3 exclude
# @board px4_fmu-v4 exclude
# @board px4_fmu-v4pro exclude
# @board px4_fmu-v5 exclude
# @board px4_fmu-v5x exclude
# @board intel_aerofc-v1 exclude
#
sh /etc/init.d/rc.mc_defaults

set MIXER quad_x_cw
set PWM_OUT 1234


param import-airframe /etc/init.d

set PWM_DISARMED none
set PWM_MAX none
set PWM_MIN none

syslink start
mavlink start -d /dev/bridge0 -b 57600 -m osd -r 40000

