#!/bin/sh
#
# @name SSRC BUNKER UGV
#
# @url https://global.agilex.ai/products/bunker
#
# @type Rover
# @class Rover
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.rover_defaults

param set-default RI_ROVER_TYPE 5
param set-default RI_MAN_THR_MAX 1.5

# Battery setting
param set-default BAT1_N_CELLS 14
param set-default BAT1_V_EMPTY 3.3
param set-default BAT1_V_CHARGED 4.2

# EKF2
param set-default EKF2_GBIAS_INIT 0.01
param set-default EKF2_ANGERR_INIT 0.01
param set-default EKF2_MAG_TYPE 1
param set-default EKF2_REQ_SACC 1.0
param set-default EKF2_REQ_VDRIFT 0.4
param set-default EKF2_REQ_HDRIFT 0.2


param set-default FW_AIRSPD_MIN 0
param set-default FW_AIRSPD_TRIM 1
param set-default FW_AIRSPD_MAX 3

param set-default GND_SP_CTRL_MODE 1
param set-default GND_L1_DIST 5
param set-default GND_L1_PERIOD 3
param set-default GND_THR_CRUISE 1
param set-default GND_THR_MAX 1

# Because this is differential drive, it can make a turn with radius 0.
# This corresponds to a turn angle of pi radians.
# If a special case is made for differential-drive, this will need to change.
param set-default GND_MAX_ANG 3.142
param set-default GND_WHEEL_BASE 0.778

# TODO: Set to -1.0, to allow reversing. This will require many changes in the codebase
# to support negative throttle.
param set-default GND_THR_MIN 0
param set-default GND_SPEED_P 0.4
param set-default GND_SPEED_I 1
param set-default GND_SPEED_D 0.001
param set-default GND_SPEED_IMAX 1
param set-default GND_SPEED_MAX 1
param set-default GND_SPEED_THR_SC 1

param set-default MIS_TAKEOFF_ALT 0.01

param set-default NAV_ACC_RAD 0.5     # reached when within 0.5m of waypoint

# Enable Airspeed check circuit breaker because Rovers will have no airspeed sensor
param set-default CBRK_AIRSPD_CHK 162128

# Set geometry & output configration. This is just the place holder for rover type. We dont actually use control allocation for scout mini.
param set-default CA_AIRFRAME 6

# Disable UAVCAN since rover use rover_interface module instead
param set UAVCAN_ENABLE 0


###### ROVER/DRONE COMMON PARAMS ######
# Disable internal magnetometer
param set-default CAL_MAG0_PRIO 0

# LEDs on TELEMETRY 1
param set-default SER_TEL1_BAUD 57600
param set-default MAV_1_CONFIG 101
param set-default MAV_1_MODE 7
param set-default MAV_1_RATE 1000

# Disable MAV_0 and MAV_2
param set-default MAV_0_CONFIG 0
param set-default MAV_2_CONFIG 0

# Enable safety switch
param set-default CBRK_IO_SAFETY 0

# Enable satellite info by default
param set-default GPS_SAT_INFO 1

# Set sticks movement not to switch to RC, we use mode switch for this
param set-default COM_RC_OVERRIDE 0

# Set default logfile encryption key indecies
param set-default SDLOG_EXCH_KEY 2
param set-default SDLOG_KEY 3
