#!/bin/sh
#
# @name Generic Ground Vehicle
#
# @type Rover
# @class Rover
#
# @board px4_fmu-v2 exclude
#
# @output MAIN2 steering
# @output MAIN4 throttle
#
# @maintainer
#
# @board px4_fmu-v2 exclude
# @board intel_aerofc-v1 exclude
# @board bitcraze_crazyflie exclude
#

sh /etc/init.d/rc.rover_defaults

param import-as-default /etc/init.d/50000.params

# Configure this as rover
set MAV_TYPE 10

# Set mixer
set MIXER rover_generic

set PWM_MAIN_REV2 1
