#!/bin/sh
#
# @name Hiwonder Tracked
#
# @url https://www.hiwonder.com/products/suspended-shock-absorbing-tracked-chassis?variant=40378709835863
#
# @type Rover
# @class Rover
#

. ${R}etc/init.d/rc.rover_differential_defaults

param set-default HIWONDER_EMM_EN 1 # Enable motor driver
param set-default BAT1_N_CELLS 3
param set-default NAV_ACC_RAD 0.5

# Differential Parameters
param set-default RD_WHEEL_TRACK 0.16
param set-default RD_TRANS_DRV_TRN 0.785398
param set-default RD_TRANS_TRN_DRV 0.0872665

# Rover Rate Control Parameters
param set-default RO_YAW_EXPO 0.2
param set-default RO_YAW_SUPEXPO 0.1
param set-default RO_YAW_RATE_I 0.1
param set-default RO_YAW_RATE_P 0.1
param set-default RO_YAW_RATE_LIM 140

# Rover Attitude Control Parameters
param set-default RO_YAW_P 5

# Rover Velocity Control Parameters
param set-default RO_ACCEL_LIM 1
param set-default RO_DECEL_LIM 1
param set-default RO_JERK_LIM 10
param set-default RO_MAX_THR_SPEED 0.3
param set-default RO_SPEED_LIM 0.28
param set-default RO_SPEED_I 0.05
param set-default RO_SPEED_P 0.1
param set-default RO_SPEED_RED 1

# Pure Pursuit parameters
param set-default PP_LOOKAHD_GAIN 1
param set-default PP_LOOKAHD_MAX 10
param set-default PP_LOOKAHD_MIN 1
