#!/bin/sh
#
# @name SimLE SeaSentinel ASV Perkoz
#
# @type Rover
# @class Rover
#
# @output Motor1 motor 1 CCW, bow starboard horizontal, , propeller CCW
# @output Motor2 motor 2 CCW, bow port horizontal, propeller CCW
# @output Motor3 motor 3 CCW, stern starboard horizontal, propeller CW
# @output Motor4 motor 4 CCW, stern port horizontal, propeller CW
#
# @maintainer Norbert Szulc
# @maintainer Jakub Wilk
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.sese_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=ocean}

# disable circuit breaker for airspeed sensor
param set-default CBRK_AIRSPD_CHK 162128
# companion computer is connected via USB permanently
param set-default CBRK_USB_CHK 197848
param set-default CBRK_IO_SAFETY 22027

param set-default MAV_1_CONFIG 102

param set-default SIM_GZ_EN 1

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 0
param set-default SENS_EN_MAGSIM 1

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

param set-default CA_R_REV 255

param set-default CA_ROTOR0_PX 0.13
param set-default CA_ROTOR0_PY 0.22
param set-default CA_ROTOR0_KM  0.05
param set-default CA_ROTOR0_AX -1.0000
param set-default CA_ROTOR0_AY 1.0000

param set-default CA_ROTOR1_PX 0.13
param set-default CA_ROTOR1_PY -0.22
param set-default CA_ROTOR1_KM  -0.05
param set-default CA_ROTOR1_AX -1.0000
param set-default CA_ROTOR1_AY -1.0000

param set-default CA_ROTOR2_PX -0.13
param set-default CA_ROTOR2_PY 0.22
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR2_AX 1.0000
param set-default CA_ROTOR2_AY 1.0000

param set-default CA_ROTOR3_PX -0.13
param set-default CA_ROTOR3_PY -0.22
param set-default CA_ROTOR3_KM 0.05
param set-default CA_ROTOR3_AX 1.0000
param set-default CA_ROTOR3_AY -1.0000

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150

param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000

param set-default MPC_THR_HOVER 0.60

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
