#!/bin/sh
#
# @name Generic Underwater Robot
#
# @type Underwater Robot
# @class Underwater Robot
#
# @maintainer
#
# @board px4_fmu-v2 exclude
# @board intel_aerofc-v1 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.uuv_defaults

if [ $AUTOCNF = yes ]
then
	#Set data link loss failsafe mode (0: disabled)
	param set NAV_DLL_ACT 0

	# disable circuit breaker for airspeed sensor
	param set CBRK_AIRSPD_CHK 162128

	#param set CBRK_GPSFAIL 240024
fi

set MAV_TYPE 12
param set MAV_TYPE ${MAV_TYPE}

set MIXER uuv_x
