#!/bin/sh
#
# @name Robosub UUV (Unmanned Underwater Vehicle)
#
# @type Underwater Robot
# @class Underwater Robot
#
# @maintainer
#
# @board px4_fmu-v2 exclude
#



set VEHICLE_TYPE uuv

# MAV_TYPE_SUBMARINE 12
param set-default MAV_TYPE 12


param set-default SER_TEL1_BAUD 115200

param set-default CA_AIRFRAME 7
param set-default CA_ROTOR_COUNT 4
param set-default CA_R_REV 255
param set-default CA_ROTOR0_AX 1
param set-default CA_ROTOR0_AY 0
param set-default CA_ROTOR0_AZ 0
param set-default CA_ROTOR0_KM 0
param set-default CA_ROTOR0_PX 0
param set-default CA_ROTOR0_PY -0.3
param set-default CA_ROTOR0_PZ -0.3
param set-default CA_ROTOR1_AX 1
param set-default CA_ROTOR1_AY 0
param set-default CA_ROTOR1_AZ 0
param set-default CA_ROTOR1_KM 0
param set-default CA_ROTOR1_PX 0
param set-default CA_ROTOR1_PY 0.3
param set-default CA_ROTOR1_PZ -0.3
param set-default CA_ROTOR2_AX 1
param set-default CA_ROTOR2_AY 0
param set-default CA_ROTOR2_AZ 0
param set-default CA_ROTOR2_KM 0
param set-default CA_ROTOR2_PX 0
param set-default CA_ROTOR2_PY 0.3
param set-default CA_ROTOR2_PZ 0.3
param set-default CA_ROTOR3_AX 1
param set-default CA_ROTOR3_AY 0
param set-default CA_ROTOR3_AZ 0
param set-default CA_ROTOR3_KM 0
param set-default CA_ROTOR3_PX 0
param set-default CA_ROTOR3_PY -0.3
param set-default CA_ROTOR3_PZ 0.3

param set-default PWM_OUT_W_MAX 0.2
param set-default PWM_ON_W_MAX 0.2
param set-default PWM_IN_W_MAX 1.0

param set-default PWM_MAIN_FUNC1 101

param set-default EKF2_EV_CTRL 4

param set-default UXRCE_DDS_CFG 1
param set-default UXRCE_DDS_AG_IP -1856423239
param set-default UXRCE_DDS_PRT 8888

param set-default SENS_EN_INA228 1

rs_motor_control start
rs_remote_control start
control_allocator start
land_detector start rover
rs_canfd_socket start
rs_canfd_receiver start
rs_canfd_sender start








































































