#!/bin/sh
#
# @name Robosub UUV (Unmanned Underwater Vehicle)
#
# @type Underwater Robot
# @class Underwater Robot
#
# @maintainer
#
# @board px4_fmu-v2 exclude
#



set VEHICLE_TYPE uuv

# MAV_TYPE_SUBMARINE 12
param set-default MAV_TYPE 12


param set-default SER_TEL1_BAUD 115200

param set-default CA_AIRFRAME 7
param set-default CA_ROTOR_COUNT 4
param set-default CA_R_REV 255
param set-default CA_ROTOR0_AX 1
param set-default CA_ROTOR0_AY 0
param set-default CA_ROTOR0_AZ 0
param set-default CA_ROTOR0_KM 0
param set-default CA_ROTOR0_PX 0
param set-default CA_ROTOR0_PY -0.3
param set-default CA_ROTOR0_PZ -0.3
param set-default CA_ROTOR1_AX 1
param set-default CA_ROTOR1_AY 0
param set-default CA_ROTOR1_AZ 0
param set-default CA_ROTOR1_KM 0
param set-default CA_ROTOR1_PX 0
param set-default CA_ROTOR1_PY 0.3
param set-default CA_ROTOR1_PZ -0.3
param set-default CA_ROTOR2_AX 1
param set-default CA_ROTOR2_AY 0
param set-default CA_ROTOR2_AZ 0
param set-default CA_ROTOR2_KM 0
param set-default CA_ROTOR2_PX 0
param set-default CA_ROTOR2_PY 0.3
param set-default CA_ROTOR2_PZ 0.3
param set-default CA_ROTOR3_AX 1
param set-default CA_ROTOR3_AY 0
param set-default CA_ROTOR3_AZ 0
param set-default CA_ROTOR3_KM 0
param set-default CA_ROTOR3_PX 0
param set-default CA_ROTOR3_PY -0.3
param set-default CA_ROTOR3_PZ 0.3
param set-default PWM_MAIN_OUT 1234  # Enable channels 1-4 for PWM
param set-default PWM_MAIN_RATE 400  # Set PWM frequency to 400 Hz
param set-default PWM_MAIN_DISARM 1500  # Stop (neutral) when disarmed
param set-default PWM_MAIN_MIN 1100     # Minimum PWM value (full reverse)
param set-default PWM_MAIN_MAX 1900     # Maximum PWM value (full forward)

param set-default PWM_MAIN_FUNC1 101

rs_motor_control start
rs_remote_control start
control_allocator start
land_detector start rover
