#!/bin/sh
#
# @name HippoCampus UUV (Unmanned Underwater Vehicle)
#
# @type Underwater Robot
# @class Underwater Robot
#
# @maintainer Daniel Duecker <daniel.duecker@tuhh.de>
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.uuv_defaults

# disable circuit breaker for airspeed sensor
param set-default CBRK_AIRSPD_CHK 162128

set MIXER uuv_x
