#!/bin/sh
#
# @name BlueROV2 (Heavy Configuration)
#
# @type Vectored 6 DOF UUV
# @class Underwater Robot
#
# @maintainer Thies Lennart Alff <thies.lennart.alff@tuhh.de>
#
# @board px4_fmu-v2 exclude
# @board intel_aerofc-v1 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.uuv_defaults

if [ $AUTOCNF = yes ]
then
	#Set data link loss failsafe mode (0: disabled)
	param set NAV_DLL_ACT 0

	# disable circuit breaker for airspeed sensor
	set CBRK_AIRSPD_CHK 162128
	set CBRK_USB_CHK 197848
	set CBRK_IO_SAFETY 22027
	param set CBRK_AIRSPD_CHK ${CBRK_AIRSPD_CHK}
	param set CBRK_USB_CHK ${CBRK_USB_CHK}
	param set CBRK_IO_SAFETY ${CBRK_IO_SAFETY}

	param set COM_PREARM_MODE 0

	param set MAV_1_CONFIG 102

	param set BAT1_A_PER_V 37.8798
	param set BAT1_CAPACITY 18000
	param set BAT1_V_DIV 11.0
	param set BAT1_N_CELLS 4
	param set BAT_V_OFFS_CURR 0.33
fi

set MAV_TYPE 12
param set MAV_TYPE ${MAV_TYPE}
set PWM_OUT 12345678
# set MIXER IO_pass
set MIXER vectored6dof

