#!/bin/sh
#
# @name KTH Space Robot
#
# @type Space Robot
# @class 2D Space Robot
#
# @maintainer DISCOWER
#

. ${R}etc/init.d/rc.sc_defaults

# param set-default CA_AIRFRAME 7
# param set-default CA_ROTOR_COUNT 8

# param set-default CA_ROTOR0_PX -0.12
# param set-default CA_ROTOR0_PY -0.12

# param set-default CA_ROTOR1_PX 0.12
# param set-default CA_ROTOR1_PY -0.12

# param set-default CA_ROTOR2_PX -0.12
# param set-default CA_ROTOR2_PY 0.12

# param set-default CA_ROTOR3_PX 0.12
# param set-default CA_ROTOR3_PY 0.12

# param set-default CA_ROTOR4_PX -0.12
# param set-default CA_ROTOR4_PY 0.12

# param set-default CA_ROTOR5_PX -0.12
# param set-default CA_ROTOR5_PY -0.12

# param set-default CA_ROTOR6_PX 0.12
# param set-default CA_ROTOR6_PY 0.12

# param set-default CA_ROTOR7_PX 0.12
# param set-default CA_ROTOR7_PY -0.12

param set-default PWM_AUX_TIM0 10
param set-default PWM_AUX_TIM1 10
param set-default PWM_AUX_TIM2 10

param set-default PWM_AUX_FUNC1 101
param set-default PWM_AUX_FUNC2 102
param set-default PWM_AUX_FUNC3 103
param set-default PWM_AUX_FUNC4 104
param set-default PWM_AUX_FUNC5 105
param set-default PWM_AUX_FUNC6 106
param set-default PWM_AUX_FUNC7 107
param set-default PWM_AUX_FUNC8 108

param set-default PWM_AUX_DIS1 0
param set-default PWM_AUX_DIS2 0
param set-default PWM_AUX_DIS3 0
param set-default PWM_AUX_DIS4 0
param set-default PWM_AUX_DIS5 0
param set-default PWM_AUX_DIS6 0
param set-default PWM_AUX_DIS7 0
param set-default PWM_AUX_DIS8 0

param set-default PWM_AUX_MIN1 0
param set-default PWM_AUX_MIN2 0
param set-default PWM_AUX_MIN3 0
param set-default PWM_AUX_MIN4 0
param set-default PWM_AUX_MIN5 0
param set-default PWM_AUX_MIN6 0
param set-default PWM_AUX_MIN7 0
param set-default PWM_AUX_MIN8 0

# BOARD_PWM_FREQ is downscaled by 10, thus PWM value is given in 10s of usec
param set-default PWM_AUX_MAX1 10000
param set-default PWM_AUX_MAX2 10000
param set-default PWM_AUX_MAX3 10000
param set-default PWM_AUX_MAX4 10000
param set-default PWM_AUX_MAX5 10000
param set-default PWM_AUX_MAX6 10000
param set-default PWM_AUX_MAX7 10000
param set-default PWM_AUX_MAX8 10000

