#!/bin/sh
#
# @name Omniquad
#
# @type Quadrotor
# @class Tilting Multirotor
#
# @maintainer Andrea Berra andrea.berra@outlook.com
#

. ${R}etc/init.d/rc.mc_defaults

param set-default CA_AIRFRAME 16
param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 0.15
param set-default CA_ROTOR0_PY 0.15
param set-default CA_ROTOR0_TILT 1
param set-default CA_ROTOR1_PX -0.15
param set-default CA_ROTOR1_PY -0.15
param set-default CA_ROTOR1_TILT 2
param set-default CA_ROTOR2_PX 0.15
param set-default CA_ROTOR2_PY -0.15
param set-default CA_ROTOR2_TILT 3
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -0.15
param set-default CA_ROTOR3_PY 0.15
param set-default CA_ROTOR3_TILT 4
param set-default CA_ROTOR3_KM -0.05

param set-default CA_SV_TL_COUNT 4
param set-default CA_SV0_SLEW 0.05
param set-default CA_SV1_SLEW 0.05
param set-default CA_SV2_SLEW 0.05
param set-default CA_SV3_SLEW 0.05
param set-default CA_SV_TL0_MINA -45
param set-default CA_SV_TL0_MAXA 45
param set-default CA_SV_TL1_MINA -45
param set-default CA_SV_TL1_MAXA 45
param set-default CA_SV_TL2_MINA -45
param set-default CA_SV_TL2_MAXA 45
param set-default CA_SV_TL3_MINA -45
param set-default CA_SV_TL3_MAXA 45

param set-default MC_MAN_XY_TAU 0.25
param set-default MC_YAWRATE_I 0.01
param set-default MC_YAWRATE_P 0.05
param set-default MC_YAW_P 0.2

param set-default MPC_ACT_MODE 1

param set-default PWM_AUX_FUNC1 104
param set-default PWM_AUX_FUNC2 103
param set-default PWM_AUX_FUNC3 102
param set-default PWM_AUX_FUNC4 101
param set-default PWM_MAIN_FUNC1 201
param set-default PWM_MAIN_FUNC2 202
param set-default PWM_MAIN_FUNC3 203
param set-default PWM_MAIN_FUNC4 204
