module_name: pwm_voltage
parameters:
- group: PWM Outputs
  definitions:
    PWM_LEVEL_CONT:
      description:
        short: Control PWM output voltage
        long: |-
          Enable:  PWM output voltage 5V
          Disable: PWM output voltage 3.3V
      type: boolean
      default: 0
      reboot_required: true
