module_name: sensor_agp_sim
parameters:
- group: Sensors
  definitions:
    SENS_EN_AGPSIM:
      description:
        short: Simulate Aux Global Position (AGP)
      type: enum
      values:
        0: Disabled
        1: Enabled
      default: 0
      reboot_required: true
      min: 0
      max: 1
- group: Simulator
  definitions:
    SIM_AGP_FAIL:
      description:
        short: AGP failure mode
        long: |-
          Stuck: freeze the measurement to the current location
          Drift: add a linearly growing bias to the sensor data
      type: bitmask
      bit:
        0: Stuck
        1: Drift
      default: 0
      min: 0
      max: 3
