/*
 * I2C busses
 */
#define PX4_I2C_BUS_ESC		1
#define PX4_SIM_BUS_TEST	2
#define PX4_I2C_BUS_EXPANSION	3
#define PX4_I2C_BUS_LED		3

#define PX4_I2C_OBDEV_LED	0x55

#define BOARD_OVERRIDE_UUID "SIMULATIONID"
#define BOARD_HAS_NO_RESET
#define BOARD_HAS_NO_BOOTLOADER
