#include <systemlib/param/param.h>

/*PARAM_DEFINE_FLOAT(NAME,0.0f);*/
PARAM_DEFINE_FLOAT(KF_V_GYRO, 0.1f);
PARAM_DEFINE_FLOAT(KF_V_ACCEL, 0.1f);
PARAM_DEFINE_FLOAT(KF_R_MAG, 0.1f);
PARAM_DEFINE_FLOAT(KF_R_GPS_VEL, 0.1f);
PARAM_DEFINE_FLOAT(KF_R_GPS_POS, 5.0f);
PARAM_DEFINE_FLOAT(KF_R_GPS_ALT, 5.0f);
PARAM_DEFINE_FLOAT(KF_R_ACCEL, 0.1f);
PARAM_DEFINE_FLOAT(KF_FAULT_POS, 1.0f);
PARAM_DEFINE_FLOAT(KF_FAULT_ATT, 1.0f);
PARAM_DEFINE_FLOAT(KF_ENV_G, 9.806f);
PARAM_DEFINE_FLOAT(KF_ENV_MAG_DIP, 60.0f);
PARAM_DEFINE_FLOAT(KF_ENV_MAG_DEC, 0.0f);

