#include <systemlib/param/param.h>

/*PARAM_DEFINE_FLOAT(NAME,0.0f);*/
PARAM_DEFINE_FLOAT(KF_V_GYRO, 0.1f);
PARAM_DEFINE_FLOAT(KF_V_ACCEL, 0.1f);
PARAM_DEFINE_FLOAT(KF_R_MAG, 0.1f);
PARAM_DEFINE_FLOAT(KF_R_GPS_VEL, 0.1f);
PARAM_DEFINE_FLOAT(KF_R_GPS_POS, 0.1f);
PARAM_DEFINE_FLOAT(KF_R_GPS_ALT, 10.0f);
PARAM_DEFINE_FLOAT(KF_R_ACCEL, 0.1f);
