#!/usr/bin/env bash

set -euo pipefail

CCACHE_TEMPDIR="/tmp/ccache-tmp"
CCACHE_DIR="/tmp/.ccache"

log() { printf "[ccache-setup] %s\n" "$*"; }

log "Creating ccache directories: ${CCACHE_TEMPDIR}, ${CCACHE_DIR}"
mkdir -p "${CCACHE_TEMPDIR}" "${CCACHE_DIR}"
chmod 700 "${CCACHE_TEMPDIR}" "${CCACHE_DIR}" || true

log "Done. Add the following to your shell rc (e.g. ~/.bashrc):"
cat <<EOF

# ccache paths (generated by scripts/setup_ccache.sh)
export CCACHE_TEMPDIR=${CCACHE_TEMPDIR}
export CCACHE_DIR=${CCACHE_DIR}
EOF

log "After reloading your shell, builds will avoid /run/user/... permissions issues."
