#!/bin/sh
#
# @name 3DR Iris Quadrotor SITL
#
# @type Quadrotor Wide
#
# @maintainer Julian Oes <julian@oes.ch>
#

sh /etc/init.d/rc.mc_defaults

if [ $AUTOCNF = yes ]
then
	param set VM_INERTIA_XX 0.0083
	param set VM_INERTIA_YY 0.0083
	param set VM_INERTIA_ZZ 0.0286

	param set CA_AIRFRAME 0
	param set CA_ACT0_MIN 0.0
	param set CA_ACT1_MIN 0.0
	param set CA_ACT2_MIN 0.0
	param set CA_ACT3_MIN 0.0
	param set CA_ACT0_MAX 1.0
	param set CA_ACT1_MAX 1.0
	param set CA_ACT2_MAX 1.0
	param set CA_ACT3_MAX 1.0

	param set CA_MC_R0_PX 0.1515
	param set CA_MC_R0_PY 0.245
	param set CA_MC_R0_CT 5.0
	param set CA_MC_R1_PX -0.1515
	param set CA_MC_R1_PY -0.1875
	param set CA_MC_R1_CT 5.0
	param set CA_MC_R2_PX 0.1515
	param set CA_MC_R2_PY -0.245
	param set CA_MC_R2_CT 5.0
	param set CA_MC_R3_PX -0.1515
	param set CA_MC_R3_PY 0.1875
	param set CA_MC_R3_CT 5.0

fi

# set MIXER quad_w
set MIXER direct

