#!/bin/sh
#
# @name 3DR Iris Quadrotor SITL
#
# @type Quadrotor Wide
#
# @maintainer Julian Oes <julian@oes.ch>
#

sh /etc/init.d/rc.mc_defaults

if [ $AUTOCNF = yes ]
then
	param set MC_ROLLRATE_P 18.0
	param set MC_ROLLRATE_D 0.36
	param set MC_PITCHRATE_P 18.0
	param set MC_PITCHRATE_D 0.36
	param set MC_YAWRATE_P 7.0
	param set MC_YAWRATE_D 0.0

	param set VM_INERTIA_XX 0.0083
	param set VM_INERTIA_YY 0.0083
	param set VM_INERTIA_ZZ 0.0286

	param set CA_AIRFRAME 0
	param set CA_ACT0_MIN 0.0
	param set CA_ACT1_MIN 0.0
	param set CA_ACT2_MIN 0.0
	param set CA_ACT3_MIN 0.0
	param set CA_ACT0_MAX 1.0
	param set CA_ACT1_MAX 1.0
	param set CA_ACT2_MAX 1.0
	param set CA_ACT3_MAX 1.0
fi
# set MIXER quad_w
set MIXER quad

