#!/bin/sh
#
# @name 3DR Iris Quadrotor SITL (Vision)
#
# @type Quadrotor Wide
#

sh /etc/init.d-posix/10016_iris

if [ $AUTOCNF = yes ]
then
	# EKF2: Vision position and heading
	param set EKF2_AID_MASK 24
	param set EKF2_EV_DELAY 5

	# INAV: trust more on the vision input
	param set INAV_W_XY_VIS_P 9
	param set INAV_W_Z_VIS_P 7
	param set INAV_W_XY_GPS_P 0
	param set INAV_W_XY_GPS_V 0
	param set INAV_W_Z_GPS_P 0

	# LPE: Vision + baro
	param set LPE_FUSION 132

	# AEQ: External heading set to use vision input
	param set ATT_EXT_HDG_M 1
fi
