#!/bin/sh
#
# @name 3DR Iris Quadrotor SITL (Vision Velocity)
#
# @type Quadrotor Wide
#

sh /etc/init.d-posix/10016_iris

if [ $AUTOCNF = yes ]
then
	# EKF2: Vision velocity and heading
	param set EKF2_AID_MASK 272
	param set EKF2_EV_DELAY 5
fi
