#!/bin/sh
#
# @name Standard VTOL
#
# @type Standard VTOL
#

sh /etc/init.d/rc.vtol_defaults

if [ $AUTOCNF = yes ]
then
	param set FW_AIRSPD_MAX 25
	param set FW_AIRSPD_MIN 14
	param set FW_AIRSPD_TRIM 16

	param set MC_ROLLRATE_P 0.3

	param set MIS_LTRMIN_ALT 10
	param set MIS_TAKEOFF_ALT 10
	param set MIS_YAW_TMT 10

	param set MPC_ACC_HOR_MAX 2
	param set MPC_ACC_HOR_MAX 2
	param set MPC_THR_MIN 0.1
	param set MPC_TKO_SPEED 1
	param set MPC_XY_P 0.8
	param set MPC_XY_VEL_D 0.005
	param set MPC_XY_VEL_I 0.2
	param set MPC_XY_VEL_P 0.15
	param set MPC_Z_VEL_MAX_DN 1.5

	param set NAV_ACC_RAD 5
	param set NAV_LOITER_RAD 80

	param set VT_F_TRANS_DUR 5
	param set VT_F_TRANS_THR 0.75
	param set VT_ARSP_TRANS 16
	param set VT_MOT_ID 1234
	param set VT_FW_MOT_OFFID 1234
	param set VT_TYPE 2


	param set MC_INERTIA_XX 1.0
	param set MC_INERTIA_YY 1.0
	param set MC_INERTIA_ZZ 1.0

	param set CA_AIRFRAME 2

	param set CA_ACT0_MIN 0.0
	param set CA_ACT1_MIN 0.0
	param set CA_ACT2_MIN 0.0
	param set CA_ACT3_MIN 0.0
	param set CA_ACT0_MAX 1.0
	param set CA_ACT1_MAX 1.0
	param set CA_ACT2_MAX 1.0
	param set CA_ACT3_MAX 1.0

	param set CA_ACT4_MAX 1.0
	param set CA_ACT4_MIN 0.0

	param set CA_ACT5_MAX 1.0
	param set CA_ACT5_MIN -1.0
	param set CA_ACT6_MAX 1.0
	param set CA_ACT6_MIN -1.0
	param set CA_ACT7_MAX 1.0
	param set CA_ACT7_MIN -1.0

fi

set MAV_TYPE 22

set MIXER standard_vtol
