#!/bin/sh
#
# @name Quadrotor + Tailsitter
#
# @type VTOL Quad Tailsitter
#

sh /etc/init.d/rc.vtol_defaults

if [ $AUTOCNF = yes ]
then
	param set FW_AIRSPD_MAX 25
	param set FW_AIRSPD_MIN 14
	param set FW_AIRSPD_TRIM 16

	param set MC_ROLLRATE_P 0.3

	param set MIS_LTRMIN_ALT 10
	param set MIS_TAKEOFF_ALT 10
	param set MIS_YAW_TMT 10

	param set MPC_ACC_HOR_MAX 2
	param set MPC_ACC_HOR_MAX 2
	param set MPC_THR_MIN 0.1
	param set MPC_TKO_SPEED 1
	param set MPC_XY_P 0.15
	param set MPC_XY_VEL_D 0.005
	param set MPC_XY_VEL_I 0.2
	param set MPC_XY_VEL_P 0.05
	param set MPC_Z_VEL_MAX_DN 1.5
	param set MPC_Z_VEL_P 0.8

	param set NAV_ACC_RAD 5
	param set NAV_LOITER_RAD 80

	param set VT_F_TRANS_DUR 1.5
	param set VT_F_TRANS_THR 0.7
	param set VT_MOT_COUNT 0
	param set VT_TYPE 0

	param set WEST_EN 1

	# Indicate that FW roll direction was fixed in mixer, to be removed in v1.10
	param set V19_VT_ROLLDIR 0
fi

set MAV_TYPE 20

set MIXER_FILE etc/mixers-sitl/quad_x_vtol.main.mix
set MIXER custom
