#!/bin/sh
#
# @name Typhoon H480 SITL
#
# @type Hexarotor x
#

sh /etc/init.d/rc.mc_defaults

if [ $AUTOCNF = yes ]
then
	param set MC_PITCHRATE_P 0.1
	param set MC_PITCHRATE_I 0.05
	param set MC_PITCH_P 6.0
	param set MC_ROLLRATE_P 0.15
	param set MC_ROLLRATE_I 0.1
	param set MC_ROLL_P 6.0
	param set MPC_XY_VEL_I 0.2
	param set MPC_XY_VEL_P 0.15

	param set RTL_DESCEND_ALT 10
	param set RTL_LAND_DELAY 0

	param set TRIG_INTERFACE 3
	param set TRIG_MODE 4
	param set MNT_MODE_IN 0
	param set MAV_PROTO_VER 2

	param set CA_AIRFRAME 1
	param set CA_ACT0_MIN 0.0
	param set CA_ACT1_MIN 0.0
	param set CA_ACT2_MIN 0.0
	param set CA_ACT3_MIN 0.0
	param set CA_ACT4_MIN 0.0
	param set CA_ACT5_MIN 0.0
	param set CA_ACT0_MAX 1.0
	param set CA_ACT1_MAX 1.0
	param set CA_ACT2_MAX 1.0
	param set CA_ACT3_MAX 1.0
	param set CA_ACT4_MAX 1.0
	param set CA_ACT5_MAX 1.0
fi

set MAV_TYPE 13

# set MIXER hexa_x
set MIXER hexa
