#!/bin/sh
#
# @name Hexarotor x with tilted arms
#
# @url http://theairlab.org/
#
# @type Tilt-Hexarotor
# @class Copter
#
# @output AUX1 feed-through of RC AUX1 channel
# @output AUX2 feed-through of RC AUX2 channel
# @output AUX3 feed-through of RC AUX3 channel
#
# @maintainer Azarakhsh Keipour <keipour@cmu.edu>
#

sh /etc/init.d/rc.mc_defaults

if [ $AUTOCNF = yes ]
then
	param set MC_PITCHRATE_P 0.1
	param set MC_ROLLRATE_P 0.1
	param set MC_YAWRATE_P 0.08
	param set MPC_Z_VEL_I 0.15
	param set MPC_Z_VEL_P 0.3
	param set MC_PITCHRATE_MAX 20.0
	param set MC_ROLLRATE_MAX 20.0
	param set MC_YAWRATE_MAX 60.0
	param set MPC_ACC_DOWN_MAX 2
	param set MPC_ACC_HOR 0.5
	param set MPC_ACC_HOR_MAX 2
	param set MPC_ACC_UP_MAX 2
	# param set MPC_XY_VEL_P 0.13
	# param set MPC_XY_VEL_MAX 4

	param set RTL_DESCEND_ALT 5.0
	param set RTL_LAND_DELAY 5

	param set SDLOG_PROFILE 179

	param set OMNI_ATT_MODE 2
	param set OMNI_DFC_MAX_THR 0.20
fi

set MAV_TYPE 13

# Set mixer
set MIXER hexa_tilt_x
