if(NOT RL_TOOLS_BACKEND_DISABLE_CUDA)
    cmake_minimum_required(VERSION 3.17)
    find_package(CUDAToolkit QUIET)
    if(CUDAToolkit_FOUND)
        message(STATUS "CUDAToolkit version: ${CUDAToolkit_VERSION}")
        message(STATUS "CUDAToolkit include path: ${CUDAToolkit_INCLUDE_DIRS}")
        message(STATUS "CUDAToolkit libraries: ${CUDAToolkit_LIBRARIES}")
        message(STATUS "CUDAToolkit cublas library: ${CUDAToolkit_CUBLAS_LIBRARIES}")
        set(CMAKE_CUDA_FLAGS_DEBUG "-g -G")
        set(CMAKE_CUDA_ARCHITECTURES "native")
        set(CMAKE_CUDA_COMPILER "${CUDAToolkit_NVCC_EXECUTABLE}")
        target_compile_definitions(rl_tools_full INTERFACE RL_TOOLS_BACKEND_ENABLE_CUDA)
        target_link_libraries(rl_tools_full INTERFACE CUDA::cublas)
        set(RL_TOOLS_BACKEND_ENABLE_CUDA ON)
    else()
        message(STATUS "CUDAToolkit not found, CUDA disabled.")
    endif()
endif()
