#!/bin/sh
# Rewrite the container's apt sources to prefer the AWS regional Ubuntu
# mirror that is local to the runs-on instance, while keeping the canonical
# archive.ubuntu.com as a fallback.
#
# The regional EC2 mirrors are fast and sync aggressively, but can briefly
# serve a stale package index that references a .deb version no longer on the
# mirror (e.g. mid-security-update), causing 404s.  Retaining the canonical
# archive as a fallback URI lets apt recover automatically.
#
# deb822 format (Noble/24.04+): supports space-separated fallback URIs on a
# single URIs: line — apt tries them in order.
# Legacy sources.list format (Jammy/22.04): no fallback URI support; we
# prepend a parallel deb line so both mirrors are consulted.
#
# This script is a no-op outside runs-on, so it is safe to call from any CI
# job (forks, self-hosted runners, local docker runs, etc.) without changing
# behavior there.
#
# Usage (from a workflow step running inside the container):
#   ./Tools/ci/use_aws_apt_mirror.sh

set -e

if [ -z "$RUNS_ON_AWS_REGION" ]; then
    echo "use_aws_apt_mirror: not running on runs-on (RUNS_ON_AWS_REGION unset), skipping"
    exit 0
fi

MIRROR="http://${RUNS_ON_AWS_REGION}.ec2.archive.ubuntu.com/ubuntu"
echo "use_aws_apt_mirror: preferring ${MIRROR} with canonical archive as fallback"

# Noble (24.04+) uses the deb822 format at /etc/apt/sources.list.d/ubuntu.sources.
# Space-separated URIs are tried in order; the canonical archive is kept as fallback.
if [ -f /etc/apt/sources.list.d/ubuntu.sources ]; then
    sed -i \
        -e "s|URIs: http://archive.ubuntu.com/ubuntu|URIs: ${MIRROR} http://archive.ubuntu.com/ubuntu|g" \
        -e "s|URIs: http://security.ubuntu.com/ubuntu|URIs: ${MIRROR} http://security.ubuntu.com/ubuntu|g" \
        /etc/apt/sources.list.d/ubuntu.sources
fi

# Jammy (22.04) and earlier use the legacy /etc/apt/sources.list.
# The legacy format has no fallback URI syntax, so prepend EC2 mirror deb
# lines before the original entries.  apt prefers sources listed earlier,
# so EC2 is tried first; the canonical archive acts as fallback for 404s.
if [ -f /etc/apt/sources.list ]; then
    EC2_LINES=$(sed \
        -e "s|http://archive.ubuntu.com/ubuntu|${MIRROR}|g" \
        -e "s|http://security.ubuntu.com/ubuntu|${MIRROR}|g" \
        /etc/apt/sources.list)
    ORIG_LINES=$(cat /etc/apt/sources.list)
    printf '%s\n\n# canonical archive (fallback)\n%s\n' \
        "$EC2_LINES" "$ORIG_LINES" > /etc/apt/sources.list
fi

# Add standard Ubuntu mirrors as fallback entries so apt can still resolve
# packages if regional mirror metadata lags briefly for specific revisions.
if [ -r /etc/os-release ]; then
    # shellcheck disable=SC1091
    . /etc/os-release
fi

CODENAME="${VERSION_CODENAME:-}"
if [ -z "${CODENAME}" ]; then
    echo "use_aws_apt_mirror: unable to determine distro codename, skipping fallback source generation"
else
    # Prefer the same mirror family the image already uses.
    # This avoids keeping a hardcoded architecture map here.
    if grep -Rqs "ubuntu-ports" /etc/apt/sources.list /etc/apt/sources.list.d 2>/dev/null; then
        FALLBACK_MAIN="http://ports.ubuntu.com/ubuntu-ports"
        FALLBACK_SECURITY="http://ports.ubuntu.com/ubuntu-ports"
    else
        FALLBACK_MAIN="http://archive.ubuntu.com/ubuntu"
        FALLBACK_SECURITY="http://security.ubuntu.com/ubuntu"
    fi

    FALLBACK_FILE="/etc/apt/sources.list.d/px4-ubuntu-fallback.list"
    cat <<EOF > "${FALLBACK_FILE}"
# Generated by Tools/ci/use_aws_apt_mirror.sh
deb ${FALLBACK_MAIN} ${CODENAME} main restricted universe multiverse
deb ${FALLBACK_MAIN} ${CODENAME}-updates main restricted universe multiverse
deb ${FALLBACK_MAIN} ${CODENAME}-backports main restricted universe multiverse
deb ${FALLBACK_SECURITY} ${CODENAME}-security main restricted universe multiverse
EOF

    echo "use_aws_apt_mirror: wrote fallback sources to ${FALLBACK_FILE}"
fi
