#!/usr/bin/env bash

REMOTE_URL="$2"  #URL you are pushing to
BRANCH=`git rev-parse --abbrev-ref HEAD` #branch name

# check if the branch you're pushing has a common ancestor with one of Auterion's private forks
REMOTE_PRIVATE=`git remote -v | grep "Auterion/PX4_firmware_private.git" | grep "(fetch)" | cut -f1`
COMMON_ANCESTOR_PRIVATE="$(git merge-base --fork-point $REMOTE_PRIVATE/develop $BRANCH 2>&1 )"

PX4_PUBLIC="PX4"
DST_ORG=$(echo $REMOTE_URL | cut -d ":" -f 2 | cut -d "/" -f 1) #get org you're pushing to

if [ $DST_ORG == $PX4_PUBLIC ] && [ ! -z "$COMMON_ANCESTOR_PRIVATE" ]
then
  read -p "You're about to push to PX4 upstream, is that what you intended? [y|N] " -n 1 -r < /dev/tty
  echo
  if echo $REPLY | grep -E '^[Yy]$' > /dev/null
  then
    exit 0 # push will execute
  fi
  exit 1 # push will not execute
else
  exit 0 # push will execute
fi
