module_name: atxxxx
parameters:
- group: OSD
  definitions:
    OSD_ATXXXX_CFG:
      description:
        short: Enable/Disable the ATXXX OSD Chip
        long: ATXXXX OSD chip on OmnibusF4SD board.
      type: enum
      values:
        0: Disabled
        1: NTSC
        2: PAL
      default: 0
      reboot_required: true
