name: Checks

on:
  push:
    branches:
    - 'main'
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/px4/px4-dev:v1.17.0-rc2

    strategy:
      fail-fast: true
      matrix:
        check: [
          "check_format",
          "check_newlines",
          "tests",
          "validate_module_configs",
          "shellcheck_all",
          "module_documentation",
        ]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Configure Git Safe Directory
        run: git config --system --add safe.directory '*'

      - uses: ./.github/actions/setup-ccache
        id: ccache
        if: matrix.check == 'tests'
        with:
          cache-key-prefix: ccache-sitl
          max-size: 300M

      - name: Building [${{ matrix.check }}]
        env:
          PX4_SBOM_DISABLE: 1
        run: |
          cd "$GITHUB_WORKSPACE"
          make ${{ matrix.check }}

      - uses: ./.github/actions/save-ccache
        if: always() && matrix.check == 'tests'
        with:
          cache-primary-key: ${{ steps.ccache.outputs.cache-primary-key }}
