name: Checks

on:
  push:
    branches:
    - 'develop'
    - 'release/*'
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: [runs-on,runner=64cpu-linux-x64,"run-id=${{ github.run_id }}"]
    strategy:
      fail-fast: false
      matrix:
        check: [
          "check_format",
          "check_newlines",
          "tests",
          "tests_coverage",
          "validate_module_configs",
          "shellcheck_all",
          "NO_NINJA_BUILD=1 px4_sitl_default",
          "px4_sitl_allyes",
          "module_documentation",
        ]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.AUTERION_CI_ACCESS_TOKEN }}

      - name: Building [${{ matrix.check }}]
        uses: addnab/docker-run-action@v3
        with:
          image: px4io/px4-dev:v1.16.0-rc1-258-g0369abd556
          options: -v ${{ github.workspace }}:/workspace
          run: |
            cd /workspace
            git config --global --add safe.directory /workspace
            make ${{ matrix.check }}
