name: deploy to customer repo

on:
  workflow_run:
    workflows: ["Build and deploy APX4 release"]
    types:
      - completed


jobs:
  deploy-release-branches:
    name: Create release branch in customer repos
    runs-on: [runs-on,runner=8cpu-linux-x64,"run-id=${{ github.run_id }}"]
    container: px4io/px4-dev:v1.16.0-ondemand
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTERION_CI_ACCESS_TOKEN }}
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: 0
          submodules: 'recursive'

      - name: Set initial references
        id: references
        run: |
          TAG_BRANCH="${{ github.event.workflow_run.head_branch }}"
          REF_BRANCH=$(git branch -a --contains "tags/$TAG_BRANCH" | sed -n "s/.*\(release\/[0-9]\.[0-9]\).*/\1/p" | head -n 1)
          VALID_RELEASE="^v[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{1,2}-[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{1,2}$"
          if [ -z "$REF_BRANCH" ]; then
            echo "Branch does not match release/X.X pattern, skipping customer deploy"
            exit 0
          fi
          if [[ ! "$TAG_BRANCH" =~ $VALID_RELEASE ]]; then
            echo "Tag does not match vX.X.X-X.X.X pattern, skipping customer deploy"
            exit 0
          fi
          echo "tag_branch=${TAG_BRANCH}" >> $GITHUB_OUTPUT
          echo "release_branch=${REF_BRANCH}" >> $GITHUB_OUTPUT

      - name: Push release branch to customers repos
        shell: bash
        env:
          CUSTOM_LIST: ${{ secrets.CUSTOM_LIST }}
        run: |
          git config --global --add safe.directory '*'
          git config --global url."https://${{ secrets.AUTERION_CI_ACCESS_TOKEN }}:@github.com/".insteadOf "https://github.com/"

          echo "${CUSTOM_LIST%,}" | tr ',' '\n' > list
          failure=0

          while read url; do
            if ! git ls-remote "$url" &> /dev/null; then
              echo "::warning::Repository $url is not accessible, skipping."
              failure=1
              continue
            fi

            remote=$(basename "$url" .git)
            git remote add "$remote" "$url"
            if ! git push -u "$remote" HEAD:refs/tags/${{ steps.references.outputs.tag_branch }}; then
              echo "::warning::Failed to push tag to $url"
            fi
            if ! git push -u "$remote" HEAD:refs/heads/${{ steps.references.outputs.release_branch }}; then
              echo "::warning::Failed to push branch to $url"
              failure=1
            fi
            git remote remove "$remote"
          done < list

          if (( failure )); then
            exit 1
          fi
