name: Fuzzing
on:
  schedule:
    - cron: '0 6 * * *'  # UTC 6am every day.

permissions:
  contents: read
  issues: write # for JasonEtco/create-an-issue

env:
  RUNS_IN_DOCKER: true

jobs:
  Fuzzing:
    runs-on: [runs-on,runner=4cpu-linux-x64,image=ubuntu24-full-x64,"run-id=${{ github.run_id }}",spot=false,extras=s3-cache]
    container:
      image: px4io/px4-dev:v1.16.0-rc2-4-gb67c65bfe6
    steps:
      - uses: runs-on/action@v2

      - uses: actions/checkout@v6

      - name: Configure Git Safe Directory
        run: git config --system --add safe.directory '*'

      - name: Install clang
        run: apt-get update && apt-get install -y clang

      - uses: ./.github/actions/setup-ccache
        id: ccache
        with:
          cache-key-prefix: ccache-sitl
          max-size: 300M

      - name: Build and Run Fuzz Tests
        run: |
          # Only build the tests
          export CC=clang
          export CXX=clang++
          make tests TESTFILTER=__no_tests__

          # Run the fuzz tests
          for fuzz_binary in build/px4_sitl_test/*fuzz*; do
            ./Tools/ci/run_fuzz_tests.sh $fuzz_binary 15m
          done

      - uses: ./.github/actions/save-ccache
        if: always()
        with:
          cache-primary-key: ${{ steps.ccache.outputs.cache-primary-key }}

      - name: Create Issue
        if: ${{ failure() }}
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKFLOW_RUN_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        with:
          filename: .github/fuzzing_issue_template.md
