name: Python CI Checks

on:
  push:
    branches:
    - 'main'
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install tools
      run: pip install mypy types-requests flake8

    - name: Check MAVSDK test scripts with mypy
      run: mypy --strict test/mavsdk_tests/*.py

    - name: Check MAVSDK test scripts with flake8
      run: flake8 test/mavsdk_tests/*.py
