name: Release ROS2 messages

on:
  release:
    types: [created]

jobs:
  trigger_release_on_px4_msgs:
    if: startsWith(github.event.release.target_commitish, 'release/') && github.event.release.prerelease == false
    runs-on: [runs-on,runner=8cpu-linux-x64,"run-id=${{ github.run_id }}"]
    steps:
      - name: Validate release tag
        run: |
          if [[ ! ${{ github.event.release.tag_name }} =~ ^v[0-9]+\.[0-9]+\.[0-9]+-[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid tag for release: ${{ github.event.release.tag_name }}. Skipping workflow"
            exit 1
          fi

      - name: Extract release version
        id: extract_version
        run: |
          # Extract version from the APX4 tag name
          # e.g. v1.14.0-3.0.8 -> 3.0.8
          release_version=$(echo ${{ github.event.release.tag_name }} | grep -oP '(?<=-)[0-9]+\.[0-9]+\.[0-9]+')
          echo "release_version=$release_version" >> $GITHUB_OUTPUT

      - name: Fetch last release tag from px4_msgs
        id: get_last_tag
        run: |
          last_tag_response=$(curl -L -H "Accept: application/vnd.github+json" \
                                    -H "Authorization: Bearer ${{ secrets.AUTERION_CI_ACCESS_TOKEN }}" \
                                    -H "X-GitHub-Api-Version: 2022-11-28" \
                                    "https://api.github.com/repos/Auterion/px4_msgs/releases/latest")
          last_tag=$(echo "${last_tag_response}" | jq -r '.tag_name')
          echo "API response: ${last_tag_response}"
          echo "last_tag=${last_tag}" >> $GITHUB_OUTPUT

      - name: Create GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.AUTERION_CI_ACCESS_TOKEN }}
        with:
          owner: "Auterion"
          repo: "px4_msgs"
          commitish: ${{ github.event.release.target_commitish }}
          tag_name: ${{ steps.extract_version.outputs.release_version }}
          release_name: ${{ steps.extract_version.outputs.release_version }}
          body: |
            Release triggered by APX4 release ${{ github.event.release.tag_name }}

            Full Changelog: [${{ steps.get_last_tag.outputs.last_tag }}...${{ steps.extract_version.outputs.release_version }}](https://github.com/Auterion/px4_msgs/compare/${{ steps.get_last_tag.outputs.last_tag }}...${{ steps.extract_version.outputs.release_version }})
          draft: false
          prerelease: false
