name: Sync with upstream

# Schedule for 04:00 UTC on Mondays, or on manual trigger
on:
  workflow_dispatch:
  schedule:
    - cron: '00 4 * * 1'

jobs:
  open_pr:
    name: Open PR from upstream
    runs-on: [runs-on,runner=8cpu-linux-x64,image=ubuntu22-full-x64,"run-id=${{ github.run_id }}",spot=false]
    steps:
      - name: Determine PR branch name
        run: |
          PR_BRANCH_NAME=upstream-merge-$(date '+%Y-%m-%d')
          echo "pr_branch_name=$PR_BRANCH_NAME" >> $GITHUB_ENV
          echo "PR branch will be $PR_BRANCH_NAME"
      - name: Sync upstream/main with PR branch
        uses: wei/git-sync@v3
        with:
          source_repo: "https://auterion-ci:${{ secrets.AUTERION_CI_ACCESS_TOKEN }}@github.com/PX4/PX4-Autopilot.git"
          source_branch: main
          destination_repo: "https://auterion-ci:${{ secrets.AUTERION_CI_ACCESS_TOKEN }}@github.com/$GITHUB_REPOSITORY"
          destination_branch: ${{ env.pr_branch_name }}
      - name: Open PR to Auterion/develop
        env:
          GITHUB_TOKEN: ${{ secrets.AUTERION_CI_ACCESS_TOKEN }}
        run: |
          echo "**Sync time:** $(date '+%Y-%m-%d %H:%M:%S %Z %z')" > pr_body.md
          echo "> [!IMPORTANT]" >> pr_body.md
          echo "> ### Merge with a merge commit." >> pr_body.md
          echo "> Do not rebase." >> pr_body.md
          gh pr create \
            --repo $GITHUB_REPOSITORY \
            --base develop \
            --head ${{ env.pr_branch_name }} \
            --reviewer sfuhrer,bkueng \
            --title "chore(upstream): merge $(date '+%Y-%m-%d')" \
            --body-file pr_body.md
