name: tiiuae-coverity-scan-image

on:
  # Run only manually
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  coverity-scan-image:
    name: create coverity scan image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout px4-firmware
        uses: actions/checkout@v4
        with:
          path: px4-firmware
          fetch-depth: 0
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/tiiuae/px4-coverity-scan-image
          tags: |
            type=raw,value=latest
            type=sha
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push coverity scan image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./px4-firmware/packaging/Dockerfile.coverity
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            "COVERITY_DOCKER_REGISTRY_USERNAME=${{ secrets.COVERITY_DOCKER_REGISTRY_USERNAME }}"
            "COVERITY_DOCKER_REGISTRY_ACCESS_TOKEN=${{ secrets.COVERITY_DOCKER_REGISTRY_ACCESS_TOKEN }}"
            "COVERITY_LICENSE_DAT_B64=${{ secrets.COVERITY_LICENSE_DAT_B64 }}"
            "COVERITY_ACCESS_TOKEN_B64=${{ secrets.COVERITY_ACCESS_TOKEN_B64 }}"
