name: tiiuae-px4-coverity-scan

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
jobs:
  coverity:
    runs-on: px4-self-hosted-coverity
    steps:
      - name: Checkout px4-firmware
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_REPO_TOKEN }}
          submodules: 'recursive'
          fetch-depth: 0
      - name: Fetch submodule tags
        run: |
          git submodule foreach --recursive git fetch --tags
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run coverity scan
        run:
          docker run --rm -v "$(pwd):/main_ws" ghcr.io/tiiuae/px4-coverity-scan-image:latest
      - name: Update summary
        run:
          cat cov-analyze-result.txt >> $GITHUB_STEP_SUMMARY
      - name: Upload coverity scan results
        uses: actions/upload-artifact@v3.1.3
        with:
          name: coverity-html-report-${{ github.event.repository.name }}
          path: coverity-output
