function T_MAG = transfer_matrix(magE,magN)
%TRANSFER_MATRIX
%    T_MAG = TRANSFER_MATRIX(MAGE,MAGN)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    29-May-2017 00:16:16

t2 = 1.0./magN.^2;
t3 = magE.^2;
t4 = t2.*t3;
t5 = t4+1.0;
t6 = 1.0./t5;
T_MAG = [-magE.*t2.*t6,t6./magN];
